read:
  db: pccon
  sql:
    SELECT
      CodColecao
    FROM TAB_Colecao

functions:
  - sequence:
      count:
        start: 11

columns:
  - sequence:
      type: n
      args:
        format: '%d'
  - CodColecao: t
