csv:

  fields:

    LINHA_PRODUTO:
      type: integer

  keys:
    - NIVEL_ESTRUTURA
    - LINHA_PRODUTO

sql:

  db: systextil

  key_count: |
    SELECT
      count(LINHA_PRODUTO)
    FROM BASI_120
    WHERE NIVEL_ESTRUTURA=:NIVEL_ESTRUTURA
      AND LINHA_PRODUTO=:LINHA_PRODUTO

  update: |
    UPDATE SYSTEXTIL.BASI_120 SET
      DESCRICAO_LINHA=:DESCRICAO_LINHA
    WHERE NIVEL_ESTRUTURA=:NIVEL_ESTRUTURA
      AND LINHA_PRODUTO=:LINHA_PRODUTO

  insert: |
    INSERT INTO BASI_120
    ( LINHA_PRODUTO
    , DESCRICAO_LINHA
    , NIVEL_ESTRUTURA
    )
    VALUES
    ( :LINHA_PRODUTO
    , :DESCRICAO_LINHA
    , :NIVEL_ESTRUTURA
    )

  key_list: |
    SELECT
      NIVEL_ESTRUTURA
    , LINHA_PRODUTO
    FROM BASI_120
    WHERE NIVEL_ESTRUTURA='1'

  delete: |
    DELETE FROM BASI_120
    WHERE NIVEL_ESTRUTURA=:NIVEL_ESTRUTURA
      AND LINHA_PRODUTO=:LINHA_PRODUTO

  fault_delete: |
    UPDATE SYSTEXTIL.BASI_120 SET
      DESCRICAO_LINHA = substr('##' || DESCRICAO_LINHA, 1, 40)
    WHERE NIVEL_ESTRUTURA=:NIVEL_ESTRUTURA
      AND LINHA_PRODUTO=:LINHA_PRODUTO
      and DESCRICAO_LINHA not like '##%'
