csv:

  keys:
    - REFERENCIA
    - TAM
    - COR

sql:

  db: systextil

  key_count: |
    SELECT
      count(GRUPO_ESTRUTURA)
    FROM BASI_010
    WHERE NIVEL_ESTRUTURA = '1'
      AND GRUPO_ESTRUTURA = :REFERENCIA
      AND SUBGRU_ESTRUTURA = :TAM
      AND ITEM_ESTRUTURA = :COR

  update: |
    UPDATE BASI_010 SET
      CODIGO_VELHO = :CODITEMPROD || '.' || :CODTAM || '.' || :CODCOR
    , DESCRICAO_15 = substr(:DESCRCOR, 1, 20)
    , COMPLEMENTO = :DESCRCOR
    , NARRATIVA = (
        (
          SELECT
            DESCR_REFERENCIA
          FROM BASI_030
          WHERE NIVEL_ESTRUTURA = '1'
            AND REFERENCIA = :REFERENCIA
        ) || ' ' || (
          SELECT
            DESCR_TAM_REFER
          FROM SYSTEXTIL.BASI_020
          WHERE BASI030_NIVEL030='1'
            AND BASI030_REFERENC=:REFERENCIA
            AND TAMANHO_REF=:TAM
        ) || ' ' || (
          SELECT
            DESCRICAO
          FROM BASI_100
          WHERE COR_SORTIMENTO = :COR
            AND TIPO_COR = 1
        )
      )
    , CLASSIFIC_FISCAL = '0'
    , DATA_CADASTRO = TIMESTAMP '2017-01-24 00:00:00.000000'
    , NUMERO_ROTEIRO = 1
    , NUMERO_ALTERNATI = 1
    , ALTERNATIVA_CUSTOS = 1
    , ROTEIRO_CUSTOS = 1
    WHERE NIVEL_ESTRUTURA = 1
      AND GRUPO_ESTRUTURA = :REFERENCIA
      AND SUBGRU_ESTRUTURA = :TAM
      AND ITEM_ESTRUTURA = :COR

  insert: |
    INSERT INTO BASI_010
    (
      NIVEL_ESTRUTURA
    , GRUPO_ESTRUTURA
    , SUBGRU_ESTRUTURA
    , ITEM_ESTRUTURA
    , CODIGO_VELHO
    , DESCRICAO_15
    , COMPLEMENTO
    , NARRATIVA
    , CLASSIFIC_FISCAL
    , DATA_CADASTRO
    , NUMERO_ROTEIRO
    , NUMERO_ALTERNATI
    , ALTERNATIVA_CUSTOS
    , ROTEIRO_CUSTOS
    ) VALUES (
      1
    , :REFERENCIA
    , :TAM
    , :COR
    , :CODITEMPROD || '.' || :CODTAM || '.' || :CODCOR
    , substr(:DESCRCOR, 1, 20)
    , :DESCRCOR
    , (
        (
          SELECT
            DESCR_REFERENCIA
          FROM BASI_030
          WHERE NIVEL_ESTRUTURA = '1'
            AND REFERENCIA = :REFERENCIA
        ) || ' ' || (
          SELECT
            DESCR_TAM_REFER
          FROM SYSTEXTIL.BASI_020
          WHERE BASI030_NIVEL030='1'
            AND BASI030_REFERENC=:REFERENCIA
            AND TAMANHO_REF=:TAM
        ) || ' ' || (
          SELECT
            DESCRICAO
          FROM BASI_100
          WHERE COR_SORTIMENTO = :COR
            AND TIPO_COR = 1
        )
      )
    , '0' -- CLASSIFIC_FISCAL
    , TIMESTAMP '2017-01-24 00:00:00.000000' -- DATA_CADASTRO
    , 1 -- NUMERO_ROTEIRO
    , 1 -- NUMERO_ALTERNATI
    , 1 -- ALTERNATIVA_CUSTOS
    , 1 -- ROTEIRO_CUSTOS
    )

  key_list: |
    SELECT
      rtc.GRUPO_ESTRUTURA
    , rtc.SUBGRU_ESTRUTURA
    , rtc.ITEM_ESTRUTURA
    FROM BASI_010 rtc
    LEFT JOIN BASI_030 rb
      ON rb.REFERENCIA = rtc.GRUPO_ESTRUTURA
    WHERE rtc.NIVEL_ESTRUTURA='1'
      AND rb.CODIGO_CONTABIL=99
      AND substr(rtc.GRUPO_ESTRUTURA, 1, 1) in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '0')

  delete: |
    DELETE FROM BASI_010
    WHERE NIVEL_ESTRUTURA='1'
      AND GRUPO_ESTRUTURA=:REFERENCIA
      AND SUBGRU_ESTRUTURA=:TAM
      AND ITEM_ESTRUTURA=:COR
