csv:

  first: 19999

  columns:
    - NIVEL_ESTRUTURA
    - REFERENCIA
    - COD_ANT_MD
    - DESCRICAO
    - UNIDMEDIDA
    - CONTA_ESTOQUE
    - CODIGO_CONTABIL
    - ARTIGO
    - CODCOLECAO
    - CLASSIFIC_FISCAL

  fields:

    CONTA_ESTOQUE:
      type: integer

  keys:
    - NIVEL_ESTRUTURA
    - REFERENCIA

sql:

  db: systextil

  key_count: |
    SELECT
      count(REFERENCIA)
    FROM BASI_030
    WHERE NIVEL_ESTRUTURA=:NIVEL_ESTRUTURA
      AND REFERENCIA=:REFERENCIA

  update: |
    UPDATE BASI_030 SET
      DESCR_REFERENCIA= substr(:COD_ANT_MD || ' ' ||:DESCRICAO, 1, 30)
    , UNIDADE_MEDIDA=:UNIDMEDIDA
    , CONTA_ESTOQUE=:CONTA_ESTOQUE
    , CODIGO_CONTABIL=:CODIGO_CONTABIL
    , COMPRADO_FABRIC=2
    , CLASSIFIC_FISCAL=:CLASSIFIC_FISCAL
    , LINHA_PRODUTO=12
    , ARTIGO=:ARTIGO
    , COLECAO=:CODCOLECAO
    WHERE NIVEL_ESTRUTURA=:NIVEL_ESTRUTURA
      AND REFERENCIA=:REFERENCIA

  insert: |
    INSERT INTO BASI_030
    ( NIVEL_ESTRUTURA
    , REFERENCIA
    , DESCR_REFERENCIA
    , UNIDADE_MEDIDA
    , CONTA_ESTOQUE
    , CODIGO_CONTABIL
    , COMPRADO_FABRIC
    , CLASSIFIC_FISCAL
    , LINHA_PRODUTO
    , ARTIGO
    , COLECAO
    ) VALUES (
      :NIVEL_ESTRUTURA
    , :REFERENCIA
    , substr(:COD_ANT_MD || ' ' ||:DESCRICAO, 1, 30)
    , :UNIDMEDIDA
    , :CONTA_ESTOQUE
    , :CODIGO_CONTABIL
    , 2
    , :CLASSIFIC_FISCAL
    , 12
    , :ARTIGO
    , :CODCOLECAO
    )

  after_insert_update:

    columns:
      - NIVEL_ESTRUTURA
      - REFERENCIA

    command: |
      UPDATE BASI_030 SET
        LINHA_PRODUTO=11
      WHERE NIVEL_ESTRUTURA=:NIVEL_ESTRUTURA
        AND REFERENCIA=:REFERENCIA
        AND DESCR_REFERENCIA like '%COSTU%'

  key_list: |
    SELECT
      NIVEL_ESTRUTURA
    , REFERENCIA
    FROM BASI_030
    WHERE NIVEL_ESTRUTURA = '1'
      AND substr(REFERENCIA, 1, 1) in ('M', 'N', 'P', 'Q', 'W', 'Y')
      AND REFERENCIA not like '%00%'
      AND substr(REFERENCIA, 2, 2) = '00'

  delete: |
    DELETE FROM BASI_030
    WHERE NIVEL_ESTRUTURA=:NIVEL_ESTRUTURA
      AND REFERENCIA=:REFERENCIA
