csv:

  keys:
    - REFERENCIA
    - TAM

sql:

  db: systextil

  key_count: |
    SELECT
      count(BASI030_REFERENC)
    FROM BASI_020
    WHERE BASI030_NIVEL030=1
      AND BASI030_REFERENC=:REFERENCIA
      AND TAMANHO_REF=:TAM

  update: |
    UPDATE BASI_020 SET
      DESCR_TAM_REFER=
        case when :CATALOGODOTAMAMANHO is null
          then ( select t.DESCR_TAMANHO FROM basi_220 t where t.TAMANHO_REF = :TAM )
          else :CATALOGODOTAMAMANHO
        end
    , DESC_TAM_FICHA=:CODITEMPROD
    , TIPO_PRODUTO = 1
    WHERE BASI030_NIVEL030=1
      AND BASI030_REFERENC=:REFERENCIA
      AND TAMANHO_REF=:TAM

  insert: |
    INSERT INTO BASI_020
    ( BASI030_NIVEL030
    , BASI030_REFERENC
    , TAMANHO_REF
    , DESCR_TAM_REFER
    , DESC_TAM_FICHA
    , TIPO_PRODUTO
    ) VALUES (
      1
    , :REFERENCIA
    , :TAM
    , case when :CATALOGODOTAMAMANHO is null
      then ( select t.DESCR_TAMANHO FROM basi_220 t where t.TAMANHO_REF = :TAM )
      else :CATALOGODOTAMAMANHO
      end
    , :CODITEMPROD
    , 1
    )

  key_list: |
    SELECT
      rt.BASI030_REFERENC
    , rt.TAMANHO_REF
    FROM BASI_020 rt
    WHERE rt.BASI030_NIVEL030=1
      AND substr(rt.BASI030_REFERENC, 1, 1) in ('1', '2', '3', '4', '5', '6', '7', '8', '9', '0')
      AND rt.BASI030_REFERENC not like '%00%'

  delete: |
    DELETE FROM BASI_020
    WHERE BASI030_NIVEL030=1
      AND BASI030_REFERENC=:REFERENCIA
      AND TAMANHO_REF=:TAM
