csv:

  fields:

    ARTIGO:
      type: integer

  keys:
    - ARTIGO
    - NIVEL_ESTRUTURA

sql:

  db: systextil

  key_count: |
    SELECT
      count(ARTIGO)
    FROM BASI_290
    WHERE NIVEL_ESTRUTURA=:NIVEL_ESTRUTURA
      AND ARTIGO=:ARTIGO

  update: |
    UPDATE SYSTEXTIL.BASI_290 SET
      DESCR_ARTIGO=:DESCR_ARTIGO
    WHERE NIVEL_ESTRUTURA=:NIVEL_ESTRUTURA
      AND ARTIGO=:ARTIGO

  insert: |
    INSERT INTO BASI_290
    ( NIVEL_ESTRUTURA
    , ARTIGO
    , DESCR_ARTIGO
    )
    VALUES
    ( :NIVEL_ESTRUTURA
    , :ARTIGO
    , :DESCR_ARTIGO
    )

  key_list: |
    SELECT
      ARTIGO
    , NIVEL_ESTRUTURA
    FROM BASI_290
    WHERE NIVEL_ESTRUTURA='1'

  delete: |
    DELETE FROM BASI_290
    WHERE NIVEL_ESTRUTURA=:NIVEL_ESTRUTURA
      AND ARTIGO=:ARTIGO

  fault_delete: |
    UPDATE SYSTEXTIL.BASI_290 SET
      DESCR_ARTIGO=substr('##' || DESCR_ARTIGO, 1, 25)
    WHERE NIVEL_ESTRUTURA=:NIVEL_ESTRUTURA
      AND ARTIGO=:ARTIGO
      and DESCR_ARTIGO not like '##%'
