INSERT INTO PEDI_150 (
  CD_CLI_CGC_CLI9
, CD_CLI_CGC_CLI4
, CD_CLI_CGC_CLI2
, SEQ_ENDERECO
, TIPO_ENDERECO
, END_ENTR_COBR
, CGC_ENTR_COBR9
, CGC_ENTR_COBR4
, CGC_ENTR_COBR2
, IE_ENTR_COBR
, CEP_ENTR_COBR
, BAIRRO_ENTR_COBR
, CID_ENTR_COBR
, FONE_ENTR_COBR
, GERA_NOTA_ENTREG
, CIDADE_CIF
, NOME_COMPLEMENTO
, FONE_COMPLEMENTO
, CEP_COMPLEMENTO
, TRANSP_REDESPACHO9
, TRANSP_REDESPACHO4
, TRANSP_REDESPACHO2
, NUMERO_IMOVEL
, COMPLEMENTO_ENDERECO
, FLAG_EXPORTACAO_LOJA
) SELECT
  c.CGC_9 -- CD_CLI_CGC_CLI9
, c.CGC_4 -- CD_CLI_CGC_CLI4
, c.CGC_2 -- CD_CLI_CGC_CLI2
, 1 -- SEQ_ENDERECO
, 1 -- TIPO_ENDERECO (entrega)
, c.ENDERECO_CLIENTE -- END_ENTR_COBR
, c.CGC_9 -- CGC_ENTR_COBR9
, c.CGC_4 -- CGC_ENTR_COBR4
, c.CGC_2 -- CGC_ENTR_COBR2
, c.INSC_EST_CLIENTE -- IE_ENTR_COBR
, c.CEP_CLIENTE -- CEP_ENTR_COBR
, c.BAIRRO -- BAIRRO_ENTR_COBR
, c.COD_CIDADE -- CID_ENTR_COBR
, 0 -- FONE_ENTR_COBR
, 0 -- GERA_NOTA_ENTREG (nao gera)
, 0 -- CIDADE_CIF
, '' -- NOME_COMPLEMENTO
, '' -- FONE_COMPLEMENTO
, '' -- CEP_COMPLEMENTO
, 0 -- TRANSP_REDESPACHO9
, 0 -- TRANSP_REDESPACHO4
, 0 -- TRANSP_REDESPACHO2
, c.NUMERO_IMOVEL -- NUMERO_IMOVEL
, c.COMPLEMENTO -- COMPLEMENTO_ENDERECO
, 0 -- FLAG_EXPORTACAO_LOJA
--, c.*
FROM PEDI_010 c
WHERE NOT (  -- filtro só necessário pois já haviam incluido esses endereços
     (c.CGC_9 = 92754738 AND c.CGC_4 = 203 )
  OR (c.CGC_9 = 9339936 AND c.CGC_4 = 2 )
  )
