INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(6, 'SAEDI', 1, 1, 7110537, 1, 53, 0, 0, 0, 100, 2500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(10, 'LUIMAR', 1, 1, 18474482, 1, 87, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(12, 'COUNTRY', 1, 1, 497744, 1, 64, 0, 0, 0, 100, 1200, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(13, 'JIREH', 1, 1, 2081699, 1, 93, 0, 0, 0, 100, 2100, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(26, 'EBENEZER', 1, 1, 5102799, 1, 48, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(100, 'TEAR 100', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(101, 'TEAR 101', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(102, 'TEAR 102', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(1100, 'COSTURA 12', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(1200, 'COSTURA 13', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(1300, 'COSTURA 14', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(1400, 'COSTURA 15', 1, 0, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(2100, 'COSTURA 8920', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(2200, 'COSTURA 8921', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(2300, 'COSTURA 8922', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(2400, 'COSTURA 8923', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(2500, 'COSTURA 8924', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(2600, 'COSTURA 8925', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3001, 'TEAR 1', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3002, 'TEAR 2', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3003, 'TEAR 3', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3004, 'TEAR 4', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3005, 'TEAR 5', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3006, 'TEAR 6', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3007, 'TEAR 7', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3008, 'TEAR 8', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3009, 'TEAR 9', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3010, 'TEAR 10', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3011, 'TEAR 11', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3012, 'TEAR 12', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3013, 'TEAR 13', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3014, 'TEAR 14', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3015, 'TEAR 15', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3016, 'TEAR 16', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3017, 'TEAR 17', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3018, 'TEAR 18', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3019, 'TEAR 19', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3020, 'TEAR 20', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3021, 'TEAR 21', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3022, 'TEAR 22', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3023, 'TEAR 23', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3024, 'TEAR 24', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3025, 'TEAR 25', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3026, 'TEAR 26', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3027, 'TEAR 27', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3028, 'TEAR 28', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3029, 'TEAR 29', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3030, 'TEAR 30', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3031, 'TEAR 31', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3032, 'TEAR 32', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(3033, 'TEAR 33', 1, 1, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.BASI_180
(DIVISAO_PRODUCAO, DESCRICAO, AREA_PRODUCAO, CENTRO_CUSTO, FACCIONISTA9, FACCIONISTA4, FACCIONISTA2, CAPACIDADE_DIA, DEPOSITO, LEAD_TIME, PERC_EFICIENCIA, QTDE_CAPAC_DIA, ABASTECIMENTO, QTDE_MAX_REF, ROTA_ABASTECI, TIPO_LINHA, VLR_MAX_OCORRENCIA, MIN_COST, CODIGO_RESPONSAVEL)
VALUES(4000, 'CORTE', 1, 0, 0, 0, 0, 0, 0, 0, 100, 1500, 0, 0, 0, 0, 0, 0, 0);
