SELECT
  r.NIVEL_ESTRUTURA
, r.GRUPO_ESTRUTURA
, r.SUBGRU_ESTRUTURA
, r.ITEM_ESTRUTURA
, r.NUMERO_ALTERNATI
, r.NUMERO_ROTEIRO
, r.SEQ_OPERACAO
, r.CODIGO_OPERACAO
, r.MINUTOS
, r.CODIGO_ESTAGIO
, r.CENTRO_CUSTO
, r.SEQUENCIA_ESTAGIO
, r.ESTAGIO_ANTERIOR
, r.ESTAGIO_DEPENDE
, r.SEPARA_OPERACAO
, r.MINUTOS_HOMEM
, r.CCUSTO_HOMEM
, r.NUMERO_CORDAS
, r.NUMERO_ROLOS
, r.VELOCIDADE
, r.CODIGO_FAMILIA
, r.OBSERVACAO
, r.TIPO_PROCESSO
, r.PECAS_1_HORA
, r.PECAS_8_HORAS
, r.CUSTO_MINUTO
, r.PERC_EFICIENCIA
, r.TEMPERATURA
, r.TEMPO_LOTE_PRODUCAO
, r.PECAS_LOTE_PRODUCAO
, r.TIME_CELULA
, r.CODIGO_APARELHO
, r.PERC_EFIC_ROT
, r.NUMERO_OPERADORAS
, r.CONSIDERA_EFIC
, r.SEQ_OPERACAO_AGRUPADORA
, r.CODIGO_PARTE_PECA
, r.SEQ_JUNCAO_PARTE_PECA
, r.SITUACAO
, r.PERC_PERDAS
, r.PERC_CUSTOS
FROM MQOP_050 r
WHERE r.GRUPO_ESTRUTURA > '99999'
  AND r.NUMERO_ROTEIRO = 1
  -- AND r.CODIGO_OPERACAO = 33
  AND r.SEQ_OPERACAO > 60
ORDER BY
  r.GRUPO_ESTRUTURA
, r.SEQ_OPERACAO

----

SELECT
  r.NIVEL_ESTRUTURA
, r.GRUPO_ESTRUTURA
, count(*)
FROM MQOP_050 r
WHERE r.GRUPO_ESTRUTURA > '99999'
  AND r.NUMERO_ROTEIRO = 1
GROUP BY
  r.NIVEL_ESTRUTURA
, r.GRUPO_ESTRUTURA
ORDER BY
  r.GRUPO_ESTRUTURA

-- vvvvvvvvvvvvvvvvv executar

UPDATE MQOP_050 r
SET
  r.SEQUENCIA_ESTAGIO = r.SEQUENCIA_ESTAGIO + 1
WHERE r.GRUPO_ESTRUTURA > '99999'
  AND r.NUMERO_ROTEIRO = 1
  AND r.SEQ_OPERACAO > 60
;

INSERT INTO SYSTEXTIL.MQOP_050
(NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRU_ESTRUTURA, ITEM_ESTRUTURA, NUMERO_ALTERNATI, NUMERO_ROTEIRO, SEQ_OPERACAO, CODIGO_OPERACAO, MINUTOS, CODIGO_ESTAGIO, CENTRO_CUSTO, SEQUENCIA_ESTAGIO, ESTAGIO_ANTERIOR, ESTAGIO_DEPENDE, SEPARA_OPERACAO, MINUTOS_HOMEM, CCUSTO_HOMEM, NUMERO_CORDAS, NUMERO_ROLOS, VELOCIDADE, CODIGO_FAMILIA, OBSERVACAO, TIPO_PROCESSO, PECAS_1_HORA, PECAS_8_HORAS, CUSTO_MINUTO, PERC_EFICIENCIA, TEMPERATURA, TEMPO_LOTE_PRODUCAO, PECAS_LOTE_PRODUCAO, TIME_CELULA, CODIGO_APARELHO, PERC_EFIC_ROT, NUMERO_OPERADORAS, CONSIDERA_EFIC, SEQ_OPERACAO_AGRUPADORA, CODIGO_PARTE_PECA, SEQ_JUNCAO_PARTE_PECA, SITUACAO, PERC_PERDAS, PERC_CUSTOS)
SELECT
  r.NIVEL_ESTRUTURA
, r.GRUPO_ESTRUTURA
, r.SUBGRU_ESTRUTURA
, r.ITEM_ESTRUTURA
, r.NUMERO_ALTERNATI
, r.NUMERO_ROTEIRO
, 65 SEQ_OPERACAO
, 45 CODIGO_OPERACAO
, r.MINUTOS
, 45 CODIGO_ESTAGIO
, r.CENTRO_CUSTO
, 6 SEQUENCIA_ESTAGIO
, r.ESTAGIO_ANTERIOR
, r.ESTAGIO_DEPENDE
, r.SEPARA_OPERACAO
, r.MINUTOS_HOMEM
, r.CCUSTO_HOMEM
, r.NUMERO_CORDAS
, r.NUMERO_ROLOS
, r.VELOCIDADE
, r.CODIGO_FAMILIA
, r.OBSERVACAO
, r.TIPO_PROCESSO
, r.PECAS_1_HORA
, r.PECAS_8_HORAS
, r.CUSTO_MINUTO
, r.PERC_EFICIENCIA
, r.TEMPERATURA
, r.TEMPO_LOTE_PRODUCAO
, r.PECAS_LOTE_PRODUCAO
, r.TIME_CELULA
, r.CODIGO_APARELHO
, r.PERC_EFIC_ROT
, r.NUMERO_OPERADORAS
, r.CONSIDERA_EFIC
, r.SEQ_OPERACAO_AGRUPADORA
, r.CODIGO_PARTE_PECA
, r.SEQ_JUNCAO_PARTE_PECA
, r.SITUACAO
, r.PERC_PERDAS
, r.PERC_CUSTOS
FROM MQOP_050 r
WHERE r.GRUPO_ESTRUTURA > '99999'
  AND r.NUMERO_ROTEIRO = 1
  AND r.CODIGO_OPERACAO = 33
;

DELETE FROM MQOP_050 r
WHERE r.GRUPO_ESTRUTURA > '99999'
  AND r.NUMERO_ROTEIRO = 1
  AND r.CODIGO_OPERACAO = 57
;
