SELECT
  c.INSC_EST_CLIENTE
, c.*
FROM PEDI_010 c
WHERE c.INSC_EST_CLIENTE IS NULL


UPDATE PEDI_010 c
SET
  c.INSC_EST_CLIENTE = 'ISENTO'
WHERE c.INSC_EST_CLIENTE IS NULL

SELECT
  c.TELEFONE_CLIENTE
, c.*
FROM PEDI_010 c
WHERE c.TELEFONE_CLIENTE IS NULL

UPDATE PEDI_010 c
SET
  c.TELEFONE_CLIENTE = 99999999
WHERE c.TELEFONE_CLIENTE IS NULL
