SELECT
  e.*
FROM ESTQ_300 e
--WHERE e.NIVEL_ESTRUTURA = 9
ORDER BY
  e.GRUPO_ESTRUTURA
, e.SUBGRUPO_ESTRUTURA
, e.ITEM_ESTRUTURA
, e.SEQUENCIA_INSERCAO
;

insert into estq_300 (
  CODIGO_DEPOSITO
, CODIGO_TRANSACAO
, NIVEL_ESTRUTURA
, GRUPO_ESTRUTURA
, SUBGRUPO_ESTRUTURA
, ITEM_ESTRUTURA
, DATA_MOVIMENTO
, SEQUENCIA_FICHA
, SEQUENCIA_INSERCAO
, NUMERO_LOTE
, NUMERO_DOCUMENTO
, SERIE_DOCUMENTO
, SEQUENCIA_DOCUMENTO
, ENTRADA_SAIDA
, QUANTIDADE
, VALOR_MOVIMENTO_UNITARIO
)
VALUES
(
  231 -- deposito MP
, 105 -- entrada via balanco
, 9 -- nivel
, ( SELECT
      ptc.GRUPO_ESTRUTURA
    FROM BASI_010 ptc
    WHERE ptc.CODIGO_VELHO = 'AL03004' || '.' || 'UN' || '.' || 'UN'
  )
, ( SELECT
      ptc.SUBGRU_ESTRUTURA
    FROM BASI_010 ptc
    WHERE ptc.CODIGO_VELHO = 'AL03004' || '.' || 'UN' || '.' || 'UN'
  )
, ( SELECT
      ptc.ITEM_ESTRUTURA
    FROM BASI_010 ptc
    WHERE ptc.CODIGO_VELHO = 'AL03004' || '.' || 'UN' || '.' || 'UN'
  )
, CURRENT_TIMESTAMP -- DATA_MOVIMENTO
, 0 -- SEQUENCIA_FICHA
, 1 -- SEQUENCIA_INSERCAO
, 0 -- NUMERO_LOTE
, 10 -- NUMERO_DOCUMENTO
, NULL -- SERIE_DOCUMENTO
, 0 -- SEQUENCIA_DOCUMENTO
, 'E' -- ENTRADA_SAIDA
, 5560 -- QUANTIDADE
, 1 -- VALOR_MOVIMENTO_UNITARIO
)
;

INSERT INTO ESTQ_300
(CODIGO_DEPOSITO, NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRUPO_ESTRUTURA, ITEM_ESTRUTURA, DATA_MOVIMENTO, SEQUENCIA_FICHA, SEQUENCIA_INSERCAO, NUMERO_LOTE, NUMERO_DOCUMENTO, SERIE_DOCUMENTO, CNPJ_9, CNPJ_4, CNPJ_2, SEQUENCIA_DOCUMENTO, CODIGO_TRANSACAO, ENTRADA_SAIDA, CENTRO_CUSTO, QUANTIDADE, SALDO_FISICO, VALOR_MOVIMENTO_UNITARIO, VALOR_CONTABIL_UNITARIO, PRECO_MEDIO_UNITARIO, SALDO_FINANCEIRO, GRUPO_MAQUINA, SUBGRU_MAQUINA, NUMERO_MAQUINA, ORDEM_SERVICO, CONTABILIZADO, USUARIO_SYSTEXTIL, PROCESSO_SYSTEXTIL, DATA_INSERCAO, USUARIO_REDE, MAQUINA_REDE, APLICATIVO, TABELA_ORIGEM, FLAG_ELIMINA, VALOR_MOVIMENTO_UNITARIO_PROJ, VALOR_CONTABIL_UNITARIO_PROJ, PRECO_MEDIO_UNITARIO_PROJ, SALDO_FINANCEIRO_PROJ, VALOR_MOVTO_UNIT_ESTIMADO, PRECO_MEDIO_UNIT_ESTIMADO, SALDO_FINANCEIRO_ESTIMADO, VALOR_TOTAL, PROJETO, SUBPROJETO, SERVICO, QUANTIDADE_QUILO, SALDO_FISICO_QUILO, ESTAGIO_OP, NUMERO_NF, NUMERO_OP, NUMERO_OS, TIPO_ORDEM, TIPO_SPED_TRANSACAO)
SELECT
CODIGO_DEPOSITO, NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRUPO_ESTRUTURA, ITEM_ESTRUTURA, DATA_MOVIMENTO, SEQUENCIA_FICHA, SEQUENCIA_INSERCAO, NUMERO_LOTE, NUMERO_DOCUMENTO, SERIE_DOCUMENTO, CNPJ_9, CNPJ_4, CNPJ_2, SEQUENCIA_DOCUMENTO, 3, 'S', CENTRO_CUSTO, QUANTIDADE, SALDO_FISICO, VALOR_MOVIMENTO_UNITARIO, VALOR_CONTABIL_UNITARIO, PRECO_MEDIO_UNITARIO, SALDO_FINANCEIRO, GRUPO_MAQUINA, SUBGRU_MAQUINA, NUMERO_MAQUINA, ORDEM_SERVICO, CONTABILIZADO, USUARIO_SYSTEXTIL, PROCESSO_SYSTEXTIL, DATA_INSERCAO, USUARIO_REDE, MAQUINA_REDE, APLICATIVO, TABELA_ORIGEM, FLAG_ELIMINA, VALOR_MOVIMENTO_UNITARIO_PROJ, VALOR_CONTABIL_UNITARIO_PROJ, PRECO_MEDIO_UNITARIO_PROJ, SALDO_FINANCEIRO_PROJ, VALOR_MOVTO_UNIT_ESTIMADO, PRECO_MEDIO_UNIT_ESTIMADO, SALDO_FINANCEIRO_ESTIMADO, VALOR_TOTAL, PROJETO, SUBPROJETO, SERVICO, QUANTIDADE_QUILO, SALDO_FISICO_QUILO, ESTAGIO_OP, NUMERO_NF, NUMERO_OP, NUMERO_OS, TIPO_ORDEM, TIPO_SPED_TRANSACAO
FROM estq_300
WHERE NIVEL_ESTRUTURA = 9
