-- cad forne
-- supr_f010
-- codigo_contabil
-- supr_010
--
-- cad repr
-- pedi_f020
--
SELECT
  f.CODIGO_CONTABIL
, f.FORNECEDOR9
, r.CGC_9
, f.nome_fornecedor
, r.*
, f.*
FROM PEDI_020 r
LEFT JOIN supr_010 f
  ON f.FORNECEDOR9 = r.CGC_9
 AND f.FORNECEDOR4 = r.CGC_4
 AND f.FORNECEDOR2 = r.CGC_2
WHERE r.COD_REP_CLIENTE <> 0
  AND f.FORNECEDOR9 <> 0
;

UPDATE supr_010 fu
SET
  fu.CODIGO_CONTABIL = 486
WHERE EXISTS (
SELECT
  f.FORNECEDOR9
FROM PEDI_020 r
LEFT JOIN supr_010 f
  ON f.FORNECEDOR9 = r.CGC_9
 AND f.FORNECEDOR4 = r.CGC_4
 AND f.FORNECEDOR2 = r.CGC_2
WHERE r.COD_REP_CLIENTE <> 0
  AND f.FORNECEDOR9 <> 0
  AND f.FORNECEDOR9 = fu.FORNECEDOR9
  AND f.FORNECEDOR4 = fu.FORNECEDOR4
  AND f.FORNECEDOR2 = fu.FORNECEDOR2
)
;
