SELECT
  r.NIVEL_ESTRUTURA
, r.REFERENCIA
, r.DESCR_REFERENCIA
, r.CONTA_ESTOQUE
, ce.DESCR_CT_ESTOQUE
, r.CLASSIFIC_FISCAL
, ncm.DESCR_CLASS_FISC
, r.CODIGO_CONTABIL
, ccont.DESCRICAO
FROM basi_030 r
JOIN basi_150 ce
  ON ce.CONTA_ESTOQUE = r.CONTA_ESTOQUE
JOIN basi_240 ncm
  ON ncm.CLASSIFIC_FISCAL = r.CLASSIFIC_FISCAL
JOIN cont_540 ccont
  ON ccont.CODIGO_CONTABIL = r.CODIGO_CONTABIL
WHERE r.NIVEL_ESTRUTURA IN (2, 9)
ORDER BY
  r.NIVEL_ESTRUTURA
, r.REFERENCIA
;
