SELECT
  e.*
FROM BASI_050 e
WHERE e.NIVEL_ITEM = 1
  AND e.GRUPO_ITEM <= '99999'
  AND e.ALTERNATIVA_ITEM = 1
  AND e.NIVEL_COMP = 1
  AND e.GRUPO_COMP > '99999'
  AND e.ESTAGIO <> 57
;

UPDATE BASI_050 e
SET
  e.ESTAGIO = 57
WHERE e.NIVEL_ITEM = 1
  AND e.GRUPO_ITEM <= '99999'
  AND e.ALTERNATIVA_ITEM = 1
  AND e.NIVEL_COMP = 1
  AND e.GRUPO_COMP > '99999'
  AND e.ESTAGIO <> 57
;

------------------------
------------------------
------------------------
------------------------
------------------------

SELECT
  c.*
FROM basi_050 e
JOIN BASI_040 c
  ON c.NIVEL_ITEM = e.NIVEL_ITEM
 AND c.GRUPO_ITEM = e.GRUPO_ITEM
 AND c.ALTERNATIVA_ITEM = e.ALTERNATIVA_ITEM
 AND c.SEQUENCIA = e.SEQUENCIA
WHERE e.NIVEL_COMP = 9
  AND e.GRUPO_COMP = 'DV012'
ORDER BY
  e.NIVEL_ITEM
, e.GRUPO_ITEM
;

-- na estrutura inserir DV004 0000PR onde tem DV012 com sequencia+1

INSERT INTO SYSTEXTIL.BASI_050
(NIVEL_ITEM, GRUPO_ITEM, SUB_ITEM, ITEM_ITEM, ALTERNATIVA_ITEM,
  SEQUENCIA, NIVEL_COMP,
  GRUPO_COMP, SUB_COMP,
  ITEM_COMP, ALTERNATIVA_COMP, CONSUMO, ESTAGIO, TIPO_CALCULO, LETRA_GRAFICO, QTDE_CAMADAS, PERCENT_PERDAS, NUMERO_GRAFICO, QTDE_INICIAL, QTDE_FINAL, TENSAO, LFA, LOTE, FORNECEDOR, CONS_UN_REC, SEQ_PRINCIPAL, GRUPO_SIMILARES, CENTRO_CUSTO, CONS_UNID_MED_GENERICA, PERC_CONS_CALC, CALCULA_COMPOSICAO, RELACAO_BANHO, QTDE_PECAS_ESTAMPADAS, TIPO_TELA, AREA_COBERTURA, TIPO_APLICACAO, TIPO_MEDIDA, CODIGO_PROJETO, SEQUENCIA_PROJETO, TECIDO_PRINCIPAL, VALOR_ML_L, FATOR_CONVERSOR, QTDE_CABOS, VARIACAO, AGRUP_TINGIMENTO, QTDE_PECAS)
SELECT NIVEL_ITEM, GRUPO_ITEM, SUB_ITEM, ITEM_ITEM, ALTERNATIVA_ITEM,
  SEQUENCIA+1, NIVEL_COMP,
  'DV004', SUB_COMP,
  '0000PR', ALTERNATIVA_COMP, CONSUMO, ESTAGIO, TIPO_CALCULO, LETRA_GRAFICO, QTDE_CAMADAS, PERCENT_PERDAS, NUMERO_GRAFICO, QTDE_INICIAL, QTDE_FINAL, TENSAO, LFA, LOTE, FORNECEDOR, CONS_UN_REC, SEQ_PRINCIPAL, GRUPO_SIMILARES, CENTRO_CUSTO, CONS_UNID_MED_GENERICA, PERC_CONS_CALC, CALCULA_COMPOSICAO, RELACAO_BANHO, QTDE_PECAS_ESTAMPADAS, TIPO_TELA, AREA_COBERTURA, TIPO_APLICACAO, TIPO_MEDIDA, CODIGO_PROJETO, SEQUENCIA_PROJETO, TECIDO_PRINCIPAL, VALOR_ML_L, FATOR_CONVERSOR, QTDE_CABOS, VARIACAO, AGRUP_TINGIMENTO, QTDE_PECAS
FROM SYSTEXTIL.BASI_050
WHERE NIVEL_COMP = 9
  AND GRUPO_COMP = 'DV012'
;

-- na combinação inserir DV004 0000PR onde tem DV012 0000* com sequencia+1

INSERT INTO SYSTEXTIL.BASI_040
(NIVEL_ITEM, GRUPO_ITEM, SUB_ITEM, ITEM_ITEM, ALTERNATIVA_ITEM,
  SEQUENCIA, SUB_COMP,
  ITEM_COMP, CONSUMO, CONS_UNID_MED_GENERICA, SEQUENCIA_TAMANHO, ALTERNATIVA_COMP, CODIGO_PROJETO, SEQUENCIA_PROJETO, QTDE_PECAS)
SELECT c.NIVEL_ITEM, c.GRUPO_ITEM, c.SUB_ITEM, c.ITEM_ITEM, c.ALTERNATIVA_ITEM,
  c.SEQUENCIA+1, c.SUB_COMP,
  '0000PR', c.CONSUMO, c.CONS_UNID_MED_GENERICA, c.SEQUENCIA_TAMANHO, c.ALTERNATIVA_COMP, c.CODIGO_PROJETO, c.SEQUENCIA_PROJETO, c.QTDE_PECAS
FROM basi_050 e
JOIN BASI_040 c
  ON c.NIVEL_ITEM = e.NIVEL_ITEM
 AND c.GRUPO_ITEM = e.GRUPO_ITEM
 AND c.ALTERNATIVA_ITEM = e.ALTERNATIVA_ITEM
 AND c.SEQUENCIA = e.SEQUENCIA
WHERE e.NIVEL_COMP = 9
  AND e.GRUPO_COMP = 'DV012'
;

-- na combinação apagar DV012

DELETE FROM BASI_040 cd
WHERE cd.ROWID IN (
	SELECT
	  c.ROWID
	FROM basi_050 e
	JOIN BASI_040 c
	  ON c.NIVEL_ITEM = e.NIVEL_ITEM
	 AND c.GRUPO_ITEM = e.GRUPO_ITEM
	 AND c.ALTERNATIVA_ITEM = e.ALTERNATIVA_ITEM
	 AND c.SEQUENCIA = e.SEQUENCIA
	WHERE e.NIVEL_COMP = 9
	  AND e.GRUPO_COMP = 'DV012'
)
;

-- na estrutura apagar DV012

DELETE FROM SYSTEXTIL.BASI_050
WHERE NIVEL_COMP = 9
  AND GRUPO_COMP = 'DV012'
;

-- Gi disse que poderia ficar sequencia+1 (81), por isso não fiz os passos abaixo
-- na estrutura inserir DV004 sequencia, onde tem DV004 com sequencia+1
-- na combinação inserir DV004 sequencia, onde tem DV004 com sequencia+1
-- na combinação apagar DV004 com sequencia+1
-- na estrutura apagar DV004 com sequencia+1
