SELECT
  l.CODIGO_ESTAGIO
, e.DESCRICAO DESCRICAO_ESTAGIO
, l.QTDE_PROGRAMADA
, l.QTDE_EM_PRODUCAO_PACOTE
, l.QTDE_A_PRODUZIR_PACOTE
--, l.*
--, e.*
--, r.*
FROM PCPC_040 l
JOIN MQOP_005 e
  ON e.CODIGO_ESTAGIO = l.CODIGO_ESTAGIO
--JOIN MQOP_050 r
--  ON r.NIVEL_ESTRUTURA = l.PROCONF_NIVEL99
-- AND r.GRUPO_ESTRUTURA = l.PROCONF_GRUPO
-- AND r.CODIGO_ESTAGIO = l.CODIGO_ESTAGIO
WHERE 1=1
--  AND l.ORDEM_PRODUCAO = 145
--  AND l.NUMERO_ORDEM = 165
  AND l.PERIODO_PRODUCAO = 1719
  AND l.ORDEM_CONFECCAO = 5537
ORDER BY
  l.SEQ_OPERACAO
;


SELECT
  r.*
FROM BASI_070 r
;

SELECT
  r.*
FROM MQOP_050 r
;

SELECT
  r.*
FROM MQOP_040 r
;
