SELECT
  p.REFERENCIA
, p.DESCR_REFERENCIA
, LISTAGG(t.TAMANHO_REF, ', ') WITHIN GROUP (ORDER BY tam.ORDEM_TAMANHO) tamanhos
, (
    SELECT
      LISTAGG(c.ITEM_ESTRUTURA, ', ') WITHIN GROUP (ORDER BY c.ITEM_ESTRUTURA)
    FROM
    ( SELECT DISTINCT
        i.NIVEL_ESTRUTURA
      , i.GRUPO_ESTRUTURA
      , i.ITEM_ESTRUTURA
      FROM basi_010 i
      WHERE i.NIVEL_ESTRUTURA = 1
        AND i.GRUPO_ESTRUTURA = '00103'
    )  c
    GROUP BY
      c.NIVEL_ESTRUTURA
    , c.GRUPO_ESTRUTURA
  ) cores
FROM BASI_030 p
JOIN basi_020 t
  ON t.BASI030_NIVEL030 = p.NIVEL_ESTRUTURA
 AND t.BASI030_REFERENC = p.REFERENCIA
JOIN BASI_220 tam
  ON tam.TAMANHO_REF = t.TAMANHO_REF
WHERE p.NIVEL_ESTRUTURA = 1
  AND p.REFERENCIA = '00103'
GROUP BY
  p.REFERENCIA
, p.DESCR_REFERENCIA
ORDER BY
  p.REFERENCIA

--

  SELECT DISTINCT
        LISTAGG(i.ITEM_ESTRUTURA, ' ') WITHIN GROUP (ORDER BY i.ITEM_ESTRUTURA)
      FROM basi_010 i
    WHERE i.NIVEL_ESTRUTURA = 1
      AND i.GRUPO_ESTRUTURA = '00103'
    GROUP BY
      i.GRUPO_ESTRUTURA

--

SELECT
  LISTAGG(c.ITEM_ESTRUTURA, ', ') WITHIN GROUP (ORDER BY c.ITEM_ESTRUTURA)
, (
    SELECT DISTINCT
	  t.TAMANHO_REF
	FROM basi_020 t
	WHERE t.BASI030_NIVEL030 = c.NIVEL_ESTRUTURA
	  AND t.BASI030_REFERENC = c.GRUPO_ESTRUTURA
	  AND t.TAMANHO_REF = 'P'
  ) tam
FROM
( SELECT DISTINCT
    i.NIVEL_ESTRUTURA
  , i.GRUPO_ESTRUTURA
  , i.ITEM_ESTRUTURA
  FROM basi_010 i
  WHERE i.NIVEL_ESTRUTURA = 1
    AND i.GRUPO_ESTRUTURA = '00103'
)  c
GROUP BY
  c.NIVEL_ESTRUTURA
, c.GRUPO_ESTRUTURA

--

SELECT
  LISTAGG(c.ITEM_ESTRUTURA, ', ') WITHIN GROUP (ORDER BY c.ITEM_ESTRUTURA)
, (
  SELECT
    LISTAGG(tt.TAMANHO_REF, ', ') WITHIN GROUP (ORDER BY tt.TAMANHO_REF)
  FROM (
    SELECT DISTINCT
	  t.TAMANHO_REF
	FROM basi_020 t
	WHERE t.BASI030_NIVEL030 = i.NIVEL_ESTRUTURA
	  AND t.BASI030_REFERENC = i.GRUPO_ESTRUTURA
  ) tt
  GROUP BY
    tt.NIVEL_ESTRUTURA
  , tt.GRUPO_ESTRUTURA
  ) tam
FROM
( SELECT DISTINCT
    i.NIVEL_ESTRUTURA
  , i.GRUPO_ESTRUTURA
  , i.ITEM_ESTRUTURA
  FROM basi_010 i
  WHERE i.NIVEL_ESTRUTURA = 1
    AND i.GRUPO_ESTRUTURA < '00200'
)  c
GROUP BY
  c.NIVEL_ESTRUTURA
, c.GRUPO_ESTRUTURA

--

SELECT
  p.REFERENCIA
, p.DESCR_REFERENCIA
, LISTAGG(t.TAMANHO_REF, ', ') WITHIN GROUP (ORDER BY tam.ORDEM_TAMANHO) tamanhos
, cc.cores
FROM BASI_030 p
JOIN basi_020 t
  ON t.BASI030_NIVEL030 = p.NIVEL_ESTRUTURA
 AND t.BASI030_REFERENC = p.REFERENCIA
JOIN BASI_220 tam
  ON tam.TAMANHO_REF = t.TAMANHO_REF
JOIN
    ( SELECT
        c.NIVEL_ESTRUTURA
      , c.GRUPO_ESTRUTURA
      , LISTAGG(c.ITEM_ESTRUTURA, ', ') WITHIN GROUP (ORDER BY c.ITEM_ESTRUTURA) cores
    FROM
    ( SELECT DISTINCT
        i.NIVEL_ESTRUTURA
      , i.GRUPO_ESTRUTURA
      , i.ITEM_ESTRUTURA
      FROM basi_010 i
    )  c
    GROUP BY
        c.NIVEL_ESTRUTURA
      , c.GRUPO_ESTRUTURA
    ) cc
  ON cc.NIVEL_ESTRUTURA = p.NIVEL_ESTRUTURA
 AND cc.GRUPO_ESTRUTURA = p.REFERENCIA
WHERE p.NIVEL_ESTRUTURA = 1
  AND p.REFERENCIA < '00200'
GROUP BY
  p.REFERENCIA
, p.DESCR_REFERENCIA
, cc.cores
ORDER BY
  p.REFERENCIA

--

SELECT
  p.REFERENCIA
, p.DESCR_REFERENCIA
, eee.alter_estr
FROM BASI_030 p
JOIN
    ( SELECT
        ee.NIVEL_ITEM
      , ee.GRUPO_ITEM
      , LISTAGG(ee.ALTERNATIVA_ITEM, ', ') WITHIN GROUP (ORDER BY ee.ALTERNATIVA_ITEM) alter_estr
    FROM
    ( SELECT DISTINCT
        e.NIVEL_ITEM
      , e.GRUPO_ITEM
      , e.ALTERNATIVA_ITEM
      FROM basi_050 e
    )  ee
    GROUP BY
      ee.NIVEL_ITEM
    , ee.GRUPO_ITEM
    ) eee
  ON eee.NIVEL_ITEM = p.NIVEL_ESTRUTURA
 AND eee.GRUPO_ITEM = p.REFERENCIA
WHERE p.NIVEL_ESTRUTURA = 1
  AND p.REFERENCIA = '00103'
ORDER BY
  p.REFERENCIA

--

SELECT
  p.REFERENCIA
, p.DESCR_REFERENCIA
, ttt.tamanhos
FROM BASI_030 p
JOIN
    ( SELECT
	    tt.BASI030_NIVEL030
	  , tt.BASI030_REFERENC
      , LISTAGG(tt.TAMANHO_REF, ', ') WITHIN GROUP (ORDER BY tt.ORDEM_TAMANHO) tamanhos
    FROM
    ( SELECT DISTINCT
	    t.BASI030_NIVEL030
	  , t.BASI030_REFERENC
      , t.TAMANHO_REF
      , tam.ORDEM_TAMANHO
      FROM basi_020 t
      JOIN BASI_220 tam
        ON tam.TAMANHO_REF = t.TAMANHO_REF
    )  tt
    GROUP BY
      tt.BASI030_NIVEL030
    , tt.BASI030_REFERENC
    ) ttt
  ON ttt.BASI030_NIVEL030 = p.NIVEL_ESTRUTURA
 AND ttt.BASI030_REFERENC = p.REFERENCIA
WHERE p.NIVEL_ESTRUTURA = 1
  AND p.REFERENCIA = '00103'
ORDER BY
  p.REFERENCIA

--

SELECT
  p.REFERENCIA
, p.DESCR_REFERENCIA
, rrr.roteiros
FROM BASI_030 p
JOIN
    ( SELECT
        rr.NIVEL_ESTRUTURA
      , rr.GRUPO_ESTRUTURA
      , LISTAGG(rr.NUMERO_ROTEIRO, ', ') WITHIN GROUP (ORDER BY rr.NUMERO_ROTEIRO) roteiros
    FROM
    ( SELECT DISTINCT
        r.NIVEL_ESTRUTURA
      , r.GRUPO_ESTRUTURA
      , r.NUMERO_ROTEIRO
      FROM mqop_050 r
    )  rr
    GROUP BY
      rr.NIVEL_ESTRUTURA
    , rr.GRUPO_ESTRUTURA
    ) rrr
  ON rrr.NIVEL_ESTRUTURA = p.NIVEL_ESTRUTURA
 AND rrr.GRUPO_ESTRUTURA = p.REFERENCIA
WHERE p.NIVEL_ESTRUTURA = 1
  AND p.REFERENCIA = '00103'
ORDER BY
  p.REFERENCIA

  --

  SELECT
    p.REFERENCIA
  , p.DESCR_REFERENCIA
  , ttt.tamanhos
  , cc.cores
  , eee.estruturas
  , rrr.roteiros
  FROM BASI_030 p
  JOIN
      ( SELECT
  	    tt.BASI030_NIVEL030
  	  , tt.BASI030_REFERENC
        , LISTAGG(tt.TAMANHO_REF, ', ') WITHIN GROUP (ORDER BY tt.ORDEM_TAMANHO) tamanhos
      FROM
      ( SELECT DISTINCT
  	    t.BASI030_NIVEL030
  	  , t.BASI030_REFERENC
        , t.TAMANHO_REF
        , tam.ORDEM_TAMANHO
        FROM basi_020 t
        JOIN BASI_220 tam
          ON tam.TAMANHO_REF = t.TAMANHO_REF
      )  tt
      GROUP BY
        tt.BASI030_NIVEL030
      , tt.BASI030_REFERENC
      ) ttt
    ON ttt.BASI030_NIVEL030 = p.NIVEL_ESTRUTURA
   AND ttt.BASI030_REFERENC = p.REFERENCIA
  JOIN
      ( SELECT
          c.NIVEL_ESTRUTURA
        , c.GRUPO_ESTRUTURA
        , LISTAGG(c.ITEM_ESTRUTURA, ', ') WITHIN GROUP (ORDER BY c.ITEM_ESTRUTURA) cores
      FROM
      ( SELECT DISTINCT
          i.NIVEL_ESTRUTURA
        , i.GRUPO_ESTRUTURA
        , i.ITEM_ESTRUTURA
        FROM basi_010 i
      )  c
      GROUP BY
          c.NIVEL_ESTRUTURA
        , c.GRUPO_ESTRUTURA
      ) cc
    ON cc.NIVEL_ESTRUTURA = p.NIVEL_ESTRUTURA
   AND cc.GRUPO_ESTRUTURA = p.REFERENCIA
  JOIN
      ( SELECT
          ee.NIVEL_ITEM
        , ee.GRUPO_ITEM
        , LISTAGG(ee.ALTERNATIVA_ITEM, ', ') WITHIN GROUP (ORDER BY ee.ALTERNATIVA_ITEM) estruturas
      FROM
      ( SELECT DISTINCT
          e.NIVEL_ITEM
        , e.GRUPO_ITEM
        , e.ALTERNATIVA_ITEM
        FROM basi_050 e
      )  ee
      GROUP BY
        ee.NIVEL_ITEM
      , ee.GRUPO_ITEM
      ) eee
    ON eee.NIVEL_ITEM = p.NIVEL_ESTRUTURA
   AND eee.GRUPO_ITEM = p.REFERENCIA
  JOIN
      ( SELECT
          rr.NIVEL_ESTRUTURA
        , rr.GRUPO_ESTRUTURA
        , LISTAGG(rr.NUMERO_ROTEIRO, ', ') WITHIN GROUP (ORDER BY rr.NUMERO_ROTEIRO) roteiros
      FROM
      ( SELECT DISTINCT
          r.NIVEL_ESTRUTURA
        , r.GRUPO_ESTRUTURA
        , r.NUMERO_ROTEIRO
        FROM mqop_050 r
      )  rr
      GROUP BY
        rr.NIVEL_ESTRUTURA
      , rr.GRUPO_ESTRUTURA
      ) rrr
    ON rrr.NIVEL_ESTRUTURA = p.NIVEL_ESTRUTURA
   AND rrr.GRUPO_ESTRUTURA = p.REFERENCIA
  WHERE p.NIVEL_ESTRUTURA = 1
    AND p.REFERENCIA < '00200'
  ORDER BY
    p.REFERENCIA

-- marcando produtos com OP

UPDATE BASI_030 r
SET
  r.OBSERVACAO3 = 'OP'
WHERE r.NIVEL_ESTRUTURA = 1
  AND EXISTS
( SELECT
    o.PERIODO_PRODUCAO
  FROM PCPC_040 o
  WHERE o.PROCONF_NIVEL99 = r.NIVEL_ESTRUTURA
    AND o.PROCONF_GRUPO = r.REFERENCIA
)
