SELECT
  l.PROCONF_GRUPO REF
, l.PROCONF_SUBGRUPO TAM
, l.PROCONF_ITEM COR
, l.CODIGO_ESTAGIO || ' - ' || e.DESCRICAO EST
, l.PERIODO_PRODUCAO PERIODO
, l.ORDEM_CONFECCAO OC
, l.SEQ_OPERACAO SEQ
, l.QTDE_EM_PRODUCAO_PACOTE QTD
, l.*
FROM PCPC_040 l
JOIN MQOP_005 e
  ON e.CODIGO_ESTAGIO = l.CODIGO_ESTAGIO
WHERE l.ORDEM_PRODUCAO = 439
--  AND l.QTDE_EM_PRODUCAO_PACOTE <> 0
ORDER BY
  l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
, l.ORDEM_CONFECCAO
, l.SEQ_OPERACAO

--

SELECT
  l.ORDEM_PRODUCAO OP
, l.NOME_PROGRAMA_CRIACAO || ' - ' || p.DESCRICAO PRG
, l.SITUACAO_ORDEM SITU
, TO_CHAR(o.DATA_HORA, 'DD/MM/YYYY HH24:MI') DT
FROM PCPC_040 l
JOIN HDOC_036 p
  ON p.CODIGO_PROGRAMA = l.NOME_PROGRAMA_CRIACAO
 AND p.LOCALE = 'pt_BR'
LEFT JOIN PCPC_020 o
  ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
WHERE l.PERIODO_PRODUCAO = 1720
  AND l.ORDEM_CONFECCAO = 511
  AND rownum = 1

--

SELECT
  l.PERIODO_PRODUCAO
, l.ORDEM_CONFECCAO
, sum( l.QTDE_EM_PRODUCAO_PACOTE ) em_prod
FROM PCPC_040 l
GROUP BY
  l.PERIODO_PRODUCAO
, l.ORDEM_CONFECCAO
ORDER BY
  3

--

SELECT
  l.CODIGO_ESTAGIO
, e.DESCRICAO DESCRICAO_ESTAGIO
, l.QTDE_EM_PRODUCAO_PACOTE
, l.ORDEM_PRODUCAO
FROM PCPC_040 l
JOIN MQOP_005 e
  ON e.CODIGO_ESTAGIO = l.CODIGO_ESTAGIO
WHERE 1=1
  AND l.PERIODO_PRODUCAO = 1719
  AND l.ORDEM_CONFECCAO = 9993
--                  AND l.QTDE_EM_PRODUCAO_PACOTE > 0

--

SELECT
  l.PROCONF_GRUPO REF
, l.PROCONF_SUBGRUPO TAM
, l.PROCONF_ITEM COR
, CASE WHEN l.QTDE_EM_PRODUCAO_PACOTE = 0 THEN 'FINALIZADO'
  ELSE l.CODIGO_ESTAGIO || ' - ' || e.DESCRICAO
  END EST
, l.PERIODO_PRODUCAO PERIODO
, l.ORDEM_CONFECCAO OC
, l.SEQ_OPERACAO SEQ
, l.QTDE_EM_PRODUCAO_PACOTE EM_PROD
, l.QTDE_A_PRODUZIR_PACOTE A_PROD
, l.QTDE_PROGRAMADA QTD
--, l.*
FROM PCPC_040 l
JOIN MQOP_005 e
  ON e.CODIGO_ESTAGIO = l.CODIGO_ESTAGIO
WHERE 1=1
  AND l.ORDEM_PRODUCAO = 796
--  AND l.QTDE_EM_PRODUCAO_PACOTE <> 0
--  AND l.PERIODO_PRODUCAO = 1719
--  AND l.ORDEM_CONFECCAO = 9980
  AND l.SEQ_OPERACAO =
  (
    SELECT
      max(lms.SEQ_OPERACAO)
	FROM PCPC_040 lms
	WHERE lms.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
 	  AND lms.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
	  AND lms.QTDE_EM_PRODUCAO_PACOTE = lms.QTDE_A_PRODUZIR_PACOTE
  )
ORDER BY
  l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
, l.ORDEM_CONFECCAO
, l.SEQ_OPERACAO
;

-- OP - por OS

SELECT
  l.ORDEM_PRODUCAO OP
, oss.NUMERO_ORDEM OS
, COUNT( l.ORDEM_CONFECCAO ) LOTES
, SUM( l.QTDE_PROGRAMADA ) QTD
FROM PCPC_040 l
JOIN (
  SELECT DISTINCT
    os.ORDEM_PRODUCAO
  , os.NUMERO_ORDEM
  FROM PCPC_040 os
  ) oss
  ON oss.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
 AND oss.NUMERO_ORDEM = l.NUMERO_ORDEM
WHERE 1=1
  AND l.ORDEM_PRODUCAO = 23
GROUP BY
  l.ORDEM_PRODUCAO
, oss.NUMERO_ORDEM
ORDER BY
  l.ORDEM_PRODUCAO
, oss.NUMERO_ORDEM
;

-- OP - por OS e referencia

SELECT
  l.ORDEM_PRODUCAO OP
, oss.NUMERO_ORDEM OS
, l.PROCONF_GRUPO REF
, l.PROCONF_SUBGRUPO TAM
, l.PROCONF_ITEM COR
, COUNT( l.ORDEM_CONFECCAO ) LOTES
, SUM( l.QTDE_PROGRAMADA ) QTD
FROM PCPC_040 l
JOIN (
  SELECT DISTINCT
    os.ORDEM_PRODUCAO
  , os.NUMERO_ORDEM
  FROM PCPC_040 os
  ) oss
  ON oss.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
 AND oss.NUMERO_ORDEM = l.NUMERO_ORDEM
WHERE 1=1
  AND l.ORDEM_PRODUCAO = 23
GROUP BY
  l.ORDEM_PRODUCAO
, oss.NUMERO_ORDEM
, l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
ORDER BY
  l.ORDEM_PRODUCAO
, oss.NUMERO_ORDEM
, l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
;

-- OP - por OS e lote

SELECT
  l.ORDEM_PRODUCAO OP
, oss.NUMERO_ORDEM OS
, l.PROCONF_GRUPO REF
, l.PROCONF_SUBGRUPO TAM
, l.PROCONF_ITEM COR
, COUNT( l.ORDEM_CONFECCAO ) LOTES
, SUM( l.QTDE_PROGRAMADA ) QTD
FROM PCPC_040 l
JOIN (
  SELECT DISTINCT
    os.ORDEM_PRODUCAO
  , os.NUMERO_ORDEM
  FROM PCPC_040 os
  ) oss
  ON oss.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
 AND oss.NUMERO_ORDEM = l.NUMERO_ORDEM
WHERE 1=1
  AND l.ORDEM_PRODUCAO = 23
GROUP BY
  l.ORDEM_PRODUCAO
, oss.NUMERO_ORDEM
, l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
ORDER BY
  l.ORDEM_PRODUCAO
, oss.NUMERO_ORDEM
, l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
;

-- PO - por lote completão

SELECT
  l.ORDEM_PRODUCAO OP
, oss.NUMERO_ORDEM OS
, l.PROCONF_GRUPO REF
, l.PROCONF_SUBGRUPO TAM
, l.PROCONF_ITEM COR
, CASE WHEN l.QTDE_EM_PRODUCAO_PACOTE = 0 THEN 'FINALIZADO'
  ELSE l.CODIGO_ESTAGIO || ' - ' || e.DESCRICAO
  END EST
, l.PERIODO_PRODUCAO PERIODO
, l.ORDEM_CONFECCAO OC
, l.QTDE_PROGRAMADA QTD
FROM PCPC_040 l
JOIN MQOP_005 e
  ON e.CODIGO_ESTAGIO = l.CODIGO_ESTAGIO
JOIN (
  SELECT DISTINCT
    os.ORDEM_PRODUCAO
  , os.NUMERO_ORDEM
  FROM PCPC_040 os
  ) oss
  ON oss.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
 AND oss.NUMERO_ORDEM = l.NUMERO_ORDEM
WHERE 1=1
  AND l.ORDEM_PRODUCAO = 24
ORDER BY
  l.ORDEM_PRODUCAO
, oss.NUMERO_ORDEM
, l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
, 6
, l.PERIODO_PRODUCAO
, l.ORDEM_CONFECCAO
, l.QTDE_PROGRAMADA
;
