SELECT
  c.C_CGC CNPJ
, c.C_RSOC CLIENTE
, d.D_DUPNUM DUPLICATA
, d.D_STAT STAT
, d.D_PEDNUM PEDIDO
, d.D_DFAT EMISSAO
, d.D_DVENCORI VENC_ORI
, d.D_DVENC VENCIMENTO
, cast('NOW' AS DATE) now
, CASE WHEN mod(ord(d.D_AUX), 2) = 1
  THEN 'P'
  ELSE ' '
  END PRORROGADO
, d.D_VALOR VALOR_ORI
, CASE WHEN d.D_VPAGO = 0 AND d.D_DVENC < 'NOW'
THEN d.D_VALOR
  ELSE d.D_VALOR*(1-(d.D_DESC/100))
  END VALOR
, d.D_VALOR -
CASE WHEN d.D_VPAGO = 0 AND d.D_DVENC < 'NOW'
THEN d.D_VALOR
  ELSE d.D_VALOR*(1-(d.D_DESC/100))
  END VALOR_DIF
, d.D_QTD QUANT
, d.D_QTDFAT QUANT_FAT
, d.D_DPAGO DATA_PAGO
, d.D_VPAGO VALOR_PAGO
, d.D_JUROS JUROS
, (cast('NOW' AS DATE) - d.D_DVENC) DIAS_ATRASO
, (d.D_JUROS * ((cast('NOW' AS DATE) - d.D_DVENC) / 3000.00000)) JUROS_APLICAR
, 6.00000 * 10 / 3000 JUROS_APLICAR_N
, CASE WHEN d.D_DPAGO <> '1899.12.30' THEN
CASE WHEN d.D_DVENC >= d.D_DPAGO THEN
  0 -- ''
--WHEN d.D_VPAGO <> 0 THEN
ELSE
  d.D_VPAGO - d.D_VALOR
--ELSE
--  d.D_VALOR * (d.D_JUROS * ((d.D_DPAGO -  d.D_DVENC) / 3000))
END
ELSE
CASE WHEN d.D_DVENC >= 'NOW' THEN
  0 -- ''
WHEN d.D_VPAGO <> 0 THEN
  d.D_VPAGO - d.D_VALOR
ELSE
  d.D_VALOR * (d.D_JUROS * ((cast('NOW' AS DATE) - d.D_DVENC) / 3000.0000))
END
END VAL_JUROS
, CASE WHEN d.D_DPAGO <> '1899.12.30' THEN
CASE WHEN d.D_DVENC >= d.D_DPAGO THEN
  0
ELSE
  d.D_DPAGO - d.D_DVENC
END
ELSE
CASE WHEN d.D_DVENC >= 'NOW' THEN
  0
ELSE
      cast('NOW' AS DATE) - d.D_DVENC
END
  END ATRASO
, d.D_OP OP
, d.D_BANCO BANCO
, d.D_DESCONTO DESCONTO
, d.D_OBS OBSERVACAO
, d.*
FROM DIS_DUP d
LEFT JOIN DIS_CLI c
  ON c.C_CGC = d.D_CGC
WHERE 1=1
  --AND d.D_CGC LIKE '07196323%'
  AND D.D_STAT >= '0' -- nao canceladas
  AND d.D_CODFIS IN ('5101', '6101', '6107', '6109', '5124', '6124', '5125', '6125') -- cpof de venda
  AND d.D_DUPNUM STARTING WITH 'T'
  AND d.D_DUPNUM > 'T55000'
  AND d.D_DPAGO = '1899.12.30'
  AND d.D_DVENC < 'NOW'
  AND d.D_VPAGO = 0
ORDER BY
  d.D_DUPNUM DESC
;
