SELECT
  CASE WHEN l.QTDE_EM_PRODUCAO_PACOTE = 0 THEN 0
  ELSE l.CODIGO_ESTAGIO
  END CODIGO_ESTAGIO
, CASE WHEN l.QTDE_EM_PRODUCAO_PACOTE = 0 THEN 'FINALIZADO'
  ELSE e.DESCRICAO
  END DESCRICAO_ESTAGIO
FROM PCPC_040 l
JOIN MQOP_005 e
  ON e.CODIGO_ESTAGIO = l.CODIGO_ESTAGIO
WHERE l.PERIODO_PRODUCAO = 1725
  AND l.ORDEM_CONFECCAO = 5587
  AND l.SEQ_OPERACAO =
  (
    SELECT
      max(lms.SEQ_OPERACAO)
    FROM PCPC_040 lms
    WHERE lms.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
      AND lms.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
      AND lms.QTDE_EM_PRODUCAO_PACOTE =
          lms.QTDE_A_PRODUZIR_PACOTE
  )

--

SELECT
  max(lms.SEQ_OPERACAO)
FROM PCPC_040 lms
WHERE lms.ORDEM_PRODUCAO = 843
  AND lms.ORDEM_CONFECCAO = 05587
  AND lms.QTDE_EM_PRODUCAO_PACOTE =
      lms.QTDE_A_PRODUZIR_PACOTE
;

--

SELECT
  CASE WHEN l.QTDE_EM_PRODUCAO_PACOTE = 0 THEN 0
  ELSE l.CODIGO_ESTAGIO
  END CODIGO_ESTAGIO
, CASE WHEN l.QTDE_EM_PRODUCAO_PACOTE = 0 THEN 'FINALIZADO'
  ELSE e.DESCRICAO
  END DESCRICAO_ESTAGIO
, e.*
, l.*
FROM PCPC_040 l
JOIN MQOP_005 e
  ON e.CODIGO_ESTAGIO = l.CODIGO_ESTAGIO
WHERE l.PERIODO_PRODUCAO = 1725
  AND l.ORDEM_CONFECCAO = 5587
  AND l.SEQ_OPERACAO = 40

--

SELECT
  l.PERIODO_PRODUCAO
, l.ORDEM_CONFECCAO
, l.CODIGO_ESTAGIO
, l.QTDE_EM_PRODUCAO_PACOTE
FROM PCPC_040 l
WHERE 1=1
  --AND rownum = 1
  AND l.PERIODO_PRODUCAO = 1725
  AND l.ORDEM_CONFECCAO = 5589
  AND l.CODIGO_ESTAGIO IN (
    SELECT
      es.CODIGO_ESTAGIO
    FROM MQOP_005 e
    JOIN MQOP_005 es
      ON (e.ESTAGIO_FINAL <> 0 AND es.ESTAGIO_FINAL = e.ESTAGIO_FINAL)
         OR (e.ESTAGIO_FINAL = 0 AND es.CODIGO_ESTAGIO = e.CODIGO_ESTAGIO)
    WHERE e.CODIGO_ESTAGIO =
	  (
	    SELECT
	      max(lms.CODIGO_ESTAGIO)
	    FROM PCPC_040 lms
	    WHERE lms.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
	      AND lms.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
	      AND lms.QTDE_EM_PRODUCAO_PACOTE =
	          lms.QTDE_A_PRODUZIR_PACOTE
	  )
    )
ORDER BY
  l.QTDE_EM_PRODUCAO_PACOTE DESC

--
