SELECT
  l.CODIGO_ESTAGIO || ' - ' || e.DESCRICAO EST
, l.QTDE_PROGRAMADA Q_P
, l.QTDE_EM_PRODUCAO_PACOTE Q_EP
, l.QTDE_A_PRODUZIR_PACOTE Q_AP
, l.CODIGO_FAMILIA FAMI
, l.NUMERO_ORDEM OS
, coalesce(d.USUARIO_SYSTEXTIL, ' ') USU
, TO_CHAR(d.DATA_INSERCAO, 'DD/MM/YYYY HH24:MI') DT
, coalesce(d.PROCESSO_SYSTEXTIL || ' - ' || p.DESCRICAO, ' ') PRG
, d.*
FROM PCPC_040 l
JOIN MQOP_005 e
  ON e.CODIGO_ESTAGIO = l.CODIGO_ESTAGIO
LEFT JOIN PCPC_045 d
  ON d.PCPC040_PERCONF = l.PERIODO_PRODUCAO
 AND d.PCPC040_ORDCONF = l.ORDEM_CONFECCAO
 AND d.PCPC040_ESTCONF = l.CODIGO_ESTAGIO
 AND d.ORDEM_PRODUCAO = 1016
LEFT JOIN HDOC_036 p
  ON p.CODIGO_PROGRAMA = d.PROCESSO_SYSTEXTIL
 AND p.LOCALE = 'pt_BR'
WHERE l.PERIODO_PRODUCAO = 1729
  AND l.ORDEM_CONFECCAO = 3515
ORDER BY
  l.SEQ_OPERACAO
, d.SEQUENCIA
;
--
SELECT
  d.*
FROM  PCPC_045 d
WHERE d.ORDEM_PRODUCAO = 1016
ORDER BY
  d.PCPC040_PERCONF
, d.PCPC040_ORDCONF
, d.PCPC040_ESTCONF
, d.SEQUENCIA
;
--
DELETE
FROM  PCPC_045 d
WHERE d.ORDEM_PRODUCAO = 1016
;
--
DELETE
FROM  PCPC_045 d
WHERE d.ORDEM_PRODUCAO = 1017
;
