SELECT DISTINCT
  i.DATA_OCORR
, i.*
FROM BASI_400_HIST i -- log do basi_130 (marcelo_comp)
WHERE
  i.DATA_OCORR >= TO_DATE('2017-05-24 10:27','YYYY-MM-DD HH24:MI')
ORDER BY
  i.DATA_OCORR DESC
;
--
SELECT DISTINCT
  i.DATA_OCORR
, i.*
FROM BASI_240_LOG i -- log de classificações fiscais
WHERE
  i.DATA_OCORR >= TO_DATE('2017-06-24 10:27','YYYY-MM-DD HH24:MI')
ORDER BY
  i.DATA_OCORR DESC
;
--
SELECT DISTINCT
  i.DATA_OCORR
, i.*
FROM BASI_205_LOG i -- log de depósito
WHERE
  i.DATA_OCORR >= TO_DATE('2017-07-24 10:27','YYYY-MM-DD HH24:MI')
ORDER BY
  i.DATA_OCORR DESC
;
--
SELECT DISTINCT
  i.DATA_OCORR
, i.*
FROM BASI_030_LOG i -- log de ficha técnica
WHERE
  i.DATA_OCORR >= TO_DATE('2017-07-24 10:27','YYYY-MM-DD HH24:MI')
ORDER BY
  i.DATA_OCORR DESC
;
--
SELECT
  h.DATA_OCORRENCIA
, h.*
FROM HIST_999 h -- log do item (de produto)
WHERE
  h.DATA_OCORRENCIA >= TO_DATE('2017-07-10 10:27','YYYY-MM-DD HH24:MI')
ORDER BY
  h.DATA_OCORRENCIA DESC
;
--
SELECT
  h.DATA_OCORR
, h.*
FROM HIST_100 h -- log de pedido e faturamento
WHERE
  h.DATA_OCORR >= TO_DATE('2017-07-24 16:27','YYYY-MM-DD HH24:MI')
ORDER BY
  h.DATA_OCORR DESC
;
--
SELECT
  h.DATA_OCORR
, h.*
FROM HIST_010 h -- log de lotes
WHERE
  h.DATA_OCORR >= TO_DATE('2017-07-24 17:27','YYYY-MM-DD HH24:MI')
ORDER BY
  h.DATA_OCORR DESC
;
--
