SELECT
  i.PRECO_MEDIO
, i.*
FROM BASI_010 i
WHERE 1=1
  AND i.GRUPO_ESTRUTURA = '00156'
;

SELECT
*
FROM BASI_010 i
WHERE SUBGRU_ESTRUTURA = '35-'
;

UPDATE BASI_010
SET
  SUBGRU_ESTRUTURA = '35A'
WHERE SUBGRU_ESTRUTURA = '35-'
;

SELECT
*
FROM BASI_020
WHERE TAMANHO_REF = '35-'
;

SELECT
  x.*
FROM BASI_023 x
WHERE x.TAMANHO_REF = '35-'
;

UPDATE basi_010 ptc
SET
  ptc.PRECO_MEDIO = 2
WHERE ptc.NIVEL_ESTRUTURA = 1
  AND ptc.PRECO_MEDIO = 0
;

SELECT
  count(*)
FROM ESTQ_040_LOG t
;

SELECT
  *
FROM ESTQ_040_LOG t
;



SELECT DISTINCT
  l.ORDEM_PRODUCAO
, l.NUMERO_ORDEM
, l.SEQ_ORDEM_SERV
, l.PERIODO_PRODUCAO
, l.ORDEM_CONFECCAO
, l.*
FROM pcpc_040 l

UPDATE pcpc_040 l
SET
  l.NUMERO_ORDEM = 0
, l.SEQ_ORDEM_SERV = 0
WHERE 1=1
  --AND l.ORDEM_PRODUCAO = 297
  AND l.NUMERO_ORDEM = 698
  --AND l.CODIGO_ESTAGIO = 39
  AND l.PERIODO_PRODUCAO = 1729
  AND l.ORDEM_CONFECCAO IN (
    7613
  --, 3708
  )
  AND l.NUMERO_ORDEM <> 0
  AND l.SEQ_ORDEM_SERV <> 0
;


select
  *
from basi_010 i
WHERE i.GRUPO_ESTRUTURA = 'ZAL03'
;


SELECT
  e.*
FROM ESTQ_040_HIST e
WHERE e.NIVEL = 9
  AND e.GRUPO = 'EB008'
;

SELECT
  e.*
FROM ESTQ_040_LOG e
WHERE e.CDITEM_NIVEL99_OLD = 9
--  AND e.CDITEM_GRUPO_OLD = 'EB008'
;

SELECT
  e.*
FROM ESTQ_040_TRACE e
WHERE e.CDITEM_NIVEL99_OLD = 9
--  AND e.CDITEM_GRUPO_OLD = 'EB008'
;

SELECT
  e.*
FROM ESTQ_043 e
WHERE e.NIVEL_ESTRUTURA = 9
  AND e.GRUPO_ESTRUTURA = 'EB008'
;

SELECT
  e.*
FROM ESTQ_300_OBRF_015 e
--WHERE e.NIVEL_ESTRUTURA = 9
  --AND e.GRUPO_ESTRUTURA = 'EB008'
;

SELECT
  e.*
FROM ESTQ_040 e
WHERE e.CDITEM_NIVEL99 = 9
  AND e.CDITEM_GRUPO = 'EB008'
;

SELECT
  e.*
FROM ESTQ_301_HIST e
WHERE e.NIVEL_ESTRUTURA_OLD = 9
--  AND e.GRUPO_ESTRUTURA_OLD = 'EB008'
;

SELECT
  e.*
FROM ESTQ_170 e
--WHERE e.NIVEL_ESTRUTURA_OLD = 9
--  AND e.GRUPO_ESTRUTURA_OLD = 'EB008'
;

SELECT
  e.*
FROM BASI_023 e
WHERE e.BASI030_NIVEL030 = 9
  AND e.BASI030_REFERENC = 'EB008'
;

SELECT
  e.*
FROM BASI_030_LOG e
WHERE e.NIVEL_ESTRUTURA_OLD = 9
  AND e.REFERENCIA_OLD = 'EB008'
;

SELECT
  r.*
FROM BASI_050 r
--WHERE r.NIVEL_ITEM = 9
--  AND r.GRUPO_ITEM = 'EB008'
;

SELECT
  r.*
FROM BASI_050 r
WHERE r.NIVEL_ITEM = 9
  AND r.GRUPO_ITEM = 'EB008'
;

SELECT
  r.*
FROM BASI_050 r
WHERE r.NIVEL_COMP = 9
  AND r.GRUPO_COMP = 'EB008'
;

SELECT
  r.*
FROM BASI_001 r
--WHERE r.NIVEL_ESTRUTURA = 9
--  AND r.GRUPO_ESTRUTURA = 'EB008'
;

SELECT
  r.*
FROM ANDAMENTO_REQ_COT r
WHERE r.ITEM_REQ_NIVEL99 = 9
--  AND r.ITEM_REQ_GRUPO = 'EB008'
;

SELECT
  f.*
FROM FICHA_CARDEX f
WHERE f.NIVEL_PRODUTO = 9
--  AND f.GRUPO_PRODUTO = 'EB008'
;

SELECT
  p.*
FROM FTEC_098 p
--WHERE p.NIVEL_PRODUTO = 9
--  AND p.GRUPO_PRODUTO = 'EB008'
WHERE p.NIVEL_COMPONENTE = 9
  AND p.GRUPO_COMPONENTE = 'EB008'
;

SELECT
  p.*
FROM HIST_999 p
WHERE p.NIVEL_PRODUTO = 9
  AND p.GRUPO_PRODUTO = 'EB008'
;

SELECT
  p.*
FROM OBRF_082 p
WHERE p.PRODSAI_NIVEL99 = 9
  AND p.PRODSAI_GRUPO = 'EB008'
;

SELECT
  p.*
FROM PEDx_010 p
--WHERE p.CD_IT_PE_NIVEL99 = 9
--  AND p.PRODSAI_GRUPO = 'EB008'
;

ORDER BY
  PCPC040_PERCONF
, PCPC040_ORDCONF
;

SELECT
  a.*
FROM HDOC_033 a
WHERE a.PROGRAMA = 'supr_f120'
;

SELECT
  a.*
FROM HDOC_033 a
WHERE a.PROGRAMA = 'pedi_f125'
;

UPDATE HDOC_033 a
SET
  a.MODIFICAR = 'N'
, a.EXCLUIR = 'N'
WHERE a.PROGRAMA = 'pedi_f125'
;

UPDATE HDOC_033 a
SET
  a.MODIFICAR = 'S'
, a.EXCLUIR = 'S'
WHERE a.PROGRAMA = 'pedi_f125'
  AND a.USU_PRG_CDUSU IN ('GISELE_COME', 'VANESSA_COME', 'KATY_LOG')
;

SELECT
  c.*
FROM cont_010 c
WHERE c.CODIGO_HISTORICO IN (10,20)
;

UPDATE cont_010 c
SET
  c.ATUALIZA_COMIS = 1
WHERE c.CODIGO_HISTORICO IN (10,20)
;

SELECT
  e.SEQUENCIA
, e.NIVEL_COMP NIVEL
, e.GRUPO_COMP GRUPO
, r.DESCR_REFERENCIA DESCR
, e.SUB_COMP SUBGRUPO
, e.ITEM_COMP ITEM
, e.ALTERNATIVA_COMP ALTERN
, e.CONSUMO
, e.ESTAGIO || '-' || es.DESCRICAO ESTAGIO
FROM BASI_050 e
LEFT JOIN basi_030 r
  ON r.NIVEL_ESTRUTURA = e.NIVEL_COMP
 AND r.REFERENCIA = e.GRUPO_COMP
LEFT JOIN MQOP_005 es
  ON es.CODIGO_ESTAGIO = e.ESTAGIO
WHERE e.NIVEL_ITEM = 1
  AND e.GRUPO_ITEM = '0640R'
  AND e.ALTERNATIVA_ITEM = 1
ORDER BY
  e.SEQUENCIA
;

SELECT
  count(*)
--  *
FROM HIST_010
;

SELECT
  count(*)
, min(r.NIVEL_ESTRUTURA)
FROM basi_030 r
WHERE r.REFERENCIA = 'AL004'
;

SELECT
  cc.*
FROM CONT_540 cc
WHERE cc.TIPO_CONTABIL = 3
;

SELECT
  r.DESCR_REFERENCIA DESCR
, r.UNIDADE_MEDIDA || ' - ' || um.DESCR_UNIDADE UM
, r.CONTA_ESTOQUE || ' - ' || ce.DESCR_CT_ESTOQUE CONTA_ESTOQUE
, r.CLASSIFIC_FISCAL || ' - ' || cf.DESCR_CLASS_FISC NCM
, r.CODIGO_CONTABIL || ' - ' || cc.DESCRICAO CODIGO_CONTABIL
, CASE WHEN r.TIPO_PRODUTO = 1 THEN '1 - Tecido Normal (liso e estampado)'
  WHEN r.TIPO_PRODUTO = 2 THEN '2 - Tecido Listrado (com fio tinto)'
  WHEN r.TIPO_PRODUTO = 3 THEN '3 - Gola'
  WHEN r.TIPO_PRODUTO = 4 THEN '4 - Punho'
  WHEN r.TIPO_PRODUTO = 5 THEN '5 - Ribanas'
  WHEN r.TIPO_PRODUTO = 6 THEN '6 - Retilínea(Golas, punhos, tiras, decotes)'
  END TIPO_PRODUTO
FROM basi_030 r
JOIN basi_200 um
  ON um.unidade_medida = r.UNIDADE_MEDIDA
JOIN BASI_150 ce
  ON ce.CONTA_ESTOQUE = r.CONTA_ESTOQUE
JOIN BASI_240 cf
  ON cf.CLASSIFIC_FISCAL = r.CLASSIFIC_FISCAL
JOIN CONT_540 cc
  ON cc.TIPO_CONTABIL = 3
 AND cc.CODIGO_CONTABIL = r.CODIGO_CONTABIL
LEFT JOIN BASI_120 lin
  ON lin.NIVEL_ESTRUTURA = 1
 AND lin.LINHA_PRODUTO = r.LINHA_PRODUTO
WHERE r.NIVEL_ESTRUTURA = '2'
  AND r.REFERENCIA = 'MA002'
;

SELECT DISTINCT
  t.TAMANHO_REF TAM
, t.DESCR_TAM_REFER DESCR
, tam.ORDEM_TAMANHO ORD
, t.DESC_TAM_FICHA
FROM basi_020 t
LEFT JOIN BASI_220 tam
  ON tam.TAMANHO_REF = t.TAMANHO_REF
WHERE t.BASI030_NIVEL030 = 9
  AND t.BASI030_REFERENC = 'AL004'
ORDER BY
  tam.ORDEM_TAMANHO
;

SELECT
  p.SUBGRU_ESTRUTURA TAM
, p.ITEM_ESTRUTURA COR
, p.CODIGO_DEPOSITO || ' - ' || d.DESCRICAO DEPOSITO
, p.ESTOQUE_MINIMO
, p.ESTOQUE_MAXIMO
, p.TEMPO_REPOSICAO LEAD
FROM BASI_015 p
JOIN BASI_205 d
  ON d.CODIGO_DEPOSITO = p.CODIGO_DEPOSITO
WHERE p.NIVEL_ESTRUTURA = '9'
  AND p.GRUPO_ESTRUTURA = 'AL004'
;

SELECT DISTINCT
  e.ALTERNATIVA_ITEM ALTERNATIVA
, COALESCE( al.DESCRICAO, '' ) DESCR
, COALESCE(
  ( SELECT
      ec.GRUPO_COMP
    FROM BASI_050 ec
    WHERE ec.NIVEL_ITEM = e.NIVEL_ITEM
      AND ec.GRUPO_ITEM = e.GRUPO_ITEM
      AND ec.ALTERNATIVA_ITEM = e.ALTERNATIVA_ITEM
      AND ec.NIVEL_COMP = 1
      AND rownum = 1
  ), ' ') REF
FROM BASI_050 e
LEFT JOIN BASI_070 al
  ON al.ALTERNATIVA = e.ALTERNATIVA_ITEM
 AND al.ROTEIRO = 0
WHERE e.NIVEL_ITEM = 1
  AND e.GRUPO_ITEM = '0640R'
ORDER BY
  e.ALTERNATIVA_ITEM
;

SELECT DISTINCT
  CASE WHEN r.REFERENCIA <= '99999' THEN 'PA'
  WHEN r.REFERENCIA like 'A%' or r.REFERENCIA like 'B%' THEN 'PG'
  WHEN r.REFERENCIA like 'Z%' THEN 'MP'
  ELSE 'MD'
  END TIPO
, e.GRUPO_ITEM REF
, r.DESCR_REFERENCIA DESCR
, e.CONSUMO
, e.ALTERNATIVA_ITEM
FROM BASI_050 e
LEFT JOIN basi_030 r
  ON r.NIVEL_ESTRUTURA = e.NIVEL_ITEM
 AND r.REFERENCIA = e.GRUPO_ITEM
WHERE r.RESPONSAVEL IS NOT NULL
  AND e.NIVEL_ITEM = 1
  AND e.NIVEL_COMP = 9
  AND e.GRUPO_COMP = 'ET002'
ORDER BY
  NLSSORT(e.GRUPO_ITEM,'NLS_SORT=BINARY_AI')
;


with TableWithNum as (


SELECT
  rownum NUM
, op.SITUACAO OP_SITUACAO
, l.ORDEM_PRODUCAO OP
, CASE WHEN dos.NUMERO_ORDEM IS NULL
  THEN '0'
  ELSE l.NUMERO_ORDEM || ' (' || eos.DESCRICAO || ')'
  END OS
, l.PROCONF_GRUPO REF
, l.PROCONF_SUBGRUPO TAM
, l.PROCONF_ITEM COR
, COALESCE(
  ( SELECT
      LISTAGG(le.CODIGO_ESTAGIO || ' - ' || ed.DESCRICAO, ' & ')
      WITHIN GROUP (ORDER BY le.CODIGO_ESTAGIO)
    FROM PCPC_040 le
    JOIN MQOP_005 ed
      ON ed.CODIGO_ESTAGIO = le.CODIGO_ESTAGIO
    WHERE le.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
      AND le.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
      AND le.QTDE_EM_PRODUCAO_PACOTE <> 0
  )
  , 'FINALIZADO'
  ) EST
, l.PERIODO_PRODUCAO PERIODO
, l.ORDEM_CONFECCAO OC
, l.QTDE_PECAS_PROG QTD
, r.NARRATIVA
, l.DIVISAO DIVISAO_pcp
, osc.CGCTERC_FORNE9
, CASE WHEN l.DIVISAO <> 0 THEN 'l'
  ELSE CASE WHEN dp.DIVISAO_PRODUCAO <> 0
       THEN 'd'
       ELSE 'n'
       END
  END DL_DIVISAO
, CASE WHEN l.DIVISAO = 0 THEN dp.DIVISAO_PRODUCAO
  ELSE l.DIVISAO END DIVISAO
, CASE WHEN l.DIVISAO = 0 THEN dp.DESCRICAO
  ELSE di.DESCRICAO END DESCRICAO_DIVISAO
FROM (
  SELECT
    os.PERIODO_PRODUCAO
  , os.ORDEM_CONFECCAO
  , os.PROCONF_GRUPO
  , os.PROCONF_SUBGRUPO
  , os.PROCONF_ITEM
  , os.ORDEM_PRODUCAO
  , max( os.NUMERO_ORDEM ) NUMERO_ORDEM
  , max( os.QTDE_PECAS_PROG ) QTDE_PECAS_PROG
  , max( CASE WHEN os.CODIGO_FAMILIA < 1000
         THEN os.CODIGO_FAMILIA
         ELSE 0 END ) DIVISAO
  FROM PCPC_040 os
  WHERE 1=1
    --AND (os.ORDEM_CONFECCAO >= 211 or 211 IS NULL)
    --AND (os.ORDEM_CONFECCAO <= 222 or 222 IS NULL)
    AND (os.ORDEM_PRODUCAO > 2000 )-- or 2111 IS NULL)
    AND (os.NUMERO_ORDEM = '' OR '' IS NULL)
    AND (os.PROCONF_SUBGRUPO = '' OR '' IS NULL)
    AND (os.PROCONF_ITEM = '' OR '' IS NULL)
  GROUP BY
    os.PERIODO_PRODUCAO
  , os.ORDEM_CONFECCAO
  , os.PROCONF_GRUPO
  , os.PROCONF_SUBGRUPO
  , os.PROCONF_ITEM
  , os.ORDEM_PRODUCAO
) l
LEFT JOIN PCPC_040 dos
  ON l.NUMERO_ORDEM <> 0
 AND dos.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
 AND dos.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
 AND dos.NUMERO_ORDEM = l.NUMERO_ORDEM
LEFT JOIN MQOP_005 eos
  ON eos.CODIGO_ESTAGIO = dos.CODIGO_ESTAGIO
LEFT JOIN BASI_220 t
  ON t.TAMANHO_REF = l.PROCONF_SUBGRUPO
JOIN BASI_010 r
  ON r.NIVEL_ESTRUTURA = 1
 AND r.GRUPO_ESTRUTURA = l.PROCONF_GRUPO
 AND r.SUBGRU_ESTRUTURA = l.PROCONF_SUBGRUPO
 AND r.ITEM_ESTRUTURA = l.PROCONF_ITEM
LEFT JOIN BASI_180 di -- divisao de producao - unidade
  ON di.DIVISAO_PRODUCAO = l.DIVISAO
LEFT JOIN OBRF_080 osc -- OS capa
  ON l.NUMERO_ORDEM <> 0
 AND osc.NUMERO_ORDEM = l.NUMERO_ORDEM
LEFT JOIN BASI_180 dp -- divisao de producao - unidade
  ON dp.FACCIONISTA9 = osc.CGCTERC_FORNE9
 AND dp.FACCIONISTA4 = osc.CGCTERC_FORNE4
 AND dp.FACCIONISTA2 = osc.CGCTERC_FORNE2
JOIN PCPC_020 op -- OP capa
  ON op.ordem_producao = l.ORDEM_PRODUCAO
WHERE l.DIVISAO <> 0
  AND l.DIVISAO <> 6
ORDER BY
  l.ORDEM_PRODUCAO
, l.NUMERO_ORDEM
, l.PROCONF_GRUPO
, l.PROCONF_ITEM
, t.ORDEM_TAMANHO
, l.PERIODO_PRODUCAO
, l.ORDEM_CONFECCAO
;

SELECT
  op.SITUACAO
, op.*
FROM pcpc_020 op
;


)
select * from TableWithNum where NUM > 0
;

SELECT
  max(o.CODIGO_FAMILIA) DIVISAO
FROM PCPC_040 o
WHERE o.ORDEM_PRODUCAO = 2290
;

SELECT
  o.*
FROM PCPC_030 o
WHERE o.ORDEM_PRODUCAO = 2290
;

  SELECT
    os.PERIODO_PRODUCAO
  , os.ORDEM_CONFECCAO
  , os.PROCONF_GRUPO
  , os.PROCONF_SUBGRUPO
  , os.PROCONF_ITEM
  , os.ORDEM_PRODUCAO
  , max( os.NUMERO_ORDEM ) NUMERO_ORDEM
  , max( os.QTDE_PECAS_PROG ) QTDE_PECAS_PROG
  , os.CODIGO_FAMILIA DIVISAO
  FROM PCPC_040 os
  WHERE 1=1
    --AND (os.ORDEM_CONFECCAO >= 211 or 211 IS NULL)
    --AND (os.ORDEM_CONFECCAO <= 222 or 222 IS NULL)
    AND (os.ORDEM_PRODUCAO = 2077 or 2077 IS NULL)
    AND (os.NUMERO_ORDEM = '' OR '' IS NULL)
    AND (os.PROCONF_SUBGRUPO = '' OR '' IS NULL)
    AND (os.PROCONF_ITEM = '' OR '' IS NULL)
  GROUP BY
    os.PERIODO_PRODUCAO
  , os.ORDEM_CONFECCAO
  , os.PROCONF_GRUPO
  , os.PROCONF_SUBGRUPO
  , os.PROCONF_ITEM
  , os.ORDEM_PRODUCAO
  , os.CODIGO_FAMILIA
;

SELECT DISTINCT
  os.ORDEM_PRODUCAO
, os.*
FROM PCPC_040 os
WHERE os.CODIGO_ESTAGIO = 39
  --AND os.NUMERO_ORDEM <> 0
  AND os.CODIGO_FAMILIA <> 0
;

SELECT DISTINCT
  os.ORDEM_PRODUCAO
, os.*
FROM PCPC_040 os
WHERE 1=1
  -- AND os.CODIGO_ESTAGIO = 39
  -- AND os.NUMERO_ORDEM <> 0
  AND os.CODIGO_FAMILIA = 6
;

SELECT DISTINCT
  os.CODIGO_FAMILIA
FROM PCPC_040 os
ORDER BY
  os.CODIGO_FAMILIA
;

SELECT
  *
FROM OBRF_080
;

SELECT DISTINCT
  os.ORDEM_PRODUCAO
, os.CODIGO_FAMILIA
FROM PCPC_040 os
WHERE 1=1
  -- AND os.CODIGO_ESTAGIO = 39
  -- AND os.NUMERO_ORDEM <> 0
  AND os.ORDEM_PRODUCAO = 2077
;

SELECT
  *
FROM basi_180 -- divisão de produção "= célula"
;

SELECT
  *
FROM PCPC_600
;

SELECT DISTINCT
  CAST(
  COALESCE(
  CASE WHEN r.REFERENCIA < 'C0000' THEN
    CAST( CAST( regexp_replace(r.REFERENCIA, '[^0-9]', '')
                AS INTEGER ) AS VARCHAR2(5) )
  ELSE
    ( SELECT
          CASE WHEN ec.GRUPO_ITEM IS NULL THEN '0'
          ELSE CAST( CAST( regexp_replace(ec.GRUPO_ITEM, '[^0-9]', '')
                           AS INTEGER ) AS VARCHAR2(5) )
          END
        FROM BASI_050 ec
        WHERE ec.NIVEL_COMP = r.NIVEL_ESTRUTURA
          AND ec.GRUPO_COMP = r.REFERENCIA
          AND rownum = 1
    )
  END
  , '0' ) AS INTEGER ) MODELO
, COALESCE(
  CASE WHEN r.REFERENCIA < 'C0000' THEN
    r.DESCR_REFERENCIA
  ELSE
    ( SELECT
          CASE WHEN ec.GRUPO_ITEM IS NULL THEN ' '
          ELSE rec.DESCR_REFERENCIA
          END
        FROM BASI_050 ec
        JOIN BASI_030 rec
          ON rec.REFERENCIA = ec.GRUPO_ITEM
         AND rec.NIVEL_ESTRUTURA = ec.NIVEL_ITEM
        WHERE ec.NIVEL_COMP = r.NIVEL_ESTRUTURA
          AND ec.GRUPO_COMP = r.REFERENCIA
          AND rownum = 1
    )
  END
  , ' ' ) DESCRICAO
FROM BASI_030 r
--WHERE r.DESCR_REFERENCIA LIKE '%SLIP%'
ORDER BY
  1
;

SELECT
  m.modelo
, (
	SELECT
	  COALESCE(
	    r.DESCR_REFERENCIA
	  , ' ' )
	FROM BASI_030 r
    WHERE r.NIVEL_ESTRUTURA = 1
	  AND
	  CAST(
	  COALESCE(
	    CAST( CAST( regexp_replace(r.REFERENCIA, '[^0-9]', '')
	                AS INTEGER ) AS VARCHAR2(5) )
	  , '0' ) AS INTEGER ) = m.modelo
    AND rownum = 1
  ) DESCRICAO
FROM
(
SELECT DISTINCT
  CAST(
  COALESCE(
    CAST( CAST( regexp_replace(r.REFERENCIA, '[^0-9]', '')
                AS INTEGER ) AS VARCHAR2(5) )
  , '0' ) AS INTEGER ) MODELO
FROM BASI_030 r
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.REFERENCIA <= '99999'
--  AND r.DESCR_REFERENCIA LIKE '%SLIP%'
ORDER BY
  1
  ) m
WHERE m.modelo <> 0
;

SELECT
  ec.GRUPO_ITEM REF
, CASE WHEN ec.GRUPO_ITEM <= '99999' THEN 'PA'
  WHEN ec.GRUPO_ITEM < 'C0000' THEN 'PG'
  WHEN ec.GRUPO_ITEM < 'Z0000' THEN 'MD'
  ELSE 'MP'
  END TIPO
FROM BASI_050 ec
WHERE ec.NIVEL_COMP = 1
  AND ec.GRUPO_COMP = 'C0776'
;

SELECT
  rownum NUM
, rr.NIVEL
, rr.REF
, rr.TIPO
, rr.DESCR
, rr.RESP
FROM (
SELECT
  r.NIVEL_ESTRUTURA NIVEL
, r.REFERENCIA REF
, CASE WHEN r.REFERENCIA <= '99999' THEN 'PA'
  WHEN r.REFERENCIA like 'A%' or r.REFERENCIA like 'B%' THEN 'PG'
  WHEN r.REFERENCIA like 'Z%' THEN 'MP'
  ELSE 'MD'
  END TIPO
, r.DESCR_REFERENCIA DESCR
, r.RESPONSAVEL RESP
FROM BASI_030 r
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND (  r.REFERENCIA LIKE '%SL%'
      OR r.DESCR_REFERENCIA LIKE '%SL%'
      )
ORDER BY
  NLSSORT(r.REFERENCIA,'NLS_SORT=BINARY_AI')
) rr
;

SELECT DISTINCT
  ec.GRUPO_ITEM REF
, CASE WHEN ec.GRUPO_ITEM <= '99999' THEN 'PA'
  WHEN ec.GRUPO_ITEM < 'C0000' THEN 'PG'
  WHEN ec.GRUPO_ITEM < 'Z0000' THEN 'MD'
  ELSE 'MP'
  END TIPO
, ec.ALTERNATIVA_ITEM ALTERNATIVA
FROM BASI_050 ec
JOIN BASI_030 r
  ON r.NIVEL_ESTRUTURA = ec.NIVEL_ITEM
 AND r.REFERENCIA = ec.GRUPO_ITEM
WHERE ec.NIVEL_COMP = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND ec.GRUPO_COMP = 'A0620'
;


SELECT DISTINCT
  e.SEQUENCIA
, e.NIVEL_COMP NIVEL
, e.GRUPO_COMP REF
, r.DESCR_REFERENCIA DESCR
, e.SUB_COMP TAM
, e.ITEM_COMP COR
, e.ALTERNATIVA_COMP ALTERN
, e.CONSUMO
, e.ESTAGIO || '-' || es.DESCRICAO ESTAGIO
, (
  SELECT
    LISTAGG(ee.ITEM_ITEM, ', ')
      WITHIN GROUP (ORDER BY ee.ITEM_ITEM)
  FROM BASI_050 ee
  WHERE ee.SEQUENCIA = e.SEQUENCIA
    AND ee.NIVEL_ITEM = e.NIVEL_ITEM
    AND ee.GRUPO_ITEM = e.GRUPO_ITEM
    AND ee.ALTERNATIVA_ITEM = e.ALTERNATIVA_ITEM
    AND ee.NIVEL_COMP = e.NIVEL_COMP
    AND ee.GRUPO_COMP = e.GRUPO_COMP
    AND ee.SUB_COMP = e.SUB_COMP
    AND ee.ITEM_COMP = e.ITEM_COMP
--    AND rownum = 1
  ) COR_REF
--, e.*
FROM BASI_050 e
LEFT JOIN basi_030 r
  ON r.NIVEL_ESTRUTURA = e.NIVEL_COMP
 AND r.REFERENCIA = e.GRUPO_COMP
LEFT JOIN MQOP_005 es
  ON es.CODIGO_ESTAGIO = e.ESTAGIO
WHERE e.NIVEL_ITEM = 1
  AND e.GRUPO_ITEM = 'M0156'
  AND e.ALTERNATIVA_ITEM = 4
ORDER BY
  e.SEQUENCIA
;

SELECT
	CAST(
	  CASE WHEN ec.GRUPO_ITEM IS NULL THEN 0
	  ELSE CAST( regexp_replace(ec.GRUPO_ITEM, '[^0-9]', '')
	                   AS INTEGER )
	  END
   AS VARCHAR2(5) )
, ec.*
FROM BASI_050 ec
JOIN BASI_030 rr
  ON rr.NIVEL_ESTRUTURA = ec.NIVEL_ITEM
 AND rr.REFERENCIA = ec.GRUPO_ITEM
 AND rr.RESPONSAVEL IS NOT NULL
WHERE ec.NIVEL_COMP = 1
  AND ec.GRUPO_COMP = 'M0156'
;

SELECT DISTINCT
  CASE WHEN r.REFERENCIA <= '99999' THEN 'PA'
  WHEN r.REFERENCIA like 'A%' or r.REFERENCIA like 'B%' THEN 'PG'
  WHEN r.REFERENCIA like 'Z%' THEN 'MP'
  ELSE 'MD'
  END TIPO
, e.GRUPO_ITEM REF
, r.DESCR_REFERENCIA DESCR
, e.ALTERNATIVA_ITEM ALTERNATIVA
, e.CONSUMO
, e.ESTAGIO || '-' || es.DESCRICAO ESTAGIO
FROM BASI_050 e
LEFT JOIN basi_030 r
  ON r.NIVEL_ESTRUTURA = e.NIVEL_ITEM
 AND r.REFERENCIA = e.GRUPO_ITEM
LEFT JOIN MQOP_005 es
  ON es.CODIGO_ESTAGIO = e.ESTAGIO
WHERE 1=1
--  AND r.RESPONSAVEL IS NOT NULL
  AND e.NIVEL_ITEM = 1
  AND e.NIVEL_COMP = 9
  AND e.GRUPO_COMP = 'EB006'
ORDER BY
  NLSSORT(e.GRUPO_ITEM,'NLS_SORT=BINARY_AI')
, e.ALTERNATIVA_ITEM
;

SELECT
  e.*
FROM PCPC_360 e
--WHERE e.ESTAGIO_ANTERIOR = 39
;

SELECT
  u.*
FROM HDOC_030 u
;

SELECT
  t.*
FROM MQOP_006 t
;


SELECT
  cast( SUM( lp.QTDE_PECAS_PROD ) / SUM( lp.QTDE_PECAS_PROG ) * 100
        AS NUMERIC(10,2) )
FROM pcpc_040 lp
WHERE lp.ORDEM_PRODUCAO = ll.ORDEM_PRODUCAO
  AND lp.SEQ_OPERACAO = ll.SEQ_OPERACAO
;


SELECT
  e.*
FROM MQOP_005 e
WHERE e.CODIGO_ESTAGIO = 54
;

SELECT
  l.*
FROM PCPC_040 l
;

SELECT
  e.CODIGO_ESTAGIO ESTAGIO
, e.DESCRICAO
, l.PERIODO_PRODUCAO PERIODO
, l.PROCONF_GRUPO REF
, l.ORDEM_PRODUCAO OP
, SUM( l.QTDE_PECAS_PROG - l.QTDE_PECAS_PROD) QTD
, COUNT(*) LOTES
FROM MQOP_005 e
JOIN PCPC_040 l
  ON l.CODIGO_ESTAGIO = e.CODIGO_ESTAGIO
JOIN PCPC_020 o
  ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
WHERE l.QTDE_EM_PRODUCAO_PACOTE <> 0
  AND o.SITUACAO = 4 -- Ordens em produção
  AND e.CODIGO_ESTAGIO = 55
  AND l.PERIODO_PRODUCAO >= 1721
  AND l.PERIODO_PRODUCAO <= 1733
GROUP BY
  e.CODIGO_ESTAGIO
, e.DESCRICAO
, l.ORDEM_PRODUCAO
, l.PROCONF_GRUPO
, l.PERIODO_PRODUCAO
ORDER BY
  e.CODIGO_ESTAGIO
, l.PERIODO_PRODUCAO
, l.PROCONF_GRUPO
, l.ORDEM_PRODUCAO
;

SELECT
  e.CODIGO_ESTAGIO ESTAGIO
, e.DESCRICAO
, l.PERIODO_PRODUCAO PERIODO
, l.PROCONF_GRUPO REF
, l.ORDEM_PRODUCAO OP
, l.*
FROM MQOP_005 e
JOIN PCPC_040 l
  ON l.CODIGO_ESTAGIO = e.CODIGO_ESTAGIO
JOIN PCPC_020 o
  ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
WHERE l.QTDE_EM_PRODUCAO_PACOTE <> 0
  AND o.SITUACAO = 4 -- Ordens em produção
  AND e.CODIGO_ESTAGIO = 55
  AND l.PERIODO_PRODUCAO >= 1721
  AND l.PERIODO_PRODUCAO <= 1733
ORDER BY
  e.CODIGO_ESTAGIO
, l.PERIODO_PRODUCAO
, l.PROCONF_GRUPO
, l.ORDEM_PRODUCAO
;

SELECT
  p.DATA_INI_PERIODO
, p.DATA_FIM_PERIODO
FROM PCPC_010 p
WHERE p.AREA_PERIODO = 1
  AND p.PERIODO_PRODUCAO = 1701
;

SELECT
  pend.*
, (
  SELECT
    COUNT(*)
  FROM PCPC_040 ll -- lotes
  WHERE ll.ORDEM_PRODUCAO = pend.OP
    AND ll.SEQ_OPERACAO < pend.SEQ
    AND ll.QTDE_EM_PRODUCAO_PACOTE <> 0
  ) LOTES_ANTES
, (
  SELECT
    COUNT(*)
  FROM PCPC_040 ll -- lotes
  WHERE ll.ORDEM_PRODUCAO = pend.OP
    AND ll.CODIGO_ESTAGIO = pend.ESTAGIO
  ) QTD_LOTES
, (
  SELECT
    COUNT(*)
  FROM PCPC_040 ll -- lotes
  WHERE ll.ORDEM_PRODUCAO = pend.OP
    AND ll.SEQ_OPERACAO > pend.SEQ
    AND ll.QTDE_EM_PRODUCAO_PACOTE <> 0
  ) LOTES_DEPOIS
FROM
(
SELECT
  e.CODIGO_ESTAGIO ESTAGIO
, e.DESCRICAO
, l.PERIODO_PRODUCAO PERIODO
, p.DATA_INI_PERIODO DATA_INI
, p.DATA_FIM_PERIODO DATA_FIM
, l.PROCONF_GRUPO REF
, l.ORDEM_PRODUCAO OP
, l.SEQ_OPERACAO SEQ
, o.DATA_ENTRADA_CORTE DT_CORTE
, SUM( l.QTDE_PECAS_PROG - l.QTDE_PECAS_PROD) QTD
, COUNT(*) LOTES
FROM MQOP_005 e -- estagio
JOIN PCPC_040 l -- lotes
  ON l.CODIGO_ESTAGIO = e.CODIGO_ESTAGIO
JOIN PCPC_020 o -- OP
  ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
JOIN PCPC_010 p -- periodo
  ON p.AREA_PERIODO = 1
 AND p.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
WHERE l.QTDE_EM_PRODUCAO_PACOTE <> 0
  AND o.SITUACAO = 4 -- Ordens em produção
--  AND e.CODIGO_ESTAGIO = 55
  AND l.PERIODO_PRODUCAO >= 1721
  AND l.PERIODO_PRODUCAO <= 1733
--  AND l.ORDEM_PRODUCAO = 425
GROUP BY
  e.CODIGO_ESTAGIO
, e.DESCRICAO
, l.PERIODO_PRODUCAO
, p.DATA_INI_PERIODO
, p.DATA_FIM_PERIODO
, l.PROCONF_GRUPO
, l.ORDEM_PRODUCAO
, l.SEQ_OPERACAO
, o.DATA_ENTRADA_CORTE
ORDER BY
  e.CODIGO_ESTAGIO
, l.PERIODO_PRODUCAO
, l.PROCONF_GRUPO
, l.ORDEM_PRODUCAO
) pend
;

SELECT
  l.ORDEM_PRODUCAO
, l.CODIGO_ESTAGIO
, l.SEQ_OPERACAO
, l.*
FROM PCPC_040 l -- lotes
WHERE l.ORDEM_PRODUCAO = 391
;

SELECT
  ll.ORDEM_PRODUCAO
, ll.CODIGO_ESTAGIO
, ll.SEQ_OPERACAO
, ll.*
FROM PCPC_040 ll -- lotes
WHERE ll.ORDEM_PRODUCAO = 425
  AND ll.SEQ_OPERACAO < 60
  AND ll.QTDE_EM_PRODUCAO_PACOTE <> 0
;


SELECT
  l.*
FROM PCPC_040 l
WHERE l.ORDEM_PRODUCAO in ( 2605, 2606 )
--  AND l.ORDEM_CONFECCAO in ( 12247, 12248 )
;


SELECT
  r.SEQ_OPERACAO
, r.CODIGO_OPERACAO
, o.NOME_OPERACAO
, r.CODIGO_ESTAGIO
, e.DESCRICAO
, CASE WHEN r.IND_ESTAGIO_GARGALO = 1
  THEN 'Gargalo'
  ELSE ' '
  END GARGALO
, r.NUMERO_ALTERNATI
, r.NUMERO_ROTEIRO
, r.*
FROM MQOP_050 r -- roteiro
JOIN MQOP_005 e -- estagio
  ON e.CODIGO_ESTAGIO = r.CODIGO_ESTAGIO
JOIN MQOP_040 o -- operacao
  ON o.CODIGO_OPERACAO = r.CODIGO_OPERACAO
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.GRUPO_ESTRUTURA = '0640R'
  AND r.NUMERO_ALTERNATI = 1
  AND r.NUMERO_ROTEIRO = 1
ORDER BY
  r.SEQ_OPERACAO
;

SELECT
  o.*
FROM MQOP_040 o -- operacao
;

SELECT
  COALESCE(
  CASE WHEN o.REFERENCIA_PECA < 'C0000' THEN
    CAST( CAST( regexp_replace(o.REFERENCIA_PECA, '[^0-9]', '')
                AS INTEGER ) AS VARCHAR2(5) )
  ELSE
    ( SELECT
        CAST( MAX(
          CASE WHEN ec.GRUPO_ITEM IS NULL THEN 0
          ELSE CAST( regexp_replace(ec.GRUPO_ITEM, '[^0-9]', '')
                     AS INTEGER )
          END
        ) AS VARCHAR2(5) )
        FROM BASI_050 ec
        JOIN BASI_030 rr
          ON rr.NIVEL_ESTRUTURA = ec.NIVEL_ITEM
         AND rr.REFERENCIA = ec.GRUPO_ITEM
         AND rr.RESPONSAVEL IS NOT NULL
        WHERE ec.NIVEL_COMP = 1
          AND ec.GRUPO_COMP = o.REFERENCIA_PECA
    )
  END
  , ' ' ) MODELO
, o.*
FROM PCPC_020 o
WHERE o.ORDEM_PRODUCAO = 1000
  AND o.REFERENCIA_PECA = '0693U'
;

SELECT
  i.*
FROM BASI_010 i
WHERE i.GRUPO_ESTRUTURA = '0640A'
  AND i.SUBGRU_ESTRUTURA = 'M'
  AND i.ITEM_ESTRUTURA = '0000PR'
;

UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230965' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='P' AND ITEM_ESTRUTURA='0000PR';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230958' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='M' AND ITEM_ESTRUTURA='0000PR';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230941' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='G' AND ITEM_ESTRUTURA='0000PR';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230934' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='GG' AND ITEM_ESTRUTURA='0000PR';

UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896231122' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='P' AND ITEM_ESTRUTURA='0000CB';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896231115' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='M' AND ITEM_ESTRUTURA='0000CB';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896231108' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='G' AND ITEM_ESTRUTURA='0000CB';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896231092' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='GG' AND ITEM_ESTRUTURA='0000CB';

UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896231085' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='P' AND ITEM_ESTRUTURA='0000MA';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230996' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='M' AND ITEM_ESTRUTURA='0000MA';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230989' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='G' AND ITEM_ESTRUTURA='0000MA';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230972' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='GG' AND ITEM_ESTRUTURA='0000MA';

UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230927' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='P' AND ITEM_ESTRUTURA='0000VE';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230910' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='M' AND ITEM_ESTRUTURA='0000VE';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230903' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='G' AND ITEM_ESTRUTURA='0000VE';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230897' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0640A' AND SUBGRU_ESTRUTURA='GG' AND ITEM_ESTRUTURA='0000VE';

UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230927' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0643A' AND SUBGRU_ESTRUTURA='P'  AND ITEM_ESTRUTURA='0000PR';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230910' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0643A' AND SUBGRU_ESTRUTURA='M'  AND ITEM_ESTRUTURA='0000PR';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230903' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0643A' AND SUBGRU_ESTRUTURA='G'  AND ITEM_ESTRUTURA='0000PR';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7896896230897' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='0643A' AND SUBGRU_ESTRUTURA='GG' AND ITEM_ESTRUTURA='0000PR';

SELECT
  i.NIVEL_ESTRUTURA
, i.GRUPO_ESTRUTURA
, i.SUBGRU_ESTRUTURA
, i.ITEM_ESTRUTURA
, i.CODIGO_BARRAS
FROM BASI_010 i
LEFT JOIN BASI_220 t
  ON t.TAMANHO_REF = i.SUBGRU_ESTRUTURA
WHERE i.GRUPO_ESTRUTURA = '0643A'
--  AND i.SUBGRU_ESTRUTURA = 'M'
  AND i.ITEM_ESTRUTURA = '0000PR'
ORDER BY
  i.ITEM_ESTRUTURA
, t.ORDEM_TAMANHO
;

UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7899618822899' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='2156E' AND SUBGRU_ESTRUTURA='P'  AND ITEM_ESTRUTURA='0000CZ';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7899618822905' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='2156E' AND SUBGRU_ESTRUTURA='M'  AND ITEM_ESTRUTURA='0000CZ';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7899618822912' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='2156E' AND SUBGRU_ESTRUTURA='G'  AND ITEM_ESTRUTURA='0000CZ';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7899618822929' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='2156E' AND SUBGRU_ESTRUTURA='GG' AND ITEM_ESTRUTURA='0000CZ';

UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7899618821038' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='2156E' AND SUBGRU_ESTRUTURA='P'  AND ITEM_ESTRUTURA='0000BR';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7899618821045' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='2156E' AND SUBGRU_ESTRUTURA='M'  AND ITEM_ESTRUTURA='0000BR';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7899618821052' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='2156E' AND SUBGRU_ESTRUTURA='G'  AND ITEM_ESTRUTURA='0000BR';
UPDATE SYSTEXTIL.BASI_010 SET CODIGO_BARRAS='7899618821434' WHERE NIVEL_ESTRUTURA='1' AND GRUPO_ESTRUTURA='2156E' AND SUBGRU_ESTRUTURA='GG' AND ITEM_ESTRUTURA='0000BR';

SELECT
  i.NIVEL_ESTRUTURA
, i.GRUPO_ESTRUTURA
, i.ITEM_ESTRUTURA
, i.SUBGRU_ESTRUTURA
, i.CODIGO_BARRAS
FROM BASI_010 i
LEFT JOIN BASI_220 t -- tamanhos
  ON t.TAMANHO_REF = i.SUBGRU_ESTRUTURA
WHERE i.GRUPO_ESTRUTURA = '2156E'
--  AND i.SUBGRU_ESTRUTURA = 'M'
--  AND i.ITEM_ESTRUTURA = '0000MA'
ORDER BY
  i.ITEM_ESTRUTURA
, t.ORDEM_TAMANHO
;

SELECT
  case
  when o.REFERENCIA_PECA <= '99999' then 'PA'
  when o.REFERENCIA_PECA <= 'A9999' then 'PG'
  else 'MD'
  end TIPO_REF
, CASE
  WHEN o.ORDEM_PRINCIPAL <> 0 THEN 'Filha de'
  WHEN ofi.ORDEM_PRODUCAO IS NOT NULL THEN 'Mãe de'
  ELSE 'Avulsa'
  END TIPO_OP
, coalesce( ofi.ORDEM_PRODUCAO, o.ORDEM_PRINCIPAL ) OP_REL
, o.SITUACAO ||
  CASE
  WHEN o.SITUACAO = 2 THEN '-Ordem conf. gerada'
  WHEN o.SITUACAO = 4 THEN '-Ordens em produção'
  WHEN o.SITUACAO = 9 THEN '-Ordem cancelada'
  ELSE ' '
  END SITUACAO
, o.COD_CANCELAMENTO ||
  CASE
  WHEN o.COD_CANCELAMENTO = 0 THEN ''
  ELSE '-' || COALESCE(c.DESCRICAO, '')
  END CANCELAMENTO
, o.ALTERNATIVA_PECA ALTERNATIVA
, o.ROTEIRO_PECA ROTEIRO
, o.REFERENCIA_PECA REF
, COALESCE(
  CASE WHEN o.REFERENCIA_PECA < 'C0000' THEN
    CAST( CAST( regexp_replace(o.REFERENCIA_PECA, '[^0-9]', '')
                AS INTEGER ) AS VARCHAR2(5) )
  ELSE
    ( SELECT
        CAST( MAX(
          CASE WHEN ec.GRUPO_ITEM IS NULL THEN 0
          ELSE CAST( regexp_replace(ec.GRUPO_ITEM, '[^0-9]', '')
                     AS INTEGER )
          END
        ) AS VARCHAR2(5) )
        FROM BASI_050 ec
        JOIN BASI_030 rr
          ON rr.NIVEL_ESTRUTURA = ec.NIVEL_ITEM
         AND rr.REFERENCIA = ec.GRUPO_ITEM
         AND rr.RESPONSAVEL IS NOT NULL
        WHERE ec.NIVEL_COMP = 1
          AND ec.GRUPO_COMP = o.REFERENCIA_PECA
    )
  END
  , ' ' ) MODELO
, ( SELECT
      COUNT( DISTINCT l.ORDEM_CONFECCAO )
    FROM pcpc_040 l
    WHERE l.ORDEM_PRODUCAO = o.ORDEM_PRODUCAO
  ) LOTES
, ( SELECT
      SUM( l.QTDE_PECAS_PROG )
    FROM pcpc_040 l
    WHERE l.ORDEM_PRODUCAO = o.ORDEM_PRODUCAO
      AND l.SEQ_OPERACAO = (
        SELECT
          MAX( ls.SEQ_OPERACAO )
        FROM pcpc_040 ls
        WHERE ls.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
      )
  ) QTD
, o.DATA_PROGRAMACAO DT_DIGITACAO
, o.DATA_ENTRADA_CORTE DT_CORTE
, o.PERIODO_PRODUCAO PERIODO
, p.DATA_INI_PERIODO PERIODO_INI
, p.DATA_FIM_PERIODO PERIODO_FIM
, o.DEPOSITO_ENTRADA || ' - ' || d.DESCRICAO DEPOSITO
, o.PEDIDO_VENDA PEDIDO
, COALESCE(ped.COD_PED_CLIENTE, '') PED_CLIENTE
FROM PCPC_020 o
JOIN PCPC_010 p
  ON p.AREA_PERIODO = 1
 AND p.PERIODO_PRODUCAO = o.PERIODO_PRODUCAO
LEFT JOIN pcpt_050 c
  ON c.COD_CANCELAMENTO = o.COD_CANCELAMENTO
LEFT JOIN PCPC_020 ofi
  ON ofi.ORDEM_PRINCIPAL = o.ORDEM_PRODUCAO
JOIN BASI_205 d
  ON d.CODIGO_DEPOSITO = o.DEPOSITO_ENTRADA
LEFT JOIN PEDI_100 ped -- pedido de venda
  ON ped.PEDIDO_VENDA = o.PEDIDO_VENDA
WHERE o.ORDEM_PRODUCAO = 1900
;

SELECT
  l.ORDEM_PRODUCAO OP
, count(l.ORDEM_CONFECCAO) LOTES
, sum(l.QTDE_PECAS_PROG) QTD
, o.PEDIDO_VENDA PEDIDO
, COALESCE(ped.COD_PED_CLIENTE, '') PED_CLIENTE
FROM pcpc_040 l -- lotes
JOIN PCPC_020 o -- OP
  ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
LEFT JOIN PEDI_100 ped -- pedido de venda
  ON ped.PEDIDO_VENDA = o.PEDIDO_VENDA
WHERE l.NUMERO_ORDEM = 996
GROUP BY
  l.ORDEM_PRODUCAO
, o.PEDIDO_VENDA
, ped.COD_PED_CLIENTE
;

SELECT
  ped.PEDIDO_VENDA
, ped.DATA_EMIS_VENDA DT_EMISSAO
, ped.DATA_PREV_RECEB DT_RECEBIMENTO
, c.NOME_CLIENTE || ' (' || lpad(c.CGC_9, 8, '0') || '/' || lpad(c.CGC_4, 4, '0') || '-' || lpad(c.CGC_2, 2, '0') || ')' CLIENTE
, COALESCE(ped.COD_PED_CLIENTE, '') PEDIDO_CLIENTE
, CASE ped.STATUS_PEDIDO
  WHEN 0 THEN '0-Digitado'
  WHEN 1 THEN '1-Financeiro'
  WHEN 2 THEN '2-Liberado Financeiro'
  WHEN 3 THEN '3-Faturamento'
  WHEN 4 THEN '4-A cancelar'
  WHEN 5 THEN '5-Cancelado'
  WHEN 9 THEN '9-Aberto na web'
  END STATUS_PEDIDO
, CASE ped.SITUACAO_VENDA
  WHEN 0  THEN '0-Pedido liberado'
  WHEN 5  THEN '5-Pedido suspenso'
  WHEN 10 THEN '10-Faturado total'
  WHEN 15 THEN '15-Pedido com NF cancelada'
  END SITUACAO_VENDA
, ped.*
FROM PEDI_100 ped -- pedido de venda
LEFT JOIN PEDI_010 c
  ON c.CGC_9 = ped.CLI_PED_CGC_CLI9
 AND c.CGC_4 = ped.CLI_PED_CGC_CLI4
WHERE ped.PEDIDO_VENDA = 2138
;

SELECT DISTINCT
  ped.SITUACAO_VENDA
, ped.PEDIDO_VENDA
FROM PEDI_100 ped -- pedido de venda
WHERE ped.SITUACAO_VENDA = 5
;

SELECT
  e.CODIGO_ESTAGIO
, e.CODIGO_ESTAGIO || ' - ' || e.DESCRICAO ESTAGIO
, l.PERIODO_PRODUCAO PERIODO
, p.DATA_INI_PERIODO DATA_INI
, p.DATA_FIM_PERIODO DATA_FIM
, l.PROCONF_GRUPO REF
--, r.DESCR_REFERENCIA
, r.COLECAO || ' - ' || c.DESCR_COLECAO COLECAO
, l.ORDEM_PRODUCAO OP
, l.SEQ_OPERACAO SEQ
, o.DATA_ENTRADA_CORTE DT_CORTE
, SUM( l.QTDE_PECAS_PROG - l.QTDE_PECAS_PROD) QTD
, COUNT(*) LOTES
FROM MQOP_005 e
JOIN PCPC_040 l
  ON l.CODIGO_ESTAGIO = e.CODIGO_ESTAGIO
JOIN BASI_030 r -- cadastro de produtos
  ON r.NIVEL_ESTRUTURA = l.PROCONF_NIVEL99
 AND r.REFERENCIA = l.PROCONF_GRUPO
JOIN BASI_140 c -- cadastro de coleções de produtos
  ON c.COLECAO = r.COLECAO
JOIN PCPC_020 o
  ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
JOIN PCPC_010 p
  ON p.AREA_PERIODO = 1
 AND p.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
WHERE l.QTDE_EM_PRODUCAO_PACOTE <> 0
  AND o.SITUACAO = 4 -- Ordens em produção
  AND ( e.CODIGO_ESTAGIO = 6 )
GROUP BY
  e.CODIGO_ESTAGIO
, e.DESCRICAO
, l.PERIODO_PRODUCAO
, p.DATA_INI_PERIODO
, p.DATA_FIM_PERIODO
, l.PROCONF_GRUPO
, l.ORDEM_PRODUCAO
, l.SEQ_OPERACAO
, o.DATA_ENTRADA_CORTE
, r.DESCR_REFERENCIA
, r.COLECAO
, c.DESCR_COLECAO
ORDER BY
  e.CODIGO_ESTAGIO
, l.PERIODO_PRODUCAO
, r.COLECAO
, l.PROCONF_GRUPO
, l.ORDEM_PRODUCAO
;

SELECT
  c.*
FROM BASI_140 c -- cadastro de coleções de produtos
;

SELECT
  case
  when o.REFERENCIA_PECA <= '99999' then 'PA'
  when o.REFERENCIA_PECA <= 'B9999' then 'PG'
  else 'MD'
  end TIPO_REF
, CASE
  WHEN o.ORDEM_PRINCIPAL <> 0 THEN 'Filha de'
  WHEN (
    SELECT
      count(ofi.ORDEM_PRODUCAO)
    FROM PCPC_020 ofi
    WHERE ofi.ORDEM_PRINCIPAL = o.ORDEM_PRODUCAO
  ) > 0 THEN 'Mãe de'
  ELSE 'Avulsa'
  END TIPO_OP
, coalesce((
    SELECT
      LISTAGG(ofi.ORDEM_PRODUCAO, ', ')
      WITHIN GROUP (ORDER BY ofi.ORDEM_PRODUCAO)
    FROM PCPC_020 ofi
    WHERE ofi.ORDEM_PRINCIPAL = o.ORDEM_PRODUCAO
    )
  , cast(o.ORDEM_PRINCIPAL AS varchar2(9))) OP_REL
, o.SITUACAO ||
  CASE
  WHEN o.SITUACAO = 2 THEN '-Ordem conf. gerada'
  WHEN o.SITUACAO = 4 THEN '-Ordens em produção'
  WHEN o.SITUACAO = 9 THEN '-Ordem cancelada'
  ELSE ' '
  END SITUACAO
, o.COD_CANCELAMENTO ||
  CASE
  WHEN o.COD_CANCELAMENTO = 0 THEN ''
  ELSE '-' || COALESCE(c.DESCRICAO, '')
  END CANCELAMENTO
, o.ALTERNATIVA_PECA ALTERNATIVA
, o.ROTEIRO_PECA ROTEIRO
, o.REFERENCIA_PECA REF
, COALESCE(
  CASE WHEN o.REFERENCIA_PECA < 'C0000' THEN
    CAST( CAST( regexp_replace(o.REFERENCIA_PECA, '[^0-9]', '')
                AS INTEGER ) AS VARCHAR2(5) )
  ELSE
    ( SELECT
        CAST( MAX(
          CASE WHEN ec.GRUPO_ITEM IS NULL THEN 0
          ELSE CAST( regexp_replace(ec.GRUPO_ITEM, '[^0-9]', '')
                     AS INTEGER )
          END
        ) AS VARCHAR2(5) )
        FROM BASI_050 ec
        JOIN BASI_030 rr
          ON rr.NIVEL_ESTRUTURA = ec.NIVEL_ITEM
         AND rr.REFERENCIA = ec.GRUPO_ITEM
         AND rr.RESPONSAVEL IS NOT NULL
        WHERE ec.NIVEL_COMP = 1
          AND ec.GRUPO_COMP = o.REFERENCIA_PECA
    )
  END
  , ' ' ) MODELO
, ( SELECT
      COUNT( DISTINCT l.ORDEM_CONFECCAO )
    FROM pcpc_040 l
    WHERE l.ORDEM_PRODUCAO = o.ORDEM_PRODUCAO
  ) LOTES
, ( SELECT
      SUM( l.QTDE_PECAS_PROG )
    FROM pcpc_040 l
    WHERE l.ORDEM_PRODUCAO = o.ORDEM_PRODUCAO
      AND l.SEQ_OPERACAO = (
        SELECT
          MAX( ls.SEQ_OPERACAO )
        FROM pcpc_040 ls
        WHERE ls.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
      )
  ) QTD
, o.DATA_PROGRAMACAO DT_DIGITACAO
, o.DATA_ENTRADA_CORTE DT_CORTE
, o.PERIODO_PRODUCAO PERIODO
, p.DATA_INI_PERIODO PERIODO_INI
, p.DATA_FIM_PERIODO PERIODO_FIM
, o.DEPOSITO_ENTRADA || ' - ' || d.DESCRICAO DEPOSITO
, o.PEDIDO_VENDA PEDIDO
, COALESCE(ped.COD_PED_CLIENTE, ' ') PED_CLIENTE
FROM PCPC_020 o
JOIN PCPC_010 p
  ON p.AREA_PERIODO = 1
 AND p.PERIODO_PRODUCAO = o.PERIODO_PRODUCAO
LEFT JOIN pcpt_050 c
  ON c.COD_CANCELAMENTO = o.COD_CANCELAMENTO
JOIN BASI_205 d
  ON d.CODIGO_DEPOSITO = o.DEPOSITO_ENTRADA
LEFT JOIN PEDI_100 ped -- pedido de venda
  ON ped.PEDIDO_VENDA = o.PEDIDO_VENDA
WHERE o.ORDEM_PRODUCAO = 3753
;

SELECT
  f.NUM_NOTA_FISCAL NF
, f.BASE_ICMS VALOR
, f.QTDE_EMBALAGENS VOLUMES
, f.DATA_AUTORIZACAO_NFE FATURAMENTO
, CAST( COALESCE( '0' || f.COD_STATUS, '0' ) AS INT ) COD_STATUS
, COALESCE( f.MSG_STATUS, ' ' ) MSG_STATUS
, f.SITUACAO_NFISC SITUACAO
, f.NATOP_NF_NAT_OPER NAT
, f.NATOP_NF_EST_OPER UF
, n.DESCR_NAT_OPER NATUREZA
, f.CGC_9 CNPJ9
, f.CGC_4 CNPJ4
, f.CGC_2 CNPJ2
, c.NOME_CLIENTE CLIENTE
, COALESCE(
    CASE WHEN f.TRANSPOR_FORNE9
            + f.TRANSPOR_FORNE4
            + f.TRANSPOR_FORNE2 = 0
    THEN 'O PROPRIO'
    ELSE t.NOME_FANTASIA
    END
  , '-') TRANSP
FROM FATU_050 f
JOIN PEDI_010 c
  ON c.CGC_9 = f.CGC_9
 AND c.CGC_4 = f.CGC_4
 AND c.CGC_2 = f.CGC_2
JOIN PEDI_080 n
  ON n.NATUR_OPERACAO = f.NATOP_NF_NAT_OPER
 AND n.ESTADO_NATOPER = f.NATOP_NF_EST_OPER
LEFT JOIN SUPR_010 t
  ON t.TIPO_FORNECEDOR = 31 -- transportadora
 AND t.FORNECEDOR9 = f.TRANSPOR_FORNE9
 AND t.FORNECEDOR4 = f.TRANSPOR_FORNE4
 AND t.FORNECEDOR2 = f.TRANSPOR_FORNE2
--WHERE rownum = 1
--WHERE CAST( COALESCE( '0' || f.COD_STATUS, '0' ) AS INT ) = 0
ORDER BY
  f.NUM_NOTA_FISCAL DESC
;

SELECT
  ptc.GRUPO_ESTRUTURA REF
, ptc.SUBGRU_ESTRUTURA TAM
, ptc.ITEM_ESTRUTURA COR
FROM basi_010 ptc
WHERE ptc.NIVEL_ESTRUTURA = 1
  AND (  ptc.PRECO_MEDIO IS NULL
      OR ptc.PRECO_MEDIO = 0
      )
;

SELECT
  p.AREA_PERIODO
, p.PERIODO_PRODUCAO
, p.*
FROM PCPC_010 p
ORDER BY
  p.PERIODO_PRODUCAO
;

SELECT
  r.COD_REP_CLIENTE
FROM PEDI_020 R
WHERE r.COD_REP_CLIENTE <> 0
;

SELECT
  p.*
FROM PCPC_010 p
WHERE p.PERIODO_PRODUCAO > 1700
--  AND p.PERIODO_PRODUCAO < 1800
  AND p.AREA_PERIODO = 8
;

SELECT
  p.PERIODO_PRODUCAO
, 0
, r.COD_REP_CLIENTE
, 1
, 40000
, 1
, 0
, 0
, 0
, 0
FROM PCPC_010 p, PEDI_020 R
WHERE r.COD_REP_CLIENTE <> 0
  AND p.PERIODO_PRODUCAO > 1700
  AND p.PERIODO_PRODUCAO < 1800
  AND p.AREA_PERIODO = 8
  AND NOT (p.PERIODO_PRODUCAO = 1701 AND r.COD_REP_CLIENTE = 4)
  AND NOT (p.PERIODO_PRODUCAO = 1702 AND r.COD_REP_CLIENTE = 4)
  AND NOT (p.PERIODO_PRODUCAO = 1703 AND r.COD_REP_CLIENTE = 4)
;

SELECT
  p.*
FROM PCPC_010 p
WHERE p.PERIODO_PRODUCAO > 1700
--  AND p.PERIODO_PRODUCAO < 1800
  AND p.AREA_PERIODO = 8
;

--------------------
--------------------
--------------------
--------------------
--------------------
--------------------
--------------------
--------------------
--------------------
--------------------
--------------------

SELECT
  s.PRODSAI_NIVEL99 NIVEL
, s.PRODSAI_GRUPO REF
, s.PRODSAI_ITEM COR
, s.PRODSAI_SUBGRUPO TAM
, i.NARRATIVA
, r.UNIDADE_MEDIDA UN
, s.VALOR_PRODUTO VALOR_UN
, s.QTDE_ESTRUTURA QTD_ESTR
, s.QTDE_ENVIADA QTD_ENV
, s.NUM_NF_SAI NF
FROM OBRF_082 s
JOIN BASI_010 i
  ON i.NIVEL_ESTRUTURA = s.PRODSAI_NIVEL99
 AND i.GRUPO_ESTRUTURA = s.PRODSAI_GRUPO
 AND i.SUBGRU_ESTRUTURA = s.PRODSAI_SUBGRUPO
 AND i.ITEM_ESTRUTURA = s.PRODSAI_ITEM
JOIN BASI_030 r
  ON r.NIVEL_ESTRUTURA = s.PRODSAI_NIVEL99
 AND r.REFERENCIA = s.PRODSAI_GRUPO
LEFT JOIN BASI_220 tam
  ON tam.TAMANHO_REF = s.PRODSAI_SUBGRUPO
WHERE s.NUMERO_ORDEM = 589
ORDER BY
  s.PRODSAI_NIVEL99
, s.PRODSAI_GRUPO
, s.PRODSAI_ITEM
, tam.ORDEM_TAMANHO
;

        SELECT
          case
          when o.REFERENCIA_PECA <= '99999' then 'PA'
          when o.REFERENCIA_PECA <= 'A9999' then 'PG'
          else 'MD'
          end TIPO_REF
        , CASE
          WHEN o.ORDEM_PRINCIPAL <> 0 THEN 'Filha de'
          WHEN ofi.ORDEM_PRODUCAO IS NOT NULL THEN 'Mãe de'
          ELSE 'Avulsa'
          END TIPO_OP
        , coalesce( ofi.ORDEM_PRODUCAO, o.ORDEM_PRINCIPAL ) OP_REL
        , o.SITUACAO ||
          CASE
          WHEN o.SITUACAO = 2 THEN '-Ordem conf. gerada'
          WHEN o.SITUACAO = 4 THEN '-Ordens em produção'
          WHEN o.SITUACAO = 9 THEN '-Ordem cancelada'
          ELSE ' '
          END SITUACAO
        , o.COD_CANCELAMENTO ||
          CASE
          WHEN o.COD_CANCELAMENTO = 0 THEN ''
          ELSE '-' || c.DESCRICAO
          END CANCELAMENTO
        , o.ALTERNATIVA_PECA ALTERNATIVA
        , o.ROTEIRO_PECA ROTEIRO
        , o.REFERENCIA_PECA REF
        , ( SELECT
              COUNT( DISTINCT l.ORDEM_CONFECCAO )
            FROM pcpc_040 l
            WHERE l.ORDEM_PRODUCAO = o.ORDEM_PRODUCAO
          ) LOTES
        , ( SELECT
              SUM( l.QTDE_PECAS_PROG )
            FROM pcpc_040 l
            WHERE l.ORDEM_PRODUCAO = o.ORDEM_PRODUCAO
              AND l.SEQ_OPERACAO = (
                SELECT
                  MAX( ls.SEQ_OPERACAO )
                FROM pcpc_040 ls
                WHERE ls.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
              )
          ) QTD
        , o.DATA_PROGRAMACAO DT_DIGITACAO
        , o.DATA_ENTRADA_CORTE DT_CORTE
        , o.PERIODO_PRODUCAO PERIODO
        , p.DATA_INI_PERIODO PERIODO_INI
        , p.DATA_FIM_PERIODO PERIODO_FIM
        FROM PCPC_020 o
        JOIN PCPC_010 p
          ON p.AREA_PERIODO = 1
         AND p.PERIODO_PRODUCAO = o.PERIODO_PRODUCAO
        JOIN pcpt_050 c
          ON c.COD_CANCELAMENTO = o.COD_CANCELAMENTO
        LEFT JOIN PCPC_020 ofi
          ON ofi.ORDEM_PRINCIPAL = o.ORDEM_PRODUCAO
        WHERE o.ORDEM_PRODUCAO = 829
;

SELECT
  p.*
FROM PCPC_010 p
WHERE p.PERIODO_PRODUCAO = 1729
;

SELECT
  i.*
FROM BASI_010 i
WHERE i.GRUPO_ESTRUTURA IN ('503ME', '00620')
;

SELECT
  i.*
FROM BASI_020 i
WHERE i.BASI030_REFERENC IN ('503ME', '00620')
;

SELECT
  i.*
FROM BASI_030 i
WHERE i.REFERENCIA IN ('503ME', '00620')
;

SELECT
  i.*
FROM BASI_015 i
--WHERE i.GRUPO_ESTRUTURA IN ('503ME', '00620')
;


SELECT
  l.ORDEM_PRODUCAO
, l.NUMERO_ORDEM
, l.SEQ_ORDEM_SERV
, l.PERIODO_PRODUCAO
, l.ORDEM_CONFECCAO
, l.*
FROM pcpc_040 l


SELECT DISTINCT
  l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
, sum(l.QTDE_PROGRAMADA) qtde
FROM pcpc_040 l


UPDATE pcpc_040 l
SET
  l.NUMERO_ORDEM = 0
, l.SEQ_ORDEM_SERV = 0
WHERE 1=1
  --AND l.ORDEM_PRODUCAO = 297
  AND l.NUMERO_ORDEM = 618
  --AND l.CODIGO_ESTAGIO = 39
  AND l.PERIODO_PRODUCAO = 1728
  AND l.ORDEM_CONFECCAO IN (
    5970
  , 5962
  , 6145
  , 6146
  , 6148
  , 6149
  , 6357
  , 6358
  , 6360
  , 6364
  , 6361
  , 6365
  , 6368
  , 6369
  , 6370
  , 6092
  , 6094
  , 6096
  , 6101
  , 6102
  , 6104
  , 6007
  , 6105
  , 6107
  , 6400
  , 6406
  , 6407
  , 6408
  , 6410
  , 6412
  , 6414
  , 6137
  , 6138
  , 6141
  )
  AND l.NUMERO_ORDEM <> 0
  AND l.SEQ_ORDEM_SERV <> 0
;

GROUP BY
  l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
;

SELECT
  l.PERIODO_PRODUCAO PERIODO
, p.DATA_INI_PERIODO PERIODO_INI
, p.DATA_FIM_PERIODO PERIODO_FIM
, o.ALTERNATIVA_PECA || '/' || o.ROTEIRO_PECA ALT
, CASE
  WHEN l.PROCONF_GRUPO <= '99999' THEN 'MD'
  WHEN l.PROCONF_GRUPO > 'A9999' THEN 'PA'
  ELSE 'PG'
  END TIPO
, CASE
  WHEN l.PROCONF_GRUPO <= '99999' THEN 3
  WHEN l.PROCONF_GRUPO > 'A9999' THEN 1
  ELSE 2
  END TIPO_ORDEM
, o.DATA_ENTRADA_CORTE DATA_CORTE
, SUM( l.QTDE_PECAS_PROG ) QTD
FROM pcpc_040 l
JOIN PCPC_020 o
  ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
JOIN PCPC_010 p
  ON p.AREA_PERIODO = 1
 AND p.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
WHERE l.PROCONF_NIVEL99 = 1
  --AND l.PERIODO_PRODUCAO = 1728
  --AND p.DATA_INI_PERIODO <= CURRENT_DATE
  --AND p.DATA_FIM_PERIODO >= CURRENT_DATE
  AND o.DATA_ENTRADA_CORTE = TO_DATE('01-08-2017','dd-MM-yyyy')
  AND l.SEQ_OPERACAO = (
    SELECT
      MAX( ls.SEQ_OPERACAO )
    FROM pcpc_040 ls
    WHERE ls.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
  )
GROUP BY
  l.PERIODO_PRODUCAO
, p.DATA_INI_PERIODO
, p.DATA_FIM_PERIODO
, o.ALTERNATIVA_PECA
, o.ROTEIRO_PECA
, CASE
  WHEN l.PROCONF_GRUPO <= '99999' THEN 'MD'
  WHEN l.PROCONF_GRUPO > 'A9999' THEN 'PA'
  ELSE 'PG'
  END
, CASE
  WHEN l.PROCONF_GRUPO <= '99999' THEN 3
  WHEN l.PROCONF_GRUPO > 'A9999' THEN 1
  ELSE 2
  END
, o.DATA_ENTRADA_CORTE
ORDER BY
  l.PERIODO_PRODUCAO
, o.ALTERNATIVA_PECA
, o.ROTEIRO_PECA
, 4
, o.DATA_ENTRADA_CORTE
;

  sum(l.QTDE_PECAS_PROG) QTDE_PECAS_PROG
, sum(l.QTDE_PROGRAMADA) QTDE_PROGRAMADA

SELECT DISTINCT
  l.PERIODO_PRODUCAO
, l.ORDEM_CONFECCAO
, l.QTDE_PECAS_PROG
, l.QTDE_PROGRAMADA
FROM PCPC_040 l
WHERE l.ORDEM_PRODUCAO = 1191
  --AND l.PERIODO_PRODUCAO = 1728
  --AND l.ORDEM_CONFECCAO = 5509
  AND l.QTDE_PECAS_PROG <> l.QTDE_PROGRAMADA
ORDER BY
  l.ORDEM_CONFECCAO
;


SELECT DISTINCT
  l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
, sum(l.QTDE_PECAS_PROG) qtde
FROM pcpc_040 l
WHERE l.NUMERO_ORDEM = 618
GROUP BY
  l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
;

SELECT
  p.PERIODO_PRODUCAO
, p.DATA_INI_PERIODO PERIODO_INI
, p.DATA_FIM_PERIODO PERIODO_FIM
FROM PCPC_010 p
WHERE p.AREA_PERIODO = 1
  --AND p.PERIODO_PRODUCAO = 1728
  AND p.DATA_INI_PERIODO <= CURRENT_DATE
  AND p.DATA_FIM_PERIODO >= CURRENT_DATE
;

SELECT
  p.DATA_INI_PERIODO+6 fim
, p.*
FROM PCPC_010 p

UPDATE PCPC_010 p
SET
  p.DATA_FIM_PERIODO = p.DATA_INI_PERIODO + 6
WHERE p.AREA_PERIODO = 1
;

ORDER BY
  p.PERIODO_PRODUCAO
;

SELECT
  p.DATA_INI_PERIODO+6 fim
, p.*
FROM PCPC_010 p
WHERE p.AREA_PERIODO = 1
ORDER BY
  p.PERIODO_PRODUCAO
;

SELECT
  pp.PERIODO_PRODUCAO PERIODO
, p.DATA_INI_PERIODO PERIODO_INI
, p.DATA_FIM_PERIODO PERIODO_FIM
, pp.ALTERNATIVA_PECA || '/' || pp.ROTEIRO_PECA ALT
, pp.TIPO_ORDEM
, CASE
  WHEN pp.TIPO_ORDEM = 3 THEN 'MD'
  WHEN pp.TIPO_ORDEM = 1 THEN 'PA'
  ELSE 'PG'
  END TIPO
, pp.DATA_ENTRADA_CORTE
, CASE WHEN pp.DATA_ENTRADA_CORTE = (CURRENT_DATE - 100000) THEN 1
  ELSE 2
  END ORDEM_TOTAL
, SUM( l.QTDE_PECAS_PROG ) QTD
, count(DISTINCT o.ORDEM_PRODUCAO) NUM_OPS
FROM
(
SELECT distinct
  l.PERIODO_PRODUCAO
, o.ALTERNATIVA_PECA
, o.ROTEIRO_PECA
, CASE
  WHEN l.PROCONF_GRUPO <= '99999' THEN 3
  WHEN l.PROCONF_GRUPO > 'A9999' THEN 1
  ELSE 2
  END TIPO_ORDEM
, CURRENT_DATE - 100000 DATA_ENTRADA_CORTE
FROM pcpc_040 l
JOIN PCPC_020 o
  ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
WHERE l.PROCONF_NIVEL99 = 1
  AND l.PERIODO_PRODUCAO >= 1732
  AND l.PERIODO_PRODUCAO <= 1732
UNION
SELECT distinct
  l.PERIODO_PRODUCAO
, o.ALTERNATIVA_PECA
, o.ROTEIRO_PECA
, CASE
  WHEN l.PROCONF_GRUPO <= '99999' THEN 3
  WHEN l.PROCONF_GRUPO > 'A9999' THEN 1
  ELSE 2
  END TIPO_ORDEM
, o.DATA_ENTRADA_CORTE
FROM pcpc_040 l
JOIN PCPC_020 o
  ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
WHERE l.PROCONF_NIVEL99 = 1
  AND l.PERIODO_PRODUCAO >= 1732
  AND l.PERIODO_PRODUCAO <= 1732
) pp
JOIN pcpc_040 l
  ON l.PERIODO_PRODUCAO = pp.PERIODO_PRODUCAO
JOIN PCPC_020 o
  ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
JOIN PCPC_010 p
  ON p.AREA_PERIODO = 1
 AND p.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
WHERE l.PROCONF_NIVEL99 = 1
  AND o.ALTERNATIVA_PECA = pp.ALTERNATIVA_PECA
  AND o.ROTEIRO_PECA = pp.ROTEIRO_PECA
  AND (  ( pp.TIPO_ORDEM = 3 AND l.PROCONF_GRUPO <= '99999')
      OR ( pp.TIPO_ORDEM = 1 AND l.PROCONF_GRUPO > 'A9999')
      OR ( pp.TIPO_ORDEM = 2 AND l.PROCONF_GRUPO LIKE 'A%')
      )
  AND ( pp.DATA_ENTRADA_CORTE = (CURRENT_DATE - 100000)
      OR ( pp.DATA_ENTRADA_CORTE IS NULL AND o.DATA_ENTRADA_CORTE IS NULL)
      OR ( pp.DATA_ENTRADA_CORTE <> (CURRENT_DATE - 100000) AND o.DATA_ENTRADA_CORTE = pp.DATA_ENTRADA_CORTE)
      )
GROUP BY
  pp.PERIODO_PRODUCAO
, p.DATA_INI_PERIODO
, p.DATA_FIM_PERIODO
, pp.ALTERNATIVA_PECA
, pp.ROTEIRO_PECA
, pp.TIPO_ORDEM
, pp.DATA_ENTRADA_CORTE
ORDER BY
  pp.PERIODO_PRODUCAO
, pp.ALTERNATIVA_PECA
, pp.ROTEIRO_PECA
, pp.TIPO_ORDEM
, pp.DATA_ENTRADA_CORTE
;

        SELECT
          pp.PERIODO_PRODUCAO PERIODO
        , p.DATA_INI_PERIODO PERIODO_INI
        , p.DATA_FIM_PERIODO PERIODO_FIM
        , pp.ALTERNATIVA_PECA || '/' || pp.ROTEIRO_PECA ALT
        , pp.TIPO_ORDEM
        , CASE
          WHEN pp.TIPO_ORDEM = 3 THEN 'MD'
          WHEN pp.TIPO_ORDEM = 1 THEN 'PA'
          ELSE 'PG'
          END TIPO
        , pp.DATA_ENTRADA_CORTE DATA_CORTE
        , CASE WHEN pp.PERIODO_PRODUCAO = -1 THEN 1
          ELSE 2
          END ORDEM_TOTAL
        , SUM( l.QTDE_PECAS_PROG ) QTD
        , COUNT(DISTINCT o.ORDEM_PRODUCAO) NUM_OPS
        , pp.OPS
        FROM
        (
        SELECT distinct
          -1 PERIODO_PRODUCAO
        , o.ALTERNATIVA_PECA
        , o.ROTEIRO_PECA
        , CASE
          WHEN l.PROCONF_GRUPO <= '99999' THEN 3
          WHEN l.PROCONF_GRUPO > 'A9999' THEN 1
          ELSE 2
          END TIPO_ORDEM
        , DATA_ENTRADA_CORTE
        , '' OPS
        FROM pcpc_040 l
        JOIN PCPC_020 o
          ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
        WHERE l.PROCONF_NIVEL99 = 1
          AND o.SITUACAO IN (2, 4)
          AND o.DATA_ENTRADA_CORTE >= CURRENT_DATE+2
          AND o.DATA_ENTRADA_CORTE <= CURRENT_DATE+3
        UNION
		SELECT
		  p1.*
        , LISTAGG(o1.ORDEM_PRODUCAO, ', ')
          WITHIN GROUP (ORDER BY o1.ORDEM_PRODUCAO) OPS
		FROM
		(
        SELECT distinct
          l.PERIODO_PRODUCAO
        , o.ALTERNATIVA_PECA
        , o.ROTEIRO_PECA
        , CASE
          WHEN l.PROCONF_GRUPO <= '99999' THEN 3
          WHEN l.PROCONF_GRUPO > 'A9999' THEN 1
          ELSE 2
          END TIPO_ORDEM
        , o.DATA_ENTRADA_CORTE
        FROM pcpc_040 l
        JOIN PCPC_020 o
          ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
        WHERE l.PROCONF_NIVEL99 = 1
          AND o.SITUACAO IN (2, 4)
          AND o.DATA_ENTRADA_CORTE >= CURRENT_DATE+2
          AND o.DATA_ENTRADA_CORTE <= CURRENT_DATE+3
		) p1
        JOIN PCPC_020 o1
          ON o1.DATA_ENTRADA_CORTE = p1.DATA_ENTRADA_CORTE
         AND o1.PERIODO_PRODUCAO = p1.PERIODO_PRODUCAO
         AND o1.SITUACAO IN (2, 4)
         AND o1.ALTERNATIVA_PECA = p1.ALTERNATIVA_PECA
         AND o1.ROTEIRO_PECA = p1.ROTEIRO_PECA
         AND (  ( p1.TIPO_ORDEM = 3 AND o1.REFERENCIA_PECA <= '99999')
             OR ( p1.TIPO_ORDEM = 1 AND o1.REFERENCIA_PECA > 'A9999')
             OR ( p1.TIPO_ORDEM = 2 AND o1.REFERENCIA_PECA LIKE 'A')
             )
        GROUP BY
          p1.PERIODO_PRODUCAO
        , p1.ALTERNATIVA_PECA
        , p1.ROTEIRO_PECA
        , p1.TIPO_ORDEM
        , p1.DATA_ENTRADA_CORTE
        ) pp
        JOIN PCPC_020 o
          ON o.DATA_ENTRADA_CORTE = pp.DATA_ENTRADA_CORTE
         AND ( pp.PERIODO_PRODUCAO = -1
             OR ( pp.PERIODO_PRODUCAO <> -1
                AND o.PERIODO_PRODUCAO = pp.PERIODO_PRODUCAO)
             )
        JOIN pcpc_040 l
          ON l.ORDEM_PRODUCAO = o.ORDEM_PRODUCAO
        LEFT JOIN PCPC_010 p
          ON p.AREA_PERIODO = 1
         AND p.PERIODO_PRODUCAO = pp.PERIODO_PRODUCAO
        WHERE l.PROCONF_NIVEL99 = 1
          AND o.SITUACAO IN (2, 4)
          AND o.ALTERNATIVA_PECA = pp.ALTERNATIVA_PECA
          AND o.ROTEIRO_PECA = pp.ROTEIRO_PECA
          AND (  ( pp.TIPO_ORDEM = 3 AND l.PROCONF_GRUPO <= '99999')
              OR ( pp.TIPO_ORDEM = 1 AND l.PROCONF_GRUPO > 'A9999')
              OR ( pp.TIPO_ORDEM = 2 AND l.PROCONF_GRUPO LIKE 'A')
              )
          AND l.SEQ_OPERACAO = (
            SELECT
              MAX( ls.SEQ_OPERACAO )
            FROM pcpc_040 ls
            WHERE ls.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
          )
        GROUP BY
          pp.DATA_ENTRADA_CORTE
        , pp.ALTERNATIVA_PECA
        , pp.ROTEIRO_PECA
        , pp.TIPO_ORDEM
        , pp.PERIODO_PRODUCAO
        , p.DATA_INI_PERIODO
        , p.DATA_FIM_PERIODO
        , pp.OPS
        ORDER BY
          pp.DATA_ENTRADA_CORTE
        , pp.ALTERNATIVA_PECA
        , pp.ROTEIRO_PECA
        , pp.TIPO_ORDEM
        , pp.PERIODO_PRODUCAO
;


        SELECT
          case
          when o.REFERENCIA_PECA <= '99999' then 'PA'
          when o.REFERENCIA_PECA <= 'A9999' then 'PG'
          else 'MD'
          end TIPO_REF
        , CASE
          WHEN o.ORDEM_PRINCIPAL <> 0 THEN 'Filha de'
          WHEN ofi.ORDEM_PRODUCAO IS NOT NULL THEN 'Mãe de'
          ELSE 'Avulsa'
          END TIPO_OP
        , coalesce( ofi.ORDEM_PRODUCAO, o.ORDEM_PRINCIPAL ) OP_REL
        , o.SITUACAO ||
          CASE
          WHEN o.SITUACAO = 2 THEN '-Ordem conf. gerada'
          WHEN o.SITUACAO = 4 THEN '-Ordens em produção'
          WHEN o.SITUACAO = 9 THEN '-Ordem cancelada'
          ELSE ' '
          END SITUACAO
        , o.COD_CANCELAMENTO ||
          CASE
          WHEN o.COD_CANCELAMENTO = 0 THEN ''
          ELSE '-' || coalesce(c.DESCRICAO, 'vazio')
          END CANCELAMENTO
        , o.ALTERNATIVA_PECA ALTERNATIVA
        , o.ROTEIRO_PECA ROTEIRO
        , o.REFERENCIA_PECA REF
        , ( SELECT
              COUNT( DISTINCT l.ORDEM_CONFECCAO )
            FROM pcpc_040 l
            WHERE l.ORDEM_PRODUCAO = o.ORDEM_PRODUCAO
          ) LOTES
        , ( SELECT
              SUM( l.QTDE_PECAS_PROG )
            FROM pcpc_040 l
            WHERE l.ORDEM_PRODUCAO = o.ORDEM_PRODUCAO
              AND l.SEQ_OPERACAO = (
                SELECT
                  MAX( ls.SEQ_OPERACAO )
                FROM pcpc_040 ls
                WHERE ls.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
              )
          ) QTD
        , o.DATA_PROGRAMACAO DT_DIGITACAO
        , o.DATA_ENTRADA_CORTE DT_CORTE
        , o.PERIODO_PRODUCAO PERIODO
        , p.DATA_INI_PERIODO PERIODO_INI
        , p.DATA_FIM_PERIODO PERIODO_FIM
        FROM PCPC_020 o
        JOIN PCPC_010 p
          ON p.AREA_PERIODO = 1
         AND p.PERIODO_PRODUCAO = o.PERIODO_PRODUCAO
        LEFT JOIN pcpt_050 c
          ON c.COD_CANCELAMENTO = o.COD_CANCELAMENTO
        LEFT JOIN PCPC_020 ofi
          ON ofi.ORDEM_PRINCIPAL = o.ORDEM_PRODUCAO
        WHERE o.ORDEM_PRODUCAO = 694
;

        SELECT
          l.ORDEM_PRODUCAO OP
        , CASE WHEN dos.NUMERO_ORDEM IS NULL
          THEN '0'
          ELSE l.NUMERO_ORDEM || ' (' || eos.DESCRICAO || ')'
          END OS
        , l.PROCONF_GRUPO REF
        , l.PROCONF_SUBGRUPO TAM
        , l.PROCONF_ITEM COR
        , COALESCE(
          ( SELECT
              LISTAGG(le.CODIGO_ESTAGIO || ' - ' || ed.DESCRICAO, ' & ')
              WITHIN GROUP (ORDER BY le.CODIGO_ESTAGIO)
            FROM PCPC_040 le
            JOIN MQOP_005 ed
              ON ed.CODIGO_ESTAGIO = le.CODIGO_ESTAGIO
            WHERE le.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
              AND le.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
              AND le.QTDE_EM_PRODUCAO_PACOTE <> 0
          )
          , 'FINALIZADO'
          ) EST
        , l.PERIODO_PRODUCAO PERIODO
        , l.ORDEM_CONFECCAO OC
        , l.QTDE_PECAS_PROG QTD
        FROM (
          SELECT
            os.PERIODO_PRODUCAO
          , os.ORDEM_CONFECCAO
          , os.PROCONF_GRUPO
          , os.PROCONF_SUBGRUPO
          , os.PROCONF_ITEM
          , os.ORDEM_PRODUCAO
          , max( os.NUMERO_ORDEM ) NUMERO_ORDEM
          , max( os.QTDE_PECAS_PROG ) QTDE_PECAS_PROG
          FROM PCPC_040 os
          WHERE 1=1
            AND (os.ORDEM_PRODUCAO = '694' or '694' IS NULL)
            AND (os.NUMERO_ORDEM = '' or '' IS NULL)
          GROUP BY
            os.PERIODO_PRODUCAO
          , os.ORDEM_CONFECCAO
          , os.PROCONF_GRUPO
          , os.PROCONF_SUBGRUPO
          , os.PROCONF_ITEM
          , os.ORDEM_PRODUCAO
        ) l
        LEFT JOIN PCPC_040 dos
          ON l.NUMERO_ORDEM <> 0
         AND dos.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
         AND dos.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
         AND dos.NUMERO_ORDEM = l.NUMERO_ORDEM
        LEFT JOIN MQOP_005 eos
          ON eos.CODIGO_ESTAGIO = dos.CODIGO_ESTAGIO
        LEFT JOIN BASI_220 t
          ON t.TAMANHO_REF = l.PROCONF_SUBGRUPO
        ORDER BY
          l.ORDEM_PRODUCAO
        , l.NUMERO_ORDEM
        , l.PROCONF_GRUPO
        , l.PROCONF_ITEM
        , t.ORDEM_TAMANHO
        , l.PERIODO_PRODUCAO
        , l.ORDEM_CONFECCAO
;

SELECT
  *
FROM pcpt_050
;

SELECT
  os.*
FROM OBRF_080 os
WHERE os.OBSERVACAO like '%TESTE%'
;

SELECT
  op.*
FROM PCPC_020 op
WHERE op.OBSERVACAO like '%ANSELMO%'
;

SELECT
  r.REFERENCIA
, r.DESCR_REFERENCIA
FROM basi_030 r
WHERE r.REFERENCIA = '00256'
;

SELECT DISTINCT
  c.ITEM_ESTRUTURA
, c.DESCRICAO_15
FROM basi_010 c
WHERE c.NIVEL_ESTRUTURA = 1
  AND c.GRUPO_ESTRUTURA = '00256'
;

SELECT DISTINCT
  t.TAMANHO_REF TAM
, t.DESCR_TAM_REFER DESCR
, tam.ORDEM_TAMANHO ORD
FROM basi_020 t
LEFT JOIN BASI_220 tam
  ON tam.TAMANHO_REF = t.TAMANHO_REF
WHERE t.BASI030_NIVEL030 = 1
  AND t.BASI030_REFERENC = '00256'
ORDER BY
  tam.ORDEM_TAMANHO
;

SELECT -- DISTINCT
  d.NUM_DUPLICATA
, d.SEQ_DUPLICATAS
, d.DUPLIC_EMITIDA
, d.NR_IDENTIFICACAO
, d.NUMERO_REMESSA
, d.DATA_EMISSAO
, d.*
FROM FATU_070 d
WHERE 1=1
  --AND d.NUM_DUPLICATA = 55802
  AND d.NR_IDENTIFICACAO = 1
  --AND d.NUMERO_REMESSA = 0
  AND d.DUPLIC_EMITIDA = 1
ORDER BY
  d.DATA_EMISSAO
, d.NUM_DUPLICATA
;


UPDATE FATU_070 d
SET
  d.NR_IDENTIFICACAO = 1
WHERE 1=1
  --AND d.NUM_DUPLICATA = 55802
  AND d.NR_IDENTIFICACAO = 0
  --AND d.NUMERO_REMESSA = 0
  AND d.DUPLIC_EMITIDA = 5
;

UPDATE FATU_070 d SET d.DUPLIC_EMITIDA = 1 WHERE d.NUM_DUPLICATA = 57819;
UPDATE FATU_070 d SET d.DUPLIC_EMITIDA = 1 WHERE d.NUM_DUPLICATA = 57819;
UPDATE FATU_070 d SET d.DUPLIC_EMITIDA = 1 WHERE d.NUM_DUPLICATA = 57819;
UPDATE FATU_070 d SET d.DUPLIC_EMITIDA = 1 WHERE d.NUM_DUPLICATA = 57819;


SELECT
  DISTINCT
  s.PRODSAI_NIVEL99
, s.PRODSAI_GRUPO
, s.PRODSAI_SUBGRUPO
, s.PRODSAI_ITEM
--, s.*

DELETE FROM OBRF_082 s
WHERE s.NUMERO_ORDEM = 747
  AND s.PRODSAI_GRUPO = 'M2556'
;

ORDER BY
  s.PRODSAI_NIVEL99
, s.PRODSAI_GRUPO
, s.PRODSAI_SUBGRUPO
, s.PRODSAI_ITEM
;

SELECT
  i.*
FROM FATU_060 i
WHERE i.CH_IT_NF_NUM_NFIS = 57158
;

SELECT
  n.SITUACAO_NFISC
, n.COD_CANC_NFISC
, n.*
FROM FATU_050 n
WHERE n.NUM_NOTA_FISCAL in (056384, 056394,  056435, 57158, 58428)
;

UPDATE FATU_050 n
SET
  n.SITUACAO_NFISC = 2
, n.COD_CANC_NFISC = 1
WHERE n.NUM_NOTA_FISCAL in (056384, 056394,  056435, 57158)
;

SELECT
  n.*
FROM FATU_050_HIST n
WHERE n.NUM_NOTA_FISCAL_NEW = 58428
ORDER BY
  n.DATA_OCORR
;

SELECT
  c.*
FROM BASI_140 c
;

SELECT
  r.*
FROM BASI_030 r
WHERE REFERENCIA = 'M0256'
;


SELECT
  r.REFERENCIA REF
, r.DESCR_REFERENCIA DESCR
--, ce.DESCR_CT_ESTOQUE
--  || ' (' || r.CONTA_ESTOQUE || ')' CONTA_ESTOQUE
--, lin.DESCRICAO_LINHA
--  || ' (' || r.LINHA_PRODUTO || ')' LINHA
--, col.DESCR_COLECAO
--  || ' (' || r.COLECAO || ')' COLECAO
--, ac.DESCR_ARTIGO
--  || ' (' || r.ARTIGO || ')' ARTIGO
, r.CLASSIFIC_FISCAL || ' - ' || cf.DESCR_CLASS_FISC NCM
, r.COLECAO_CLIENTE
, r.CGC_CLIENTE_9
, r.CGC_CLIENTE_4
, r.CGC_CLIENTE_2
, cl.NOME_CLIENTE
, r.RESPONSAVEL
FROM basi_030 r
JOIN BASI_150 ce
  ON ce.CONTA_ESTOQUE = r.CONTA_ESTOQUE
JOIN BASI_120 lin
  ON lin.NIVEL_ESTRUTURA = 1
 AND lin.LINHA_PRODUTO = r.LINHA_PRODUTO
JOIN BASI_140 col
  ON col.COLECAO = r.COLECAO
JOIN BASI_290 ac
  ON ac.NIVEL_ESTRUTURA = 1
 AND ac.ARTIGO = r.ARTIGO
JOIN BASI_240 cf
  ON cf.CLASSIFIC_FISCAL = r.CLASSIFIC_FISCAL
JOIN PEDI_010 cl
  ON cl.CGC_9 = r.CGC_CLIENTE_9
 and cl.CGC_4 = r.CGC_CLIENTE_4
WHERE r.REFERENCIA = 'M0256'
;

SELECT
  lin.*
FROM BASI_120 lin
WHERE lin.NIVEL_ESTRUTURA = 1
;

SELECT
  ce.*
FROM BASI_150 ce
--WHERE lin.NIVEL_ESTRUTURA = 1
;

SELECT
  ac.*
FROM BASI_290 ac
WHERE ac.NIVEL_ESTRUTURA = 1
;

SELECT
  cf.*
FROM BASI_240 cf
--WHERE ac.NIVEL_ESTRUTURA = 1
;

SELECT
  ro.*
FROM basi_070 ro
WHERE ro.GRUPO = 'A5156'
;


SELECT DISTINCT
  r.NIVEL_ESTRUTURA
, r.GRUPO_ESTRUTURA
, r.NUMERO_ALTERNATI || '/' || r.NUMERO_ROTEIRO roteiro
FROM MQOP_050 r
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.GRUPO_ESTRUTURA = '05156'
;

SELECT DISTINCT
  r.NIVEL_ESTRUTURA
, r.GRUPO_ESTRUTURA
, r.NUMERO_ALTERNATI || '/' || r.NUMERO_ROTEIRO roteiro
, r.NUMERO_ROTEIRO || ' (' || ro.DESCRICAO || ')' ROTEIRO
FROM MQOP_050 r
LEFT JOIN BASI_070 ro
  ON ro.ALTERNATIVA = r.NUMERO_ALTERNATI
 AND ro.ROTEIRO = r.NUMERO_ROTEIRO
 AND ro.NIVEL = r.NIVEL_ESTRUTURA
 AND ro.GRUPO = r.GRUPO_ESTRUTURA
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.GRUPO_ESTRUTURA = '05156'
;

SELECT DISTINCT
  r.NUMERO_ALTERNATI
, r.NUMERO_ROTEIRO
, r.NUMERO_ALTERNATI || '/' || r.NUMERO_ROTEIRO roteiro
, r.NUMERO_ALTERNATI || ' (' || COALESCE( al.DESCRICAO, '' ) || ')' ALTERNATIVA
, r.NUMERO_ROTEIRO || ' (' || COALESCE( ro.DESCRICAO, COALESCE( al.DESCRICAO, '' ) ) || ')' ROTEIRO
FROM MQOP_050 r
LEFT JOIN BASI_070 ro
  ON ro.ALTERNATIVA = r.NUMERO_ALTERNATI
 AND ro.ROTEIRO = r.NUMERO_ROTEIRO
 AND ro.NIVEL = r.NIVEL_ESTRUTURA
 AND ro.GRUPO = r.GRUPO_ESTRUTURA
LEFT JOIN BASI_070 al
  ON al.ALTERNATIVA = r.NUMERO_ALTERNATI
 AND al.ROTEIRO = 0
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.GRUPO_ESTRUTURA = 'A5156'
ORDER BY
  r.NUMERO_ALTERNATI
, r.NUMERO_ROTEIRO
;

SELECT
  al.*
FROM BASI_070 al
WHERE al.NIVEL = 1
  AND al.GRUPO = '05156'
  --AND al.ROTEIRO = 14
ORDER BY
  al.GRUPO
;

SELECT
  e.*
FROM BASI_040 e
WHERE e.NIVEL_ITEM = 1
  AND e.GRUPO_ITEM = 'M5156'
;

SELECT DISTINCT
  e.ALTERNATIVA_ITEM ALTERNATIVA
, COALESCE( al.DESCRICAO, '' ) DESCR
, COALESCE(
  ( SELECT
      ec.GRUPO_COMP
    FROM BASI_050 ec
	WHERE ec.NIVEL_ITEM = e.NIVEL_ITEM
	  AND ec.GRUPO_ITEM = e.GRUPO_ITEM
	  AND ec.ALTERNATIVA_ITEM = e.ALTERNATIVA_ITEM
	  AND ec.NIVEL_COMP = 1
	  AND rownum = 1
  ), ' ') COMP_N1
FROM BASI_050 e
LEFT JOIN BASI_070 al
  ON al.ALTERNATIVA = e.ALTERNATIVA_ITEM
 AND al.ROTEIRO = 0
WHERE e.NIVEL_ITEM = 1
  AND e.GRUPO_ITEM = 'A0417'
ORDER BY
  e.ALTERNATIVA_ITEM
;

SELECT
  r.REFERENCIA REF
, CASE WHEN r.REFERENCIA <= '99999' THEN 'PA'
  WHEN r.REFERENCIA like 'A%' or r.REFERENCIA like 'B%' THEN 'PG'
  WHEN r.REFERENCIA like 'Z%' THEN 'MP'
  ELSE 'MD'
  END TIPO
, r.COLECAO_CLIENTE
FROM basi_030 r
WHERE r.REFERENCIA like '%111%'
  AND r.REFERENCIA < 'C0000'
  AND r.NIVEL_ESTRUTURA = 1
;

SELECT DISTINCT
  ec.GRUPO_COMP
FROM BASI_050 ec
WHERE ec.NIVEL_ITEM = 1
  AND ec.NIVEL_COMP = 1
  AND ec.GRUPO_ITEM like '%256%'
  AND ec.GRUPO_ITEM < 'C0000'
;

SELECT
  re.REF
, CASE WHEN r.REFERENCIA <= '99999' THEN 'PA'
  WHEN r.REFERENCIA like 'A%' or r.REFERENCIA like 'B%' THEN 'PG'
  WHEN r.REFERENCIA like 'Z%' THEN 'MP'
  ELSE 'MD'
  END TIPO
, r.COLECAO_CLIENTE
FROM
(
SELECT
  r.REFERENCIA REF
FROM basi_030 r
WHERE regexp_replace(r.REFERENCIA, '[^0-9]', '') IN ('256', '0256', '00256')
  AND r.REFERENCIA < 'C0000'
  AND r.NIVEL_ESTRUTURA = 1
UNION
SELECT DISTINCT
  ec.GRUPO_COMP REF
FROM BASI_050 ec
WHERE ec.NIVEL_ITEM = 1
  AND ec.NIVEL_COMP = 1
  AND regexp_replace(ec.GRUPO_ITEM, '[^0-9]', '') IN ('256', '0256', '00256')
  AND ec.GRUPO_ITEM < 'C0000'
) re
JOIN basi_030 r
  ON r.REFERENCIA = re.REF
 AND r.NIVEL_ESTRUTURA = 1
ORDER BY
  NLSSORT(re.REF,'NLS_SORT=BINARY_AI')
;

        SELECT
          re.REF
        , CASE WHEN r.REFERENCIA <= '99999' THEN 'PA'
          WHEN r.REFERENCIA like 'A%' or r.REFERENCIA like 'B%' THEN 'PG'
          WHEN r.REFERENCIA like 'Z%' THEN 'MP'
          ELSE 'MD'
          END TIPO
        , r.COLECAO_CLIENTE
		, r.CGC_CLIENTE_9
		, r.CGC_CLIENTE_4
		, r.CGC_CLIENTE_2
		, cl.NOME_CLIENTE
		, r.RESPONSAVEL
		, r.DESCR_REFERENCIA
        FROM
        (
        SELECT
          r.REFERENCIA REF
        FROM basi_030 r
        WHERE regexp_replace(r.REFERENCIA, '[^0-9]', '')
              IN ('256') --, '0' || %s, '00' || %s)
          AND r.REFERENCIA < 'C0000'
          AND r.NIVEL_ESTRUTURA = 1
        UNION
        SELECT DISTINCT
          ec.GRUPO_COMP REF
        FROM BASI_050 ec
        WHERE ec.NIVEL_ITEM = 1
          AND ec.NIVEL_COMP = 1
          --AND regexp_replace(ec.GRUPO_ITEM, '[^0-9]', '')
            --  IN (%s, '0' || %s, '00' || %s)
          AND ec.GRUPO_ITEM < 'C0000'
        ) re
        JOIN basi_030 r
          ON r.REFERENCIA = re.REF
         AND r.NIVEL_ESTRUTURA = 1
		JOIN PEDI_010 cl
		  ON cl.CGC_9 = r.CGC_CLIENTE_9
		 and cl.CGC_4 = r.CGC_CLIENTE_4
        ORDER BY
          NLSSORT(re.REF,'NLS_SORT=BINARY_AI')
;

        SELECT
          r.REFERENCIA REF
        , r.DESCR_REFERENCIA DESCR
        , r.RESPONSAVEL STATUS
        , COALESCE(
          CASE WHEN r.REFERENCIA < 'C0000' THEN
            CAST( CAST( regexp_replace(r.REFERENCIA, '[^0-9]', '') AS INTEGER ) AS VARCHAR2(5) )
          ELSE
	        ( SELECT
	              CASE WHEN ec.GRUPO_ITEM IS NULL THEN ' '
	              ELSE CAST( CAST( regexp_replace(ec.GRUPO_ITEM, '[^0-9]', '') AS INTEGER ) AS VARCHAR2(5) )
	              END
		        FROM BASI_050 ec
		        WHERE ec.NIVEL_COMP = r.NIVEL_ESTRUTURA
				  AND ec.GRUPO_COMP = r.REFERENCIA
				  AND rownum = 1
			)
		  END
		  , ' ' ) MODELO
        FROM basi_030 r
        JOIN BASI_150 ce
          ON ce.CONTA_ESTOQUE = r.CONTA_ESTOQUE
        JOIN BASI_120 lin
          ON lin.NIVEL_ESTRUTURA = 1
         AND lin.LINHA_PRODUTO = r.LINHA_PRODUTO
        JOIN BASI_140 col
          ON col.COLECAO = r.COLECAO
        JOIN BASI_290 ac
          ON ac.NIVEL_ESTRUTURA = 1
         AND ac.ARTIGO = r.ARTIGO
        JOIN BASI_240 cf
          ON cf.CLASSIFIC_FISCAL = r.CLASSIFIC_FISCAL
        JOIN PEDI_010 cl
          ON cl.CGC_9 = r.CGC_CLIENTE_9
         and cl.CGC_4 = r.CGC_CLIENTE_4
        WHERE r.REFERENCIA like '%156%' -- 'N156U'
;


        SELECT
          trim(o.DEPOSITO_ENTRADA || ' - ' || d.DESCRICAO) DEPOSITO
        , case
          when o.REFERENCIA_PECA <= '99999' then 'PA'
          when o.REFERENCIA_PECA <= 'A9999' then 'PG'
          else 'MD'
          end TIPO_REF
        , CASE
          WHEN o.ORDEM_PRINCIPAL <> 0 THEN 'Filha de'
          WHEN ofi.ORDEM_PRODUCAO IS NOT NULL THEN 'Mãe de'
          ELSE 'Avulsa'
          END TIPO_OP
        , coalesce( ofi.ORDEM_PRODUCAO, o.ORDEM_PRINCIPAL ) OP_REL
        , o.SITUACAO ||
          CASE
          WHEN o.SITUACAO = 2 THEN '-Ordem conf. gerada'
          WHEN o.SITUACAO = 4 THEN '-Ordens em produção'
          WHEN o.SITUACAO = 9 THEN '-Ordem cancelada'
          ELSE ' '
          END SITUACAO
        , o.COD_CANCELAMENTO ||
          CASE
          WHEN o.COD_CANCELAMENTO = 0 THEN ''
          ELSE '-' || COALESCE(c.DESCRICAO, '')
          END CANCELAMENTO
        , o.ALTERNATIVA_PECA ALTERNATIVA
        , o.ROTEIRO_PECA ROTEIRO
        , o.REFERENCIA_PECA REF
        , ( SELECT
              COUNT( DISTINCT l.ORDEM_CONFECCAO )
            FROM pcpc_040 l
            WHERE l.ORDEM_PRODUCAO = o.ORDEM_PRODUCAO
          ) LOTES
        , ( SELECT
              SUM( l.QTDE_PECAS_PROG )
            FROM pcpc_040 l
            WHERE l.ORDEM_PRODUCAO = o.ORDEM_PRODUCAO
              AND l.SEQ_OPERACAO = (
                SELECT
                  MAX( ls.SEQ_OPERACAO )
                FROM pcpc_040 ls
                WHERE ls.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
              )
          ) QTD
        , o.DATA_PROGRAMACAO DT_DIGITACAO
        , o.DATA_ENTRADA_CORTE DT_CORTE
        , o.PERIODO_PRODUCAO PERIODO
        , p.DATA_INI_PERIODO PERIODO_INI
        , p.DATA_FIM_PERIODO PERIODO_FIM
        FROM PCPC_020 o
        JOIN PCPC_010 p
          ON p.AREA_PERIODO = 1
         AND p.PERIODO_PRODUCAO = o.PERIODO_PRODUCAO
        LEFT JOIN pcpt_050 c
          ON c.COD_CANCELAMENTO = o.COD_CANCELAMENTO
        LEFT JOIN PCPC_020 ofi
          ON ofi.ORDEM_PRINCIPAL = o.ORDEM_PRODUCAO
        JOIN BASI_205 d
          ON d.CODIGO_DEPOSITO = o.DEPOSITO_ENTRADA
        WHERE o.ORDEM_PRODUCAO = 1097
;

        SELECT
          re.REF
        , COALESCE( r.DESCR_REFERENCIA, ' ' ) DESCR
        , CASE WHEN r.REFERENCIA <= '99999' THEN 'PA'
          WHEN r.REFERENCIA like 'A%' or r.REFERENCIA like 'B%' THEN 'PG'
          WHEN r.REFERENCIA like 'Z%' THEN 'MP'
          ELSE 'MD'
          END TIPO
        , COALESCE( r.COLECAO_CLIENTE, ' ' ) COLECAO_CLIENTE
        , r.CGC_CLIENTE_9 CNPJ9
        , r.CGC_CLIENTE_4 CNPJ4
        , r.CGC_CLIENTE_2 CNPJ2
        , cl.NOME_CLIENTE NOME
        , COALESCE( r.RESPONSAVEL, ' ' ) STATUS
        FROM
        (
        SELECT
          r.REFERENCIA REF
        FROM basi_030 r
        WHERE regexp_replace(r.REFERENCIA, '[^0-9]', '')
              IN ('156', '0156', '00156')
          AND r.REFERENCIA < 'C0000'
          AND r.NIVEL_ESTRUTURA = 1
        UNION
        SELECT DISTINCT
          ec.GRUPO_COMP REF
        FROM BASI_050 ec
        WHERE ec.NIVEL_ITEM = 1
          AND ec.NIVEL_COMP = 1
          AND regexp_replace(ec.GRUPO_ITEM, '[^0-9]', '')
              IN ('156', '0156', '00156')
          AND ec.GRUPO_ITEM < 'C0000'
        ) re
        JOIN basi_030 r
          ON r.REFERENCIA = re.REF
         AND r.NIVEL_ESTRUTURA = 1
        JOIN PEDI_010 cl
          ON cl.CGC_9 = r.CGC_CLIENTE_9
         and cl.CGC_4 = r.CGC_CLIENTE_4
         --and cl.CGC_2 = r.CGC_CLIENTE_2
        ORDER BY
          NLSSORT(re.REF,'NLS_SORT=BINARY_AI')
;

SELECT
  cl.*
FROM PEDI_010 cl
WHERE cl.CGC_9 = 45543915
  AND cl.CGC_4 = 1
;

                SELECT
                  f.NUM_NOTA_FISCAL NF
                , f.BASE_ICMS VALOR
                , f.QUANTIDADE
                , f.QTDE_ITENS ITENS_NF
                , f.QTDE_EMBALAGENS VOLUMES
                , f.DATA_AUTORIZACAO_NFE FATURAMENTO
                , CAST( COALESCE( f.COD_STATUS, '0' ) AS INT ) COD_STATUS
                , COALESCE( f.MSG_STATUS, ' ' ) MSG_STATUS
                , f.SITUACAO_NFISC SITUACAO
                , f.NATOP_NF_NAT_OPER NAT
                , f.NATOP_NF_EST_OPER UF
                , n.DESCR_NAT_OPER NATUREZA
                , f.CGC_9 CNPJ9
                , f.CGC_4 CNPJ4
                , f.CGC_2 CNPJ2
                , c.NOME_CLIENTE CLIENTE
                , COALESCE(
                    CASE WHEN f.TRANSPOR_FORNE9
                            + f.TRANSPOR_FORNE4
                            + f.TRANSPOR_FORNE2 = 0
                    THEN 'O PROPRIO'
                    ELSE t.NOME_FANTASIA
                    END
                  , '-') TRANSP
                FROM FATU_050 f
                JOIN PEDI_010 c
                  ON c.CGC_9 = f.CGC_9
                 AND c.CGC_4 = f.CGC_4
                 AND c.CGC_2 = f.CGC_2
                JOIN PEDI_080 n
                  ON n.NATUR_OPERACAO = f.NATOP_NF_NAT_OPER
                 AND n.ESTADO_NATOPER = f.NATOP_NF_EST_OPER
                LEFT JOIN SUPR_010 t
                  ON t.TIPO_FORNECEDOR = 31 -- transportadora
                 AND t.FORNECEDOR9 = f.TRANSPOR_FORNE9
                 AND t.FORNECEDOR4 = f.TRANSPOR_FORNE4
                 AND t.FORNECEDOR2 = f.TRANSPOR_FORNE2
                --WHERE rownum = 1
                ORDER BY
                  f.NUM_NOTA_FISCAL DESC
;

SELECT
  f.BASE_ICMS
, f.*
FROM FATU_050 f
WHERE f.NUM_NOTA_FISCAL = 58779
;


SELECT
  f1.table_name
, f1.column_name col1
, f2.column_name col2
FROM USER_TAB_COLUMNS f1
JOIN USER_TAB_COLUMNS f2
  ON f1.TABLE_NAME = f2.TABLE_NAME
WHERE f1.COLUMN_NAME LIKE '%USUARIO%'
  AND f2.COLUMN_NAME LIKE '%ESTAGIO%'
;

SELECT
  count(*)
FROM BASI_095 l
;

SELECT
  i.*
FROM FATU_060 i
WHERE 1=1
--  AND i.CH_IT_NF_NUM_NFIS = 58800
--  AND i.CH_IT_NF_CD_EMPR <> 1
;

SELECT
  i.NUM_NOTA_ORIG
, i.*
FROM OBRF_015 i
WHERE 1=1
  AND i.CAPA_ENT_NRDOC = 50931
;

SELECT
  ll.ORDEM_PRODUCAO
, ll.CODIGO_ESTAGIO
, ll.SEQ_OPERACAO
, ll.*
FROM PCPC_040 ll -- lotes
WHERE ll.ORDEM_PRODUCAO = 425
  AND ll.SEQ_OPERACAO < 60
  AND ll.QTDE_EM_PRODUCAO_PACOTE <> 0
;

SELECT
  s.*
FROM OBRF_082 s -- itens de saída de OS
WHERE s.NUM_NF_SAI = 58944
;

SELECT
  ptc.GRUPO_ESTRUTURA REF
, ptc.SUBGRU_ESTRUTURA TAM
, ptc.ITEM_ESTRUTURA COR
FROM basi_010 ptc
LEFT JOIN BASI_220 tam
  ON tam.TAMANHO_REF = ptc.SUBGRU_ESTRUTURA
WHERE ptc.NIVEL_ESTRUTURA = 1
  AND (  ptc.PRECO_MEDIO IS NULL
      OR ptc.PRECO_MEDIO = 0
      )
ORDER BY
  ptc.GRUPO_ESTRUTURA
, tam.ORDEM_TAMANHO
, ptc.ITEM_ESTRUTURA
;

SELECT
  ptc.GRUPO_ESTRUTURA REF
, ptc.SUBGRU_ESTRUTURA TAM
, ptc.ITEM_ESTRUTURA COR
FROM basi_010 ptc
WHERE ptc.NIVEL_ESTRUTURA = 1
  AND (  ptc.PRECO_MEDIO IS NULL
      OR ptc.PRECO_MEDIO = 0
      )
;

UPDATE basi_010 ptc
SET
  ptc.PRECO_MEDIO = 2
WHERE ptc.NIVEL_ESTRUTURA = 1
  AND (  ptc.PRECO_MEDIO IS NULL
      OR ptc.PRECO_MEDIO = 0
      )
;

SELECT
  ptc.*
FROM basi_010 ptc
WHERE ptc.NIVEL_ESTRUTURA = 1
;

SELECT DISTINCT
  e.SEQUENCIA
, e.NIVEL_COMP NIVEL
, e.GRUPO_COMP REF
, r.DESCR_REFERENCIA DESCR
, e.SUB_COMP TAM
, e.ITEM_COMP COR
, e.ALTERNATIVA_COMP ALTERN
, e.CONSUMO
, e.ESTAGIO || '-' || es.DESCRICAO ESTAGIO
FROM BASI_050 e
LEFT JOIN basi_030 r
  ON r.NIVEL_ESTRUTURA = e.NIVEL_COMP
 AND r.REFERENCIA = e.GRUPO_COMP
LEFT JOIN MQOP_005 es
  ON es.CODIGO_ESTAGIO = e.ESTAGIO
WHERE e.NIVEL_ITEM = 1
--  AND e.GRUPO_ITEM = %s
--  AND e.ALTERNATIVA_ITEM = %s
  AND rownum < 11
ORDER BY
  e.SEQUENCIA
;

SELECT
  r.SEQ_OPERACAO SEQ
, r.CODIGO_OPERACAO || ' - ' || o.NOME_OPERACAO OPERACAO
, r.CODIGO_ESTAGIO || ' - ' || e.DESCRICAO ESTAGIO
FROM MQOP_050 r -- roteiro
JOIN MQOP_005 e -- estagio
  ON e.CODIGO_ESTAGIO = r.CODIGO_ESTAGIO
JOIN MQOP_040 o -- operacao
  ON o.CODIGO_OPERACAO = r.CODIGO_OPERACAO
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.GRUPO_ESTRUTURA = 'M5156'
  AND r.CODIGO_ESTAGIO = 60
--  AND r.NUMERO_ALTERNATI = %s
--  AND r.NUMERO_ROTEIRO = %s
  AND rownum < 21
ORDER BY
  r.SEQ_OPERACAO
;

SELECT DISTINCT
  e.NIVEL_ITEM || '-' || e.GRUPO_ITEM || ' (' || rp.DESCR_REFERENCIA  || ')' REF
, e.SUB_ITEM TAM
, e.ITEM_ITEM COR
, e.ALTERNATIVA_ITEM ALT
--, r.NUMERO_ALTERNATI ALT_ROTEIRO
, e.NIVEL_COMP || '-' || e.GRUPO_COMP || ' (' || rm.DESCR_REFERENCIA  || ')' MP
, e.SUB_COMP MP_TAM
, e.ITEM_COMP MP_COR
, e.ALTERNATIVA_COMP MP_ALT
, e.ESTAGIO || ' - ' || es.DESCRICAO ESTAGIO
, rp.RESPONSAVEL
FROM BASI_050 e -- estrutura de produto
LEFT JOIN basi_030 rp -- referencia produto
  ON rp.NIVEL_ESTRUTURA = e.NIVEL_ITEM
 AND rp.REFERENCIA = e.GRUPO_ITEM
LEFT JOIN basi_030 rm -- referencia matéria prima
  ON rm.NIVEL_ESTRUTURA = e.NIVEL_COMP
 AND rm.REFERENCIA = e.GRUPO_COMP
LEFT JOIN MQOP_050 r -- roteiro de produto
  ON r.CODIGO_ESTAGIO = e.ESTAGIO
 AND r.NIVEL_ESTRUTURA = e.NIVEL_ITEM
 AND r.GRUPO_ESTRUTURA = e.GRUPO_ITEM
 AND r.NUMERO_ALTERNATI = e.ALTERNATIVA_ITEM
-- AND r.NUMERO_ROTEIRO = r.NUMERO_ROTEIRO
LEFT JOIN MQOP_005 es -- cadastro de estagios
  ON es.CODIGO_ESTAGIO = e.ESTAGIO
WHERE e.NIVEL_ITEM = 1
--  AND e.GRUPO_ITEM = 'M5156'
  AND r.SEQ_OPERACAO IS NULL
  AND rp.RESPONSAVEL IS NOT NULL
--  AND rownum < 21
;

SELECT
  r.*
FROM MQOP_050 r
;

SELECT DISTINCT
  e.GRUPO_ITEM REF
, e.NIVEL_ITEM || '-' || e.GRUPO_ITEM ||
  ' (' || rp.DESCR_REFERENCIA  || ')' PROD
, e.SUB_ITEM TAM
, e.ITEM_ITEM COR
, e.ALTERNATIVA_ITEM ALT
, e.GRUPO_COMP
, e.NIVEL_COMP || '-' || e.GRUPO_COMP ||
  ' (' || rm.DESCR_REFERENCIA  || ')' MP
, e.SUB_COMP MP_TAM
, e.ITEM_COMP MP_COR
, e.ALTERNATIVA_COMP MP_ALT
, e.ESTAGIO || ' - ' || es.DESCRICAO ESTAGIO
, rp.RESPONSAVEL
FROM (
SELECT DISTINCT
  ref.NIVEL_ESTRUTURA
, ref.REFERENCIA
, ref.RESPONSAVEL
, ref.DESCR_REFERENCIA
, rpro.NUMERO_ALTERNATI
FROM basi_030 REF -- produto
LEFT JOIN MQOP_050 rpro -- roteiro de produto
  ON rpro.NIVEL_ESTRUTURA = ref.NIVEL_ESTRUTURA
 AND rpro.GRUPO_ESTRUTURA = ref.REFERENCIA
WHERE ref.NIVEL_ESTRUTURA = 1
--  AND REF.REFERENCIA = '0679A'
  AND rpro.NUMERO_ROTEIRO IS NOT NULL
  AND ref.RESPONSAVEL IS NOT NULL
) rp -- produto com algum roteiro
JOIN BASI_050 e -- estrutura de produto
  ON e.NIVEL_ITEM = rp.NIVEL_ESTRUTURA
 AND e.GRUPO_ITEM = rp.REFERENCIA
 AND e.ALTERNATIVA_ITEM = rp.NUMERO_ALTERNATI
LEFT JOIN basi_030 rm -- referencia matéria prima
  ON rm.NIVEL_ESTRUTURA = e.NIVEL_COMP
 AND rm.REFERENCIA = e.GRUPO_COMP
LEFT JOIN MQOP_050 ri -- roteiro de produto com estágio do insumo
  ON ri.CODIGO_ESTAGIO = e.ESTAGIO
 AND ri.NIVEL_ESTRUTURA = e.NIVEL_ITEM
 AND ri.GRUPO_ESTRUTURA = e.GRUPO_ITEM
 AND ri.NUMERO_ALTERNATI = rp.NUMERO_ALTERNATI
LEFT JOIN MQOP_005 es -- cadastro de estagios
  ON es.CODIGO_ESTAGIO = e.ESTAGIO
WHERE e.NIVEL_ITEM = 1
  AND e.GRUPO_COMP not like 'DV%'
--  AND r.SEQ_OPERACAO IS NOT NULL
  AND ri.SEQ_OPERACAO IS NULL
ORDER BY
  e.GRUPO_ITEM
, e.ALTERNATIVA_ITEM
, e.GRUPO_COMP
;

SELECT
  ref.NIVEL_ESTRUTURA
, ref.REFERENCIA
, ref.RESPONSAVEL
, ref.DESCR_REFERENCIA
, e.ALTERNATIVA_ITEM
FROM basi_030 REF -- produto
JOIN BASI_050 e -- estrutura de produto
  ON e.NIVEL_ITEM = ref.NIVEL_ESTRUTURA
 AND e.GRUPO_ITEM = ref.REFERENCIA
WHERE ref.NIVEL_ESTRUTURA = 1
  AND REF.COLECAO <> 3
  AND e.ALTERNATIVA_ITEM = 2
;

SELECT
  ie.*
FROM OBRF_015 ie -- item de nota fiscal de entrada
WHERE 1=1
--  AND ie.NUM_NOTA_ORIG = 58944
  AND ie.CAPA_ENT_NRDOC = 51155
;


SELECT
  ne.NATOPER_NAT_OPER
, ne.*
FROM OBRF_010 ne -- capa de nota fiscal de entrada
WHERE ne.DOCUMENTO = 51155 -- 2198
;

SELECT
  s.PRODSAI_NIVEL99 NIVEL
, s.PRODSAI_GRUPO REF
, s.PRODSAI_ITEM COR
, s.PRODSAI_SUBGRUPO TAM
, i.NARRATIVA
, r.UNIDADE_MEDIDA UN
, s.VALOR_PRODUTO VALOR_UN
, s.QTDE_ESTRUTURA QTD_ESTR
, s.QTDE_ENVIADA QTD_ENV
, s.NUM_NF_SAI NF
, nf.DATA_EMISSAO DATA_NF
, ie.CAPA_ENT_NRDOC NF_RETORNO
, ce.DATA_TRANSACAO DATA_RETORNO
, ie.QUANTIDADE QTD_RETORNO
, CASE WHEN ie.QUANTIDADE < s.QTDE_ENVIADA
  THEN 'Parcial'
  ELSE 'Total'
  END RETORNO
, CASE WHEN s.PRODSAI_NIVEL99 = 1 THEN
    CASE
    WHEN ce.NATOPER_NAT_OPER = 22 THEN 'Sim'
    WHEN ce.NATOPER_NAT_OPER = 23 THEN 'Não'
    ELSE 'Verificar'
    END
  ELSE '-'
  END APLICADO
FROM OBRF_082 s
JOIN BASI_010 i
  ON i.NIVEL_ESTRUTURA = s.PRODSAI_NIVEL99
 AND i.GRUPO_ESTRUTURA = s.PRODSAI_GRUPO
 AND i.SUBGRU_ESTRUTURA = s.PRODSAI_SUBGRUPO
 AND i.ITEM_ESTRUTURA = s.PRODSAI_ITEM
JOIN BASI_030 r
  ON r.NIVEL_ESTRUTURA = s.PRODSAI_NIVEL99
 AND r.REFERENCIA = s.PRODSAI_GRUPO
LEFT JOIN BASI_220 tam
  ON tam.TAMANHO_REF = s.PRODSAI_SUBGRUPO
LEFT JOIN FATU_050 nf -- nota fiscal da Tussor
  ON nf.NUM_NOTA_FISCAL = s.NUM_NF_SAI
LEFT JOIN OBRF_015 ie -- item de nota fiscal de entrada
  ON s.NUM_NF_SAI <> 0
 AND ie.NUM_NOTA_ORIG = s.NUM_NF_SAI
 AND ie.CODITEM_NIVEL99 = s.PRODSAI_NIVEL99
 AND ie.CODITEM_GRUPO = s.PRODSAI_GRUPO
 AND ie.CODITEM_SUBGRUPO = s.PRODSAI_SUBGRUPO
 AND ie.CODITEM_ITEM = s.PRODSAI_ITEM
LEFT JOIN OBRF_010 ce -- capa de nota fiscal de entrada
  ON ce.DOCUMENTO = CAPA_ENT_NRDOC
 AND ce.CGC_CLI_FOR_9 = ie.CAPA_ENT_FORCLI9
 AND ce.CGC_CLI_FOR_4 = ie.CAPA_ENT_FORCLI4
-- AND ce.NATOPER_NAT_OPER IN ( 22, 23 ) -- é industrializado, não indiustri. ou não tem nota de entrada relacionada a saída
WHERE s.NUMERO_ORDEM =  996 -- 962 -- 942 -- 1193 -- 895
ORDER BY
  s.PRODSAI_NIVEL99
, s.PRODSAI_GRUPO
, s.PRODSAI_ITEM
, tam.ORDEM_TAMANHO
;

SELECT
  nf.*
FROM FATU_050 nf -- nota fiscal da Tussor
WHERE nf.NUM_NOTA_FISCAL = 58944
;

SELECT
  p.PEDIDO_VENDA PEDIDO
, c.NOME_CLIENTE || ' (' || lpad(c.CGC_9, 8, '0') || '/' || lpad(c.CGC_4, 4, '0') || '-' || lpad(c.CGC_2, 2, '0') || ')' CLIENTE
, i.CD_IT_PE_NIVEL99 NIVEL
, i.CD_IT_PE_GRUPO REF
, i.CD_IT_PE_ITEM COR
, i.CD_IT_PE_SUBGRUPO TAM
, ip.SUBGRUPO_ESTRUTURA
, t.ORDEM_TAMANHO
, i.QTDE_PEDIDA QTD
, coalesce( ip.REF_CLIENTE, '-') INFADPROD
, coalesce( rtc.CODIGO_BARRAS, ' ') EAN
, rtc.NARRATIVA
FROM PEDI_100 p -- pedido de venda
LEFT JOIN PEDI_010 c
  ON c.CGC_9 = p.CLI_PED_CGC_CLI9
 AND c.CGC_4 = p.CLI_PED_CGC_CLI4
JOIN PEDI_110 i -- item de pedido de venda
  ON i.PEDIDO_VENDA = p.PEDIDO_VENDA
JOIN BASI_010 rtc -- item (ref+tam+cor)
  on rtc.NIVEL_ESTRUTURA = i.CD_IT_PE_NIVEL99
 AND rtc.GRUPO_ESTRUTURA = i.CD_IT_PE_GRUPO
 AND rtc.SUBGRU_ESTRUTURA = i.CD_IT_PE_SUBGRUPO
 AND rtc.ITEM_ESTRUTURA = i.CD_IT_PE_ITEM
LEFT JOIN ESTQ_400 ip -- item - informações por cliente
  ON ip.CLIENTE9 = CLI_PED_CGC_CLI9
 AND ip.CLIENTE4 = CLI_PED_CGC_CLI4
 AND ip.NIVEL_ESTRUTURA = i.CD_IT_PE_NIVEL99
 AND ip.GRUPO_ESTRUTURA = i.CD_IT_PE_GRUPO
 AND ip.SUBGRUPO_ESTRUTURA = i.CD_IT_PE_SUBGRUPO
 AND ip.ITEM_ESTRUTURA = i.CD_IT_PE_ITEM
LEFT JOIN BASI_220 t -- tamanhos
  ON t.TAMANHO_REF = i.CD_IT_PE_SUBGRUPO
WHERE p.PEDIDO_VENDA = 3040
ORDER BY
  p.PEDIDO_VENDA
, p.CLI_PED_CGC_CLI9
, p.CLI_PED_CGC_CLI4
, i.CD_IT_PE_NIVEL99
, i.CD_IT_PE_GRUPO
, i.CD_IT_PE_ITEM
, t.ORDEM_TAMANHO
, i.CD_IT_PE_SUBGRUPO
;

SELECT
  cr.*
FROM BASI_070 cr -- capa de roteiro | obs.: o roteiro consegue existir sem isso
WHERE cr.GRUPO LIKE 'F%'
;

SELECT
  e.*
FROM MQOP_005 e -- cadastro de estágios
;

SELECT
  oper.*
FROM MQOP_040 oper -- cadastro de operações
;

SELECT
  r.SEQUENCIA_ESTAGIO
, r.*
FROM MQOP_050 r -- Operaçoes das Alternativas de roteiro dos produtos
WHERE r.GRUPO_ESTRUTURA = 'F400U'
  AND r.NUMERO_ALTERNATI = 1
;

SELECT
  r.*
FROM MQOP_050 r -- Operaçoes das Alternativas de roteiro dos produtos
WHERE r.GRUPO_ESTRUTURA like 'F%'
--  AND r.CODIGO_OPERACAO <> r.CODIGO_ESTAGIO
  AND r.CODIGO_OPERACAO NOT IN (6, 15)
;

DELETE FROM MQOP_050 r -- Operaçoes das Alternativas de roteiro dos produtos
WHERE r.GRUPO_ESTRUTURA like 'F%'
--  AND r.CODIGO_OPERACAO <> r.CODIGO_ESTAGIO
  AND r.CODIGO_OPERACAO NOT IN (6, 15)
;

SELECT
  r.SEQUENCIA_ESTAGIO
, r.*
FROM MQOP_050 r -- Operaçoes das Alternativas de roteiro dos produtos
WHERE r.GRUPO_ESTRUTURA like 'F%'
--  AND r.CODIGO_OPERACAO <> r.CODIGO_ESTAGIO
  AND r.CODIGO_OPERACAO = 15
;

UPDATE MQOP_050 r -- Operaçoes das Alternativas de roteiro dos produtos
SET
  r.SEQUENCIA_ESTAGIO = 2
WHERE r.GRUPO_ESTRUTURA like 'F%'
--  AND r.CODIGO_OPERACAO <> r.CODIGO_ESTAGIO
  AND r.CODIGO_OPERACAO = 15
;

UPDATE MQOP_050 r -- Operaçoes das Alternativas de roteiro dos produtos
SET
  r.SEQUENCIA_ESTAGIO = 1
WHERE r.GRUPO_ESTRUTURA like 'F%'
--  AND r.CODIGO_OPERACAO <> r.CODIGO_ESTAGIO
  AND r.CODIGO_OPERACAO = 6
;

SELECT
  r.SEQUENCIA_ESTAGIO
, r.CODIGO_OPERACAO
, r.*
FROM MQOP_050 r -- Operaçoes das Alternativas de roteiro dos produtos
WHERE r.GRUPO_ESTRUTURA LIKE 'F%'
  AND r.CODIGO_OPERACAO IN (6, 15)
;

SELECT
  o.PEDIDO_VENDA
, o.ORDEM_PRODUCAO
, CASE WHEN o.REFERENCIA_PECA <= '99999' THEN 'PA'
  WHEN o.REFERENCIA_PECA like 'A%' or o.REFERENCIA_PECA like 'B%' THEN 'PG'
  WHEN o.REFERENCIA_PECA like 'Z%' THEN 'MP'
  ELSE 'MD'
  END TIPO
, o.REFERENCIA_PECA
, o.ORDEM_PRINCIPAL
, ( SELECT
      SUM( l.QTDE_PECAS_PROG )
    FROM pcpc_040 l
    WHERE l.ORDEM_PRODUCAO = o.ORDEM_PRODUCAO
      AND l.SEQ_OPERACAO = (
        SELECT
          MAX( ls.SEQ_OPERACAO )
        FROM pcpc_040 ls
        WHERE ls.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
      )
  ) QTD
, o.
FROM PCPC_020 o -- OP
WHERE o.PEDIDO_VENDA = 3761
  AND o.SITUACAO <> 9
ORDER BY
  o.ORDEM_PRINCIPAL
, o.ORDEM_PRODUCAO
;

SELECT
  o.PEDIDO_VENDA
, count( DISTINCT o.ORDEM_PRODUCAO)
FROM PCPC_020 o -- OP
GROUP BY
  o.PEDIDO_VENDA
ORDER BY
  1 DESC
;

SELECT
  o.*
FROM PCPC_020 o
JOIN PCPC_010 p
  ON p.AREA_PERIODO = 1
 AND p.PERIODO_PRODUCAO = o.PERIODO_PRODUCAO
LEFT JOIN pcpt_050 c
  ON c.COD_CANCELAMENTO = o.COD_CANCELAMENTO
LEFT JOIN PCPC_020 ofi
  ON o.ORDEM_PRODUCAO =
  SELECT min(oo.ORDEM_PRODUCAO)
  ofi.ORDEM_PRINCIPAL = o.ORDEM_PRODUCAO
WHERE o.ORDEM_PRODUCAO = 3753
;

SELECT
  LISTAGG(ofi.ORDEM_PRODUCAO, ', ')
  WITHIN GROUP (ORDER BY ofi.ORDEM_PRODUCAO)
FROM PCPC_020 ofi
WHERE ofi.ORDEM_PRINCIPAL = 3753
;

SELECT
  m.*
FROM HDOC_035 m
--WHERE m.DESCRICAO LIKE '%confe%'
WHERE m.CODIGO_PROGRAMA = 'pcpc_f049'
;

SELECT DISTINCT
  l.ORDEM_CONFECCAO
, l.QTDE_PECAS_PROG
, l.*
FROM pcpc_040 l
WHERE 1=1
  AND l.PERIODO_PRODUCAO =  1731 -- 1742
  AND l.ORDEM_CONFECCAO = 839 -- 3486
ORDER BY
  l.SEQUENCIA_ESTAGIO
;

SELECT DISTINCT
  l.ORDEM_PRODUCAO
, l.QTDE_PERDAS
, l.QTDE_PROGRAMADA
, ( SELECT
      max(os.NUMERO_ORDEM)
	FROM pcpc_040 os -- lotes
	WHERE os.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
  ) OS
, l.*
FROM pcpc_040 l -- lotes
WHERE 1=1
  AND l.QTDE_PERDAS <> 0
  AND l.QTDE_PERDAS <> l.QTDE_PROGRAMADA
--  AND l.NUMERO_ORDEM <> 0
--  AND l.PERIODO_PRODUCAO = 1735
--  AND l.ORDEM_CONFECCAO = 11820
ORDER BY
  l.SEQUENCIA_ESTAGIO
;

SELECT
  i.TAMANHO
, i.SORTIMENTO
, i.QUANTIDADE
, i.*
FROM PCPC_021 i
WHERE i.ORDEM_PRODUCAO = 2554
ORDER BY
  i.SEQUENCIA_TAMANHO
, i.SORTIMENTO
;

SELECT DISTINCT
  sum(l.QTDE_PECAS_PROG) PROG
, sum(l.QTDE_A_PRODUZIR_PACOTE) A_PROD
, sum(l.QTDE_PECAS_PROD) PROD
, sum(l.QTDE_PECAS_2A) PROD_2A
, sum(l.QTDE_PERDAS) PERDAS
FROM pcpc_040 l -- lotes
WHERE 1=1
  AND l.SEQUENCIA_ESTAGIO = 1
  AND l.ORDEM_PRODUCAO = 2554
;

SELECT DISTINCT
  l.QTDE_PECAS_PROG
, l.ORDEM_CONFECCAO
FROM pcpc_040 l -- lotes
WHERE 1=1
  AND l.SEQUENCIA_ESTAGIO = 1
  AND l.ORDEM_PRODUCAO = 2554
  AND l.QTDE_PECAS_PROG = 5
;

SELECT
  p.PERIODO_PRODUCAO
, 0
, r.COD_REP_CLIENTE
, 1
, 40000
, 1
, 0
, 0
, 0
, 0
FROM PCPC_010 p, PEDI_020 R
WHERE r.COD_REP_CLIENTE <> 0
  AND p.PERIODO_PRODUCAO > 1800
  AND p.PERIODO_PRODUCAO < 2100
  AND p.AREA_PERIODO = 8
;

INSERT INTO PEDI_170 (
  PERIODO_COTAS
, CODIGO_REGIAO
, CODIGO_REPR
, ARTIGO_COTAS
, QTDE_COTAS
, VALOR_COTAS
, QTDE_VENDIDA
, VALOR_VENDIDO
, QTDE_CANCELADA
, VALOR_CANCELADO
)
SELECT
  p.PERIODO_PRODUCAO
, 0
, r.COD_REP_CLIENTE
, 1
, 40000
, 1
, 0
, 0
, 0
, 0
FROM PCPC_010 p, PEDI_020 R
WHERE r.COD_REP_CLIENTE <> 0
  AND p.PERIODO_PRODUCAO > 1800
  AND p.PERIODO_PRODUCAO < 2100
  AND p.AREA_PERIODO = 8
;
