SELECT
  i.CODIGO_BARRAS
, i.*
FROM BASI_010 i
WHERE i.GRUPO_ESTRUTURA = '0679A'
  AND i.CODIGO_BARRAS IS NOT NULL
;

MERGE INTO BASI_010 dest
USING(
	SELECT
	  ori.*
	FROM BASI_010 ori
	WHERE ori.GRUPO_ESTRUTURA = '0679A'
	  AND ori.CODIGO_BARRAS IS NOT NULL
	) orig
ON (dest.NIVEL_ESTRUTURA = orig.NIVEL_ESTRUTURA
AND dest.GRUPO_ESTRUTURA = '0679O'
AND dest.SUBGRU_ESTRUTURA = orig.SUBGRU_ESTRUTURA
AND dest.ITEM_ESTRUTURA = orig.ITEM_ESTRUTURA
)
WHEN MATCHED THEN
    update set dest.CODIGO_BARRAS = orig.CODIGO_BARRAS
--WHEN NOT MATCHED THEN
--    insert (xyz) values (orig.xyz)
;

SELECT
  i.CODIGO_BARRAS
, i.*
FROM BASI_010 i
WHERE i.GRUPO_ESTRUTURA IN ( '0679A', '0679O')
  AND i.CODIGO_BARRAS IS NOT NULL
ORDER BY
  i.SUBGRU_ESTRUTURA
, i.ITEM_ESTRUTURA
, i.GRUPO_ESTRUTURA
;
