
-- produtos com roteiro fluxo 1 de PA
SELECT
  r.NIVEL_ESTRUTURA
, r.RESPONSAVEL
, r.REFERENCIA
, r.COLECAO
, r.*
FROM basi_030 r -- referência
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND r.REFERENCIA < 'A'
  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
;

SELECT
  r.*
FROM basi_030 r -- referência
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND r.REFERENCIA < 'A'
  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
  AND rownum <= 2

-- roteiros (lista de operações de uma alternativa de produto)
SELECT
  rot.*
FROM MQOP_050 rot
WHERE rot.GRUPO_ESTRUTURA = '0617M'
--  AND rot.NUMERO_ROTEIRO = 1
ORDER BY
  rot.NUMERO_ROTEIRO
, rot.SEQ_OPERACAO
;

-- roteiros de produtos selecionados (lista de operações de uma alternativa de produto)
SELECT
  rot.*
FROM MQOP_050 rot
JOIN
(
SELECT
  r.*
FROM basi_030 r -- referência
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND r.REFERENCIA < 'A'
  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
  AND rownum = 1
) ref ON rot.GRUPO_ESTRUTURA = REF.REFERENCIA
;

-- capa de roteiro - onde define o nome dos roteiros das alternativas de referências
SELECT
  rot.*
FROM BASI_070 rot
WHERE rot.GRUPO = 'Z01PA'
;

-- cadastro de estágios
SELECT
  rot.*
FROM MQOP_005 rot
;

-- cadastro de operações
SELECT
  rot.*
FROM MQOP_040 rot
;

-- capa de roteiros de produtos selecionados
SELECT
  rot.*
FROM BASI_070 rot
JOIN
(
SELECT
  r.*
FROM basi_030 r -- referência
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND r.REFERENCIA < 'A'
  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
  AND rownum = 1
) ref ON rot.GRUPO = REF.REFERENCIA
;

SELECT
  rotp.NIVEL_ESTRUTURA
, rotp.GRUPO_ESTRUTURA
, rotp.SUBGRU_ESTRUTURA
, rotp.ITEM_ESTRUTURA
, rotp.NUMERO_ALTERNATI
, rotp.NUMERO_ROTEIRO
, rotp.SEQ_OPERACAO
, rotp.CODIGO_OPERACAO
, rotp.MINUTOS
, rotp.CODIGO_ESTAGIO
, rotp.CENTRO_CUSTO
, rotp.SEQUENCIA_ESTAGIO
, rotp.ESTAGIO_ANTERIOR
, rotp.ESTAGIO_DEPENDE
, rotp.SEPARA_OPERACAO
, rotp.MINUTOS_HOMEM
, rotp.CCUSTO_HOMEM
, rotp.NUMERO_CORDAS
, rotp.NUMERO_ROLOS
, rotp.VELOCIDADE
, rotp.CODIGO_FAMILIA
, rotp.OBSERVACAO
, rotp.TIPO_PROCESSO
, rotp.PECAS_1_HORA
, rotp.PECAS_8_HORAS
, rotp.CUSTO_MINUTO
, rotp.PERC_EFICIENCIA
, rotp.TEMPERATURA
, rotp.TEMPO_LOTE_PRODUCAO
, rotp.PECAS_LOTE_PRODUCAO
, rotp.TIME_CELULA
, rotp.CODIGO_APARELHO
, rotp.PERC_EFIC_ROT
, rotp.NUMERO_OPERADORAS
, rotp.CONSIDERA_EFIC
, rotp.SEQ_OPERACAO_AGRUPADORA
, rotp.CODIGO_PARTE_PECA
, rotp.SEQ_JUNCAO_PARTE_PECA
, rotp.SITUACAO
, rotp.PERC_PERDAS
, rotp.PERC_CUSTOS
, rotp.IND_ESTAGIO_GARGALO
FROM SYSTEXTIL.MQOP_050 rotp
WHERE rotp.GRUPO_ESTRUTURA='Z01PA'
--  AND rotp.NUMERO_ROTEIRO=1
;

SELECT
  rotp.NIVEL_ESTRUTURA nivel
, rotp.GRUPO_ESTRUTURA ref
, rotp.SUBGRU_ESTRUTURA tam
, rotp.ITEM_ESTRUTURA cor
, rotp.NUMERO_ALTERNATI alt
, rotp.NUMERO_ROTEIRO roteiro
, rotp.SEQ_OPERACAO seq_op
, rotp.IND_ESTAGIO_GARGALO gargalo
, rotp.CODIGO_OPERACAO operacao
, rotp.CODIGO_ESTAGIO estagio
, rotp.SEQUENCIA_ESTAGIO seq_est
FROM SYSTEXTIL.MQOP_050 rotp
WHERE rotp.GRUPO_ESTRUTURA='Z01PA'
--  AND rotp.NUMERO_ROTEIRO=1
ORDER BY
  rotp.GRUPO_ESTRUTURA
, rotp.NUMERO_ROTEIRO
, rotp.SEQ_OPERACAO
;

SELECT
  rotp.NIVEL_ESTRUTURA
, ref.REFERENCIA GRUPO_ESTRUTURA
, rotp.SUBGRU_ESTRUTURA
, rotp.ITEM_ESTRUTURA
, rotp.NUMERO_ALTERNATI
, rotp.NUMERO_ROTEIRO
, rotp.SEQ_OPERACAO
, rotp.CODIGO_OPERACAO
, rotp.MINUTOS
, rotp.CODIGO_ESTAGIO
, rotp.CENTRO_CUSTO
, rotp.SEQUENCIA_ESTAGIO
, rotp.ESTAGIO_ANTERIOR
, rotp.ESTAGIO_DEPENDE
, rotp.SEPARA_OPERACAO
, rotp.MINUTOS_HOMEM
, rotp.CCUSTO_HOMEM
, rotp.NUMERO_CORDAS
, rotp.NUMERO_ROLOS
, rotp.VELOCIDADE
, rotp.CODIGO_FAMILIA
, rotp.OBSERVACAO
, rotp.TIPO_PROCESSO
, rotp.PECAS_1_HORA
, rotp.PECAS_8_HORAS
, rotp.CUSTO_MINUTO
, rotp.PERC_EFICIENCIA
, rotp.TEMPERATURA
, rotp.TEMPO_LOTE_PRODUCAO
, rotp.PECAS_LOTE_PRODUCAO
, rotp.TIME_CELULA
, rotp.CODIGO_APARELHO
, rotp.PERC_EFIC_ROT
, rotp.NUMERO_OPERADORAS
, rotp.CONSIDERA_EFIC
, rotp.SEQ_OPERACAO_AGRUPADORA
, rotp.CODIGO_PARTE_PECA
, rotp.SEQ_JUNCAO_PARTE_PECA
, rotp.SITUACAO
, rotp.PERC_PERDAS
, rotp.PERC_CUSTOS
, rotp.IND_ESTAGIO_GARGALO
FROM SYSTEXTIL.MQOP_050 rotp
,
(
SELECT
  r.*
FROM basi_030 r -- referência
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND r.REFERENCIA < 'A'
  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
  AND rownum = 1
) ref
WHERE rotp.GRUPO_ESTRUTURA='Z01PA' AND rotp.NUMERO_ROTEIRO=1
;

INSERT INTO SYSTEXTIL.MQOP_050
(NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRU_ESTRUTURA, ITEM_ESTRUTURA, NUMERO_ALTERNATI, NUMERO_ROTEIRO, SEQ_OPERACAO, CODIGO_OPERACAO, MINUTOS, CODIGO_ESTAGIO, CENTRO_CUSTO, SEQUENCIA_ESTAGIO, ESTAGIO_ANTERIOR, ESTAGIO_DEPENDE, SEPARA_OPERACAO, MINUTOS_HOMEM, CCUSTO_HOMEM, NUMERO_CORDAS, NUMERO_ROLOS, VELOCIDADE, CODIGO_FAMILIA, OBSERVACAO, TIPO_PROCESSO, PECAS_1_HORA, PECAS_8_HORAS, CUSTO_MINUTO, PERC_EFICIENCIA, TEMPERATURA, TEMPO_LOTE_PRODUCAO, PECAS_LOTE_PRODUCAO, TIME_CELULA, CODIGO_APARELHO, PERC_EFIC_ROT, NUMERO_OPERADORAS, CONSIDERA_EFIC, SEQ_OPERACAO_AGRUPADORA, CODIGO_PARTE_PECA, SEQ_JUNCAO_PARTE_PECA, SITUACAO, PERC_PERDAS, PERC_CUSTOS, IND_ESTAGIO_GARGALO)
SELECT
  rotp.NIVEL_ESTRUTURA
, ref.REFERENCIA GRUPO_ESTRUTURA
, rotp.SUBGRU_ESTRUTURA
, rotp.ITEM_ESTRUTURA
, rotp.NUMERO_ALTERNATI
, rotp.NUMERO_ROTEIRO
, rotp.SEQ_OPERACAO
, rotp.CODIGO_OPERACAO
, rotp.MINUTOS
, rotp.CODIGO_ESTAGIO
, rotp.CENTRO_CUSTO
, rotp.SEQUENCIA_ESTAGIO
, rotp.ESTAGIO_ANTERIOR
, rotp.ESTAGIO_DEPENDE
, rotp.SEPARA_OPERACAO
, rotp.MINUTOS_HOMEM
, rotp.CCUSTO_HOMEM
, rotp.NUMERO_CORDAS
, rotp.NUMERO_ROLOS
, rotp.VELOCIDADE
, rotp.CODIGO_FAMILIA
, rotp.OBSERVACAO
, rotp.TIPO_PROCESSO
, rotp.PECAS_1_HORA
, rotp.PECAS_8_HORAS
, rotp.CUSTO_MINUTO
, rotp.PERC_EFICIENCIA
, rotp.TEMPERATURA
, rotp.TEMPO_LOTE_PRODUCAO
, rotp.PECAS_LOTE_PRODUCAO
, rotp.TIME_CELULA
, rotp.CODIGO_APARELHO
, rotp.PERC_EFIC_ROT
, rotp.NUMERO_OPERADORAS
, rotp.CONSIDERA_EFIC
, rotp.SEQ_OPERACAO_AGRUPADORA
, rotp.CODIGO_PARTE_PECA
, rotp.SEQ_JUNCAO_PARTE_PECA
, rotp.SITUACAO
, rotp.PERC_PERDAS
, rotp.PERC_CUSTOS
, rotp.IND_ESTAGIO_GARGALO
FROM SYSTEXTIL.MQOP_050 rotp
,
(
SELECT
  r.*
FROM basi_030 r -- referência
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND r.REFERENCIA < 'A'
  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
  AND rownum = 1
) ref
WHERE rotp.GRUPO_ESTRUTURA='Z01PA'
--  AND rotp.NUMERO_ROTEIRO=1
;

INSERT INTO SYSTEXTIL.MQOP_050
(NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRU_ESTRUTURA, ITEM_ESTRUTURA, NUMERO_ALTERNATI, NUMERO_ROTEIRO, SEQ_OPERACAO, CODIGO_OPERACAO, MINUTOS, CODIGO_ESTAGIO, CENTRO_CUSTO, SEQUENCIA_ESTAGIO, ESTAGIO_ANTERIOR, ESTAGIO_DEPENDE, SEPARA_OPERACAO, MINUTOS_HOMEM, CCUSTO_HOMEM, NUMERO_CORDAS, NUMERO_ROLOS, VELOCIDADE, CODIGO_FAMILIA, OBSERVACAO, TIPO_PROCESSO, PECAS_1_HORA, PECAS_8_HORAS, CUSTO_MINUTO, PERC_EFICIENCIA, TEMPERATURA, TEMPO_LOTE_PRODUCAO, PECAS_LOTE_PRODUCAO, TIME_CELULA, CODIGO_APARELHO, PERC_EFIC_ROT, NUMERO_OPERADORAS, CONSIDERA_EFIC, SEQ_OPERACAO_AGRUPADORA, CODIGO_PARTE_PECA, SEQ_JUNCAO_PARTE_PECA, SITUACAO, PERC_PERDAS, PERC_CUSTOS, IND_ESTAGIO_GARGALO)
VALUES('1', '0617M', '000', '000000', 3, 3, 3, 18, 0, 18, 0, 1, 0, 0, NULL, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 1);
INSERT INTO SYSTEXTIL.MQOP_050
(NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRU_ESTRUTURA, ITEM_ESTRUTURA, NUMERO_ALTERNATI, NUMERO_ROTEIRO, SEQ_OPERACAO, CODIGO_OPERACAO, MINUTOS, CODIGO_ESTAGIO, CENTRO_CUSTO, SEQUENCIA_ESTAGIO, ESTAGIO_ANTERIOR, ESTAGIO_DEPENDE, SEPARA_OPERACAO, MINUTOS_HOMEM, CCUSTO_HOMEM, NUMERO_CORDAS, NUMERO_ROLOS, VELOCIDADE, CODIGO_FAMILIA, OBSERVACAO, TIPO_PROCESSO, PECAS_1_HORA, PECAS_8_HORAS, CUSTO_MINUTO, PERC_EFICIENCIA, TEMPERATURA, TEMPO_LOTE_PRODUCAO, PECAS_LOTE_PRODUCAO, TIME_CELULA, CODIGO_APARELHO, PERC_EFIC_ROT, NUMERO_OPERADORAS, CONSIDERA_EFIC, SEQ_OPERACAO_AGRUPADORA, CODIGO_PARTE_PECA, SEQ_JUNCAO_PARTE_PECA, SITUACAO, PERC_PERDAS, PERC_CUSTOS, IND_ESTAGIO_GARGALO)
VALUES('1', '0617M', '000', '000000', 3, 3, 6, 21, 0, 21, 0, 2, 0, 0, NULL, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 1);
INSERT INTO SYSTEXTIL.MQOP_050
(NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRU_ESTRUTURA, ITEM_ESTRUTURA, NUMERO_ALTERNATI, NUMERO_ROTEIRO, SEQ_OPERACAO, CODIGO_OPERACAO, MINUTOS, CODIGO_ESTAGIO, CENTRO_CUSTO, SEQUENCIA_ESTAGIO, ESTAGIO_ANTERIOR, ESTAGIO_DEPENDE, SEPARA_OPERACAO, MINUTOS_HOMEM, CCUSTO_HOMEM, NUMERO_CORDAS, NUMERO_ROLOS, VELOCIDADE, CODIGO_FAMILIA, OBSERVACAO, TIPO_PROCESSO, PECAS_1_HORA, PECAS_8_HORAS, CUSTO_MINUTO, PERC_EFICIENCIA, TEMPERATURA, TEMPO_LOTE_PRODUCAO, PECAS_LOTE_PRODUCAO, TIME_CELULA, CODIGO_APARELHO, PERC_EFIC_ROT, NUMERO_OPERADORAS, CONSIDERA_EFIC, SEQ_OPERACAO_AGRUPADORA, CODIGO_PARTE_PECA, SEQ_JUNCAO_PARTE_PECA, SITUACAO, PERC_PERDAS, PERC_CUSTOS, IND_ESTAGIO_GARGALO)
VALUES('1', '0617M', '000', '000000', 3, 3, 10, 24, 0, 24, 0, 3, 0, 0, NULL, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 1);
INSERT INTO SYSTEXTIL.MQOP_050
(NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRU_ESTRUTURA, ITEM_ESTRUTURA, NUMERO_ALTERNATI, NUMERO_ROTEIRO, SEQ_OPERACAO, CODIGO_OPERACAO, MINUTOS, CODIGO_ESTAGIO, CENTRO_CUSTO, SEQUENCIA_ESTAGIO, ESTAGIO_ANTERIOR, ESTAGIO_DEPENDE, SEPARA_OPERACAO, MINUTOS_HOMEM, CCUSTO_HOMEM, NUMERO_CORDAS, NUMERO_ROLOS, VELOCIDADE, CODIGO_FAMILIA, OBSERVACAO, TIPO_PROCESSO, PECAS_1_HORA, PECAS_8_HORAS, CUSTO_MINUTO, PERC_EFICIENCIA, TEMPERATURA, TEMPO_LOTE_PRODUCAO, PECAS_LOTE_PRODUCAO, TIME_CELULA, CODIGO_APARELHO, PERC_EFIC_ROT, NUMERO_OPERADORAS, CONSIDERA_EFIC, SEQ_OPERACAO_AGRUPADORA, CODIGO_PARTE_PECA, SEQ_JUNCAO_PARTE_PECA, SITUACAO, PERC_PERDAS, PERC_CUSTOS, IND_ESTAGIO_GARGALO)
VALUES('1', '0617M', '000', '000000', 3, 3, 20, 54, 0, 54, 0, 4, 0, 0, NULL, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.MQOP_050
(NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRU_ESTRUTURA, ITEM_ESTRUTURA, NUMERO_ALTERNATI, NUMERO_ROTEIRO, SEQ_OPERACAO, CODIGO_OPERACAO, MINUTOS, CODIGO_ESTAGIO, CENTRO_CUSTO, SEQUENCIA_ESTAGIO, ESTAGIO_ANTERIOR, ESTAGIO_DEPENDE, SEPARA_OPERACAO, MINUTOS_HOMEM, CCUSTO_HOMEM, NUMERO_CORDAS, NUMERO_ROLOS, VELOCIDADE, CODIGO_FAMILIA, OBSERVACAO, TIPO_PROCESSO, PECAS_1_HORA, PECAS_8_HORAS, CUSTO_MINUTO, PERC_EFICIENCIA, TEMPERATURA, TEMPO_LOTE_PRODUCAO, PECAS_LOTE_PRODUCAO, TIME_CELULA, CODIGO_APARELHO, PERC_EFIC_ROT, NUMERO_OPERADORAS, CONSIDERA_EFIC, SEQ_OPERACAO_AGRUPADORA, CODIGO_PARTE_PECA, SEQ_JUNCAO_PARTE_PECA, SITUACAO, PERC_PERDAS, PERC_CUSTOS, IND_ESTAGIO_GARGALO)
VALUES('1', '0617M', '000', '000000', 3, 3, 30, 48, 0, 48, 0, 5, 0, 0, NULL, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.MQOP_050
(NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRU_ESTRUTURA, ITEM_ESTRUTURA, NUMERO_ALTERNATI, NUMERO_ROTEIRO, SEQ_OPERACAO, CODIGO_OPERACAO, MINUTOS, CODIGO_ESTAGIO, CENTRO_CUSTO, SEQUENCIA_ESTAGIO, ESTAGIO_ANTERIOR, ESTAGIO_DEPENDE, SEPARA_OPERACAO, MINUTOS_HOMEM, CCUSTO_HOMEM, NUMERO_CORDAS, NUMERO_ROLOS, VELOCIDADE, CODIGO_FAMILIA, OBSERVACAO, TIPO_PROCESSO, PECAS_1_HORA, PECAS_8_HORAS, CUSTO_MINUTO, PERC_EFICIENCIA, TEMPERATURA, TEMPO_LOTE_PRODUCAO, PECAS_LOTE_PRODUCAO, TIME_CELULA, CODIGO_APARELHO, PERC_EFIC_ROT, NUMERO_OPERADORAS, CONSIDERA_EFIC, SEQ_OPERACAO_AGRUPADORA, CODIGO_PARTE_PECA, SEQ_JUNCAO_PARTE_PECA, SITUACAO, PERC_PERDAS, PERC_CUSTOS, IND_ESTAGIO_GARGALO)
VALUES('1', '0617M', '000', '000000', 3, 3, 40, 57, 0, 57, 0, 6, 0, 0, NULL, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.MQOP_050
(NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRU_ESTRUTURA, ITEM_ESTRUTURA, NUMERO_ALTERNATI, NUMERO_ROTEIRO, SEQ_OPERACAO, CODIGO_OPERACAO, MINUTOS, CODIGO_ESTAGIO, CENTRO_CUSTO, SEQUENCIA_ESTAGIO, ESTAGIO_ANTERIOR, ESTAGIO_DEPENDE, SEPARA_OPERACAO, MINUTOS_HOMEM, CCUSTO_HOMEM, NUMERO_CORDAS, NUMERO_ROLOS, VELOCIDADE, CODIGO_FAMILIA, OBSERVACAO, TIPO_PROCESSO, PECAS_1_HORA, PECAS_8_HORAS, CUSTO_MINUTO, PERC_EFICIENCIA, TEMPERATURA, TEMPO_LOTE_PRODUCAO, PECAS_LOTE_PRODUCAO, TIME_CELULA, CODIGO_APARELHO, PERC_EFIC_ROT, NUMERO_OPERADORAS, CONSIDERA_EFIC, SEQ_OPERACAO_AGRUPADORA, CODIGO_PARTE_PECA, SEQ_JUNCAO_PARTE_PECA, SITUACAO, PERC_PERDAS, PERC_CUSTOS, IND_ESTAGIO_GARGALO)
VALUES('1', '0617M', '000', '000000', 3, 3, 50, 60, 0, 60, 0, 7, 0, 0, NULL, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.MQOP_050
(NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRU_ESTRUTURA, ITEM_ESTRUTURA, NUMERO_ALTERNATI, NUMERO_ROTEIRO, SEQ_OPERACAO, CODIGO_OPERACAO, MINUTOS, CODIGO_ESTAGIO, CENTRO_CUSTO, SEQUENCIA_ESTAGIO, ESTAGIO_ANTERIOR, ESTAGIO_DEPENDE, SEPARA_OPERACAO, MINUTOS_HOMEM, CCUSTO_HOMEM, NUMERO_CORDAS, NUMERO_ROLOS, VELOCIDADE, CODIGO_FAMILIA, OBSERVACAO, TIPO_PROCESSO, PECAS_1_HORA, PECAS_8_HORAS, CUSTO_MINUTO, PERC_EFICIENCIA, TEMPERATURA, TEMPO_LOTE_PRODUCAO, PECAS_LOTE_PRODUCAO, TIME_CELULA, CODIGO_APARELHO, PERC_EFIC_ROT, NUMERO_OPERADORAS, CONSIDERA_EFIC, SEQ_OPERACAO_AGRUPADORA, CODIGO_PARTE_PECA, SEQ_JUNCAO_PARTE_PECA, SITUACAO, PERC_PERDAS, PERC_CUSTOS, IND_ESTAGIO_GARGALO)
VALUES('1', '0617M', '000', '000000', 3, 3, 70, 63, 0, 63, 0, 8, 0, 0, NULL, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0);
INSERT INTO SYSTEXTIL.MQOP_050
(NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRU_ESTRUTURA, ITEM_ESTRUTURA, NUMERO_ALTERNATI, NUMERO_ROTEIRO, SEQ_OPERACAO, CODIGO_OPERACAO, MINUTOS, CODIGO_ESTAGIO, CENTRO_CUSTO, SEQUENCIA_ESTAGIO, ESTAGIO_ANTERIOR, ESTAGIO_DEPENDE, SEPARA_OPERACAO, MINUTOS_HOMEM, CCUSTO_HOMEM, NUMERO_CORDAS, NUMERO_ROLOS, VELOCIDADE, CODIGO_FAMILIA, OBSERVACAO, TIPO_PROCESSO, PECAS_1_HORA, PECAS_8_HORAS, CUSTO_MINUTO, PERC_EFICIENCIA, TEMPERATURA, TEMPO_LOTE_PRODUCAO, PECAS_LOTE_PRODUCAO, TIME_CELULA, CODIGO_APARELHO, PERC_EFIC_ROT, NUMERO_OPERADORAS, CONSIDERA_EFIC, SEQ_OPERACAO_AGRUPADORA, CODIGO_PARTE_PECA, SEQ_JUNCAO_PARTE_PECA, SITUACAO, PERC_PERDAS, PERC_CUSTOS, IND_ESTAGIO_GARGALO)
VALUES('1', '0617M', '000', '000000', 3, 3, 80, 66, 0, 66, 0, 9, 0, 0, NULL, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, 0, 0, 0, 0, 0);

-- -- -- -- --
SELECT
  t.*
FROM DBA_TABLES t
WHERE t.table_name like '%DBA%'
;

-- -- -- -- --
SELECT
  t.*
FROM dba_tab_columns t
JOIN dba_tab_columns t2
  ON t2.TABLE_NAME = t.TABLE_NAME
WHERE t.OWNER = 'SYSTEXTIL'
  AND t.COLUMN_NAME like '%ROTEIRO%'
  AND t2.OWNER = 'SYSTEXTIL'
  AND t2.COLUMN_NAME like '%DESCRICAO%'
;

-- pesquisa
SELECT
  *
FROM BASI_070 t
WHERE t.GRUPO = 'Z01PA'
;

-- apagar operações de roteiros antes de inserir
DELETE FROM MQOP_050 ro -- roteiro operações
WHERE ro.GRUPO_ESTRUTURA IN (
SELECT
  r.REFERENCIA
FROM basi_030 r -- referência
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND r.REFERENCIA < 'A'
  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
  AND rownum = 1
)
;

-- capa de roteiro
SELECT
  rc.NIVEL
, rc.GRUPO
, rc.ITEM
, rc.ROTEIRO
, rc.SUBGRUPO
, rc.ALTERNATIVA
, rc.DESCRICAO
, rc.LARGURA
, rc.GRAMATURA
, rc.RENDIMENTO
FROM BASI_070 rc -- roteiro capa
WHERE rc.NIVEL='1'
--  AND rc.GRUPO='Z01PA'
  AND rc.GRUPO='0617M'
--  AND rc.ITEM='000000'
--  AND rc.ROTEIRO=1
--  AND rc.SUBGRUPO='000'
--  AND rc.ALTERNATIVA=1
;

--
SELECT
  rc.NIVEL
, REF.REFERENCIA GRUPO
, rc.ITEM
, rc.ROTEIRO
, rc.SUBGRUPO
, rc.ALTERNATIVA
, rc.DESCRICAO
, rc.LARGURA
, rc.GRAMATURA
, rc.RENDIMENTO
FROM BASI_070 rc -- roteiro capa
,
(
SELECT
  r.*
FROM basi_030 r -- referência
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND r.REFERENCIA < 'A'
  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
  AND rownum = 1
) ref
WHERE rc.NIVEL='1'
  AND rc.GRUPO='Z01PA'
;

-- apagar capa de roteiro - onde define o nome dos roteiros das alternativas de referências
DELETE FROM BASI_070 rc -- roteiro operações
WHERE rc.GRUPO IN (
SELECT
  r.REFERENCIA
FROM basi_030 r -- referência
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND r.REFERENCIA < 'A'
  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
  AND rownum = 1
)
;

INSERT INTO SYSTEXTIL.BASI_070
(NIVEL, GRUPO, ITEM, ROTEIRO, SUBGRUPO, ALTERNATIVA, DESCRICAO, LARGURA, GRAMATURA, RENDIMENTO)
SELECT
  rc.NIVEL
, REF.REFERENCIA GRUPO
, rc.ITEM
, rc.ROTEIRO
, rc.SUBGRUPO
, rc.ALTERNATIVA
, rc.DESCRICAO
, rc.LARGURA
, rc.GRAMATURA
, rc.RENDIMENTO
FROM BASI_070 rc -- roteiro capa
,
(
SELECT
  r.*
FROM basi_030 r -- referência
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND r.REFERENCIA < 'A'
  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
  AND rownum = 1
) ref
WHERE rc.NIVEL='1'
  AND rc.GRUPO='Z01PA'
;

--
-- trabalhando as capas da segunda referência da seleção
--

SELECT
  rc.NIVEL
, rc.GRUPO
, rc.ITEM
, rc.ROTEIRO
, rc.SUBGRUPO
, rc.ALTERNATIVA
, rc.DESCRICAO
, rc.LARGURA
, rc.GRAMATURA
, rc.RENDIMENTO
FROM BASI_070 rc -- roteiro capa
WHERE rc.GRUPO IN (
	SELECT
	  REFERENCIA
	from
	(
		SELECT
		  rownum row_num
		, r.*
		FROM basi_030 r -- referência
		WHERE r.NIVEL_ESTRUTURA = 1
		  AND r.RESPONSAVEL IS NOT NULL
		  AND r.REFERENCIA < 'A'
		  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
	)
	WHERE row_num = 2
)
;

-- apagar capa de roteiro - onde define o nome dos roteiros das alternativas de referências
DELETE FROM BASI_070 rc -- roteiro operações
WHERE rc.GRUPO IN (
	SELECT
	  REFERENCIA
	from
	(
		SELECT
		  rownum row_num
		, r.*
		FROM basi_030 r -- referência
		WHERE r.NIVEL_ESTRUTURA = 1
		  AND r.RESPONSAVEL IS NOT NULL
		  AND r.REFERENCIA < 'A'
		  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
	)
	WHERE row_num = 2
)
;

INSERT INTO SYSTEXTIL.BASI_070
(NIVEL, GRUPO, ITEM, ROTEIRO, SUBGRUPO, ALTERNATIVA, DESCRICAO, LARGURA, GRAMATURA, RENDIMENTO)
SELECT
  rc.NIVEL
, REF.REFERENCIA GRUPO
, rc.ITEM
, rc.ROTEIRO
, rc.SUBGRUPO
, rc.ALTERNATIVA
, rc.DESCRICAO
, rc.LARGURA
, rc.GRAMATURA
, rc.RENDIMENTO
FROM BASI_070 rc -- roteiro capa
,
(
	SELECT
	  *
	from
	(
		SELECT
		  rownum row_num
		, r.*
		FROM basi_030 r -- referência
		WHERE r.NIVEL_ESTRUTURA = 1
		  AND r.RESPONSAVEL IS NOT NULL
		  AND r.REFERENCIA < 'A'
		  AND r.COLECAO IN (1, 2, 3, 4, 8, 13, 14, 15)
	)
	WHERE row_num = 2
) ref
WHERE rc.NIVEL='1'
  AND rc.GRUPO='Z01PA'
;

--
-- trabalhando as capas de todas as referências da seleção
--

-- produtos com roteiro alternativa 1 de PA
SELECT
  r.NIVEL_ESTRUTURA
, r.RESPONSAVEL
, r.REFERENCIA
, r.COLECAO
, r.*
FROM basi_030 r -- referência
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.RESPONSAVEL IS NOT NULL
  AND r.REFERENCIA < 'A'
  AND r.COLECAO IN (1, 2, 3, 4, 13, 14, 15)
ORDER BY
  r.REFERENCIA
;

-- seleciona capa de roteiro existente - onde define o nome dos roteiros das alternativas de referências
SELECT
  rc.NIVEL
, rc.GRUPO
, rc.ITEM
, rc.ROTEIRO
, rc.SUBGRUPO
, rc.ALTERNATIVA
, rc.DESCRICAO
, rc.LARGURA
, rc.GRAMATURA
, rc.RENDIMENTO
FROM BASI_070 rc -- roteiro capa
WHERE rc.GRUPO IN (
	SELECT
	  r.REFERENCIA
	FROM basi_030 r -- referência
	WHERE r.NIVEL_ESTRUTURA = 1
	  AND r.RESPONSAVEL IS NOT NULL
	  AND r.REFERENCIA < 'A'
	  AND r.COLECAO IN (1, 2, 3, 4, 13, 14, 15)
)
  AND rc.ROTEIRO IN (1, 3)
;

-- apagar capa de roteiro - onde define o nome dos roteiros das alternativas de referências
DELETE FROM BASI_070 rc -- capa de roteiro
WHERE rc.GRUPO IN (
	SELECT
	  r.REFERENCIA
	FROM basi_030 r -- referência
	WHERE r.NIVEL_ESTRUTURA = 1
	  AND r.RESPONSAVEL IS NOT NULL
	  AND r.REFERENCIA < 'A'
	  AND r.COLECAO IN (1, 2, 3, 4, 13, 14, 15)
)
  AND rc.ROTEIRO IN (1, 3)
;

-- inserir capa de roteiro - onde define o nome dos roteiros das alternativas de referências
INSERT INTO SYSTEXTIL.BASI_070
(NIVEL, GRUPO, ITEM, ROTEIRO, SUBGRUPO, ALTERNATIVA, DESCRICAO, LARGURA, GRAMATURA, RENDIMENTO)
SELECT
  rc.NIVEL
, REF.REFERENCIA GRUPO
, rc.ITEM
, rc.ROTEIRO
, rc.SUBGRUPO
, rc.ALTERNATIVA
, rc.DESCRICAO
, rc.LARGURA
, rc.GRAMATURA
, rc.RENDIMENTO
FROM BASI_070 rc -- roteiro capa
,
(
	SELECT
	  r.REFERENCIA
	FROM basi_030 r -- referência
	WHERE r.NIVEL_ESTRUTURA = 1
	  AND r.RESPONSAVEL IS NOT NULL
	  AND r.REFERENCIA < 'A'
	  AND r.COLECAO IN (1, 2, 3, 4, 13, 14, 15)
) ref
WHERE rc.NIVEL='1'
  AND rc.GRUPO='Z01PA'
  AND rc.ROTEIRO IN (1, 3)
;

--
-- trabalhando as lista de operações (roteiro) de uma alternativa de produto
--

-- verifica gargalos
SELECT
  rotp.GRUPO_ESTRUTURA
, rotp.NUMERO_ROTEIRO
, rotp.SEQ_OPERACAO
, rotp.IND_ESTAGIO_GARGALO
, rotp.CODIGO_OPERACAO
, rotp.NIVEL_ESTRUTURA
, rotp.SUBGRU_ESTRUTURA
, rotp.ITEM_ESTRUTURA
, rotp.NUMERO_ALTERNATI
FROM SYSTEXTIL.MQOP_050 rotp
WHERE rotp.GRUPO_ESTRUTURA='Z01PA'
--  AND rotp.NUMERO_ROTEIRO=1
ORDER BY
  rotp.GRUPO_ESTRUTURA
, rotp.NUMERO_ROTEIRO
, rotp.SEQ_OPERACAO
;

-- seleciona lista de operações (roteiro) de uma alternativa de produto
SELECT
  rop.NIVEL_ESTRUTURA
, rop.GRUPO_ESTRUTURA
, rop.SUBGRU_ESTRUTURA
, rop.ITEM_ESTRUTURA
, rop.NUMERO_ALTERNATI
, rop.NUMERO_ROTEIRO
, rop.SEQ_OPERACAO
, rop.CODIGO_OPERACAO
, rop.MINUTOS
, rop.CODIGO_ESTAGIO
, rop.CENTRO_CUSTO
, rop.SEQUENCIA_ESTAGIO
, rop.ESTAGIO_ANTERIOR
, rop.ESTAGIO_DEPENDE
, rop.SEPARA_OPERACAO
, rop.MINUTOS_HOMEM
, rop.CCUSTO_HOMEM
, rop.NUMERO_CORDAS
, rop.NUMERO_ROLOS
, rop.VELOCIDADE
, rop.CODIGO_FAMILIA
, rop.OBSERVACAO
, rop.TIPO_PROCESSO
, rop.PECAS_1_HORA
, rop.PECAS_8_HORAS
, rop.CUSTO_MINUTO
, rop.PERC_EFICIENCIA
, rop.TEMPERATURA
, rop.TEMPO_LOTE_PRODUCAO
, rop.PECAS_LOTE_PRODUCAO
, rop.TIME_CELULA
, rop.CODIGO_APARELHO
, rop.PERC_EFIC_ROT
, rop.NUMERO_OPERADORAS
, rop.CONSIDERA_EFIC
, rop.SEQ_OPERACAO_AGRUPADORA
, rop.CODIGO_PARTE_PECA
, rop.SEQ_JUNCAO_PARTE_PECA
, rop.SITUACAO
, rop.PERC_PERDAS
, rop.PERC_CUSTOS
, rop.IND_ESTAGIO_GARGALO
FROM MQOP_050 rop
WHERE rop.GRUPO_ESTRUTURA IN (
	SELECT
	  r.REFERENCIA
	FROM basi_030 r -- referência
	WHERE r.NIVEL_ESTRUTURA = 1
	  AND r.RESPONSAVEL IS NOT NULL
	  AND r.REFERENCIA < 'A'
	  AND r.COLECAO IN (1, 2, 3, 4, 13, 14, 15)
)
  AND rop.NUMERO_ROTEIRO IN (1, 3)
ORDER BY
  rop.GRUPO_ESTRUTURA
, rop.NUMERO_ROTEIRO
, rop.SEQ_OPERACAO
;

-- apagar lista de operações (roteiro) de uma alternativa de produto
DELETE FROM MQOP_050 rop -- lista de operações de um roteiro
WHERE rop.GRUPO_ESTRUTURA IN (
	SELECT
	  r.REFERENCIA
	FROM basi_030 r -- referência
	WHERE r.NIVEL_ESTRUTURA = 1
	  AND r.RESPONSAVEL IS NOT NULL
	  AND r.REFERENCIA < 'A'
	  AND r.COLECAO IN (1, 2, 3, 4, 13, 14, 15)
)
  AND rop.NUMERO_ROTEIRO IN (1, 3)
;

-- inserir capa de roteiro - onde define o nome dos roteiros das alternativas de referências
INSERT INTO MQOP_050
(NIVEL_ESTRUTURA, GRUPO_ESTRUTURA, SUBGRU_ESTRUTURA, ITEM_ESTRUTURA, NUMERO_ALTERNATI, NUMERO_ROTEIRO, SEQ_OPERACAO, CODIGO_OPERACAO, MINUTOS, CODIGO_ESTAGIO, CENTRO_CUSTO, SEQUENCIA_ESTAGIO, ESTAGIO_ANTERIOR, ESTAGIO_DEPENDE, SEPARA_OPERACAO, MINUTOS_HOMEM, CCUSTO_HOMEM, NUMERO_CORDAS, NUMERO_ROLOS, VELOCIDADE, CODIGO_FAMILIA, OBSERVACAO, TIPO_PROCESSO, PECAS_1_HORA, PECAS_8_HORAS, CUSTO_MINUTO, PERC_EFICIENCIA, TEMPERATURA, TEMPO_LOTE_PRODUCAO, PECAS_LOTE_PRODUCAO, TIME_CELULA, CODIGO_APARELHO, PERC_EFIC_ROT, NUMERO_OPERADORAS, CONSIDERA_EFIC, SEQ_OPERACAO_AGRUPADORA, CODIGO_PARTE_PECA, SEQ_JUNCAO_PARTE_PECA, SITUACAO, PERC_PERDAS, PERC_CUSTOS, IND_ESTAGIO_GARGALO)
SELECT
  rop.NIVEL_ESTRUTURA
, REF.REFERENCIA GRUPO_ESTRUTURA
, rop.SUBGRU_ESTRUTURA
, rop.ITEM_ESTRUTURA
, rop.NUMERO_ALTERNATI
, rop.NUMERO_ROTEIRO
, rop.SEQ_OPERACAO
, rop.CODIGO_OPERACAO
, rop.MINUTOS
, rop.CODIGO_ESTAGIO
, rop.CENTRO_CUSTO
, rop.SEQUENCIA_ESTAGIO
, rop.ESTAGIO_ANTERIOR
, rop.ESTAGIO_DEPENDE
, rop.SEPARA_OPERACAO
, rop.MINUTOS_HOMEM
, rop.CCUSTO_HOMEM
, rop.NUMERO_CORDAS
, rop.NUMERO_ROLOS
, rop.VELOCIDADE
, rop.CODIGO_FAMILIA
, rop.OBSERVACAO
, rop.TIPO_PROCESSO
, rop.PECAS_1_HORA
, rop.PECAS_8_HORAS
, rop.CUSTO_MINUTO
, rop.PERC_EFICIENCIA
, rop.TEMPERATURA
, rop.TEMPO_LOTE_PRODUCAO
, rop.PECAS_LOTE_PRODUCAO
, rop.TIME_CELULA
, rop.CODIGO_APARELHO
, rop.PERC_EFIC_ROT
, rop.NUMERO_OPERADORAS
, rop.CONSIDERA_EFIC
, rop.SEQ_OPERACAO_AGRUPADORA
, rop.CODIGO_PARTE_PECA
, rop.SEQ_JUNCAO_PARTE_PECA
, rop.SITUACAO
, rop.PERC_PERDAS
, rop.PERC_CUSTOS
, rop.IND_ESTAGIO_GARGALO
FROM MQOP_050 rop
,
(
	SELECT
	  r.REFERENCIA
	FROM basi_030 r -- referência
	WHERE r.NIVEL_ESTRUTURA = 1
	  AND r.RESPONSAVEL IS NOT NULL
	  AND r.REFERENCIA < 'A'
	  AND r.COLECAO IN (1, 2, 3, 4, 13, 14, 15)
) ref
WHERE rop.NIVEL_ESTRUTURA = '1'
  AND rop.GRUPO_ESTRUTURA = 'Z01PA'
  AND rop.NUMERO_ROTEIRO IN (1, 3)
;
