SELECT
  l.ORDEM_PRODUCAO OP
, count(DISTINCT NUMERO_ORDEM) OS
FROM pcpc_040 l
--WHERE l.NUMERO_ORDEM = 134
GROUP BY
  l.ORDEM_PRODUCAO
;

SELECT
  l.NUMERO_ORDEM OS
, count(l.ORDEM_CONFECCAO) LOTES
, sum(l.QTDE_PECAS_PROG) QTD
FROM pcpc_040 l
WHERE l.ORDEM_PRODUCAO = 309
  AND l.NUMERO_ORDEM <> 0
GROUP BY
  l.NUMERO_ORDEM
ORDER BY
  l.NUMERO_ORDEM
;

SELECT
  l.NUMERO_ORDEM OS
, count(DISTINCT l.ORDEM_PRODUCAO) OP
FROM pcpc_040 l
--WHERE l.NUMERO_ORDEM = 134
GROUP BY
  l.NUMERO_ORDEM
ORDER BY
  2 DESC
;

        SELECT
 		  l.ORDEM_PRODUCAO
        , CASE WHEN dos.NUMERO_ORDEM IS NULL
          THEN '0'
          ELSE l.NUMERO_ORDEM || ' (' || eos.DESCRICAO || ')'
          END OS
        , l.PROCONF_GRUPO REF
        , l.PROCONF_SUBGRUPO TAM
        , l.PROCONF_ITEM COR
        , COALESCE(
          ( SELECT
              LISTAGG(le.CODIGO_ESTAGIO || ' - ' || ed.DESCRICAO, ' & ')
              WITHIN GROUP (ORDER BY le.CODIGO_ESTAGIO)
            FROM PCPC_040 le
            JOIN MQOP_005 ed
              ON ed.CODIGO_ESTAGIO = le.CODIGO_ESTAGIO
            WHERE le.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
              AND le.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
              AND le.QTDE_EM_PRODUCAO_PACOTE <> 0
          )
          , 'FINALIZADO'
          ) EST
        , l.PERIODO_PRODUCAO PERIODO
        , l.ORDEM_CONFECCAO OC
        , l.QTDE_PROGRAMADA QTD
        FROM (
          SELECT
            os.PERIODO_PRODUCAO
          , os.ORDEM_CONFECCAO
          , os.PROCONF_GRUPO
          , os.PROCONF_SUBGRUPO
          , os.PROCONF_ITEM
          , os.ORDEM_PRODUCAO
          , max( os.NUMERO_ORDEM ) NUMERO_ORDEM
          , max( os.QTDE_PROGRAMADA ) QTDE_PROGRAMADA
          FROM PCPC_040 os
          WHERE 1=1
            --AND os.ORDEM_PRODUCAO = 288
            AND os.NUMERO_ORDEM = 238
          GROUP BY
            os.PERIODO_PRODUCAO
          , os.ORDEM_CONFECCAO
          , os.PROCONF_GRUPO
          , os.PROCONF_SUBGRUPO
          , os.PROCONF_ITEM
          , os.ORDEM_PRODUCAO
        ) l
        LEFT JOIN PCPC_040 dos
          ON l.NUMERO_ORDEM <> 0
         AND dos.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
         AND dos.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
         AND dos.NUMERO_ORDEM = l.NUMERO_ORDEM
        LEFT JOIN MQOP_005 eos
          ON eos.CODIGO_ESTAGIO = dos.CODIGO_ESTAGIO
        LEFT JOIN BASI_220 t
          ON t.TAMANHO_REF = l.PROCONF_SUBGRUPO
        ORDER BY
          l.ORDEM_PRODUCAO
        , l.NUMERO_ORDEM
        , l.PROCONF_GRUPO
        , l.PROCONF_ITEM
        , t.ORDEM_TAMANHO
        , l.PERIODO_PRODUCAO
        , l.ORDEM_CONFECCAO
;


        SELECT
          os.NUMERO_ORDEM OS
        , os.CODIGO_SERVICO || '-' || s.DESC_TERCEIRO SERV
        , os.CGCTERC_FORNE9 CNPJ9
        , os.CGCTERC_FORNE4 CNPJ4
        , os.CGCTERC_FORNE2 CNPJ2
        , f.NOME_FANTASIA NOME
        , CASE os.SITUACAO_ORDEM
          WHEN 1 THEN '1-Aberta'
          WHEN 2 THEN '2-Em Processo'
          WHEN 3 THEN '3-Baixa Parcial'
          WHEN 4 THEN '4-Baixa Total'
          ELSE '-'
          END SITUACAO
        , os.COD_CANC_ORDEM || '-' || c.DESCR_CANC_ORDEM CANC
        , count(l.ORDEM_CONFECCAO) LOTES
        , sum(l.QTDE_PECAS_PROG) QTD
        FROM OBRF_080 os
        JOIN OBRF_070 s
          ON s.CODIGO_TERCEIRO = os.CODIGO_SERVICO
        JOIN SUPR_010 f
          ON f.FORNECEDOR9 = os.CGCTERC_FORNE9
         AND f.FORNECEDOR4 = os.CGCTERC_FORNE4
        JOIN OBRF_087 c
          ON c.COD_CANC_ORDEM = os.COD_CANC_ORDEM
        JOIN pcpc_040 l
          ON l.NUMERO_ORDEM = os.NUMERO_ORDEM
        WHERE 1=1
          AND (os.NUMERO_ORDEM = 239 OR 0=0)
          AND (l.PERIODO_PRODUCAO = 1719 OR 0=0)
          AND (l.ORDEM_CONFECCAO = 03600 OR 0=0)
          AND (l.ORDEM_PRODUCAO = 120 OR 0=10)
          AND l.NUMERO_ORDEM <> 0
        GROUP BY
          os.NUMERO_ORDEM
        , os.CODIGO_SERVICO
        , s.DESC_TERCEIRO
        , os.CGCTERC_FORNE9
        , os.CGCTERC_FORNE4
        , os.CGCTERC_FORNE2
        , f.NOME_FANTASIA
        , os.SITUACAO_ORDEM
        , os.COD_CANC_ORDEM
        , c.DESCR_CANC_ORDEM
        ORDER BY
          os.NUMERO_ORDEM
;


        SELECT
          ll.EST
        , (SELECT
              cast( SUM( lp.QTDE_PECAS_PROD ) / SUM( lp.QTDE_PECAS_PROG ) * 100
                    AS NUMERIC(10,2) )
            FROM pcpc_040 lp
            WHERE lp.ORDEM_PRODUCAO = ll.ORDEM_PRODUCAO
              AND lp.SEQ_OPERACAO = ll.SEQ_OPERACAO
          ) PERC
        , (SELECT
              SUM( lp.QTDE_PECAS_PROD )
            FROM pcpc_040 lp
            WHERE lp.ORDEM_PRODUCAO = ll.ORDEM_PRODUCAO
              AND lp.SEQ_OPERACAO = ll.SEQ_OPERACAO
          ) PROD
        , (SELECT
              count(*)
            FROM pcpc_040 lp
            WHERE lp.ORDEM_PRODUCAO = ll.ORDEM_PRODUCAO
              AND lp.SEQ_OPERACAO = ll.SEQ_OPERACAO
              AND lp.QTDE_EM_PRODUCAO_PACOTE <> 0
          ) LOTES
        FROM
        (
        SELECT DISTINCT
          l.ORDEM_PRODUCAO
        , l.SEQ_OPERACAO
        , l.CODIGO_ESTAGIO || ' - ' || e.DESCRICAO EST
        FROM pcpc_040 l
        JOIN MQOP_005 e
          ON e.CODIGO_ESTAGIO = l.CODIGO_ESTAGIO
        WHERE l.ORDEM_PRODUCAO = 1046
        ORDER BY
          l.SEQ_OPERACAO
        ) ll
;


SELECT
  i.TAMANHO
, i.SORTIMENTO
, i.QUANTIDADE
, i.*
FROM PCPC_021 i
WHERE i.ORDEM_PRODUCAO = 1536
ORDER BY
  i.SEQUENCIA_TAMANHO
, i.SORTIMENTO
;

SELECT DISTINCT
  i.TAMANHO
, i.SEQUENCIA_TAMANHO
FROM PCPC_021 i
WHERE i.ORDEM_PRODUCAO = 1536
ORDER BY
  i.SEQUENCIA_TAMANHO
;

SELECT
  i.SORTIMENTO
, max( p.DESCRICAO_15 ) DESCR
FROM PCPC_021 i
JOIN pcpc_020 op
  ON op.ORDEM_PRODUCAO = i.ORDEM_PRODUCAO
LEFT JOIN basi_010 p
  ON p.NIVEL_ESTRUTURA = 1
 AND p.GRUPO_ESTRUTURA = op.REFERENCIA_PECA
 AND p.ITEM_ESTRUTURA = i.SORTIMENTO
WHERE i.ORDEM_PRODUCAO = 1536
GROUP BY
  i.SORTIMENTO
ORDER BY
  2
;

SELECT
  *
FROM BASI_010
;

UPDATE pcpc_040 l
SET
  l.NUMERO_ORDEM = 0
, l.SEQ_ORDEM_SERV = 0

SELECT DISTINCT
  l.ORDEM_PRODUCAO
, l.NUMERO_ORDEM
, l.SEQ_ORDEM_SERV
, l.PERIODO_PRODUCAO
, l.ORDEM_CONFECCAO
, l.*
FROM pcpc_040 l
WHERE 1=1
  --AND l.ORDEM_PRODUCAO = 297
  AND l.NUMERO_ORDEM = 595
  --AND l.CODIGO_ESTAGIO = 39
  AND l.PERIODO_PRODUCAO = 1727
  AND l.ORDEM_CONFECCAO IN (
    7900
  , 7814
  --, 4096
  )
  AND l.NUMERO_ORDEM <> 0
  AND l.SEQ_ORDEM_SERV <> 0
;

SELECT
  DISTINCT
  s.PRODSAI_NIVEL99
, s.PRODSAI_GRUPO
, s.PRODSAI_SUBGRUPO
, s.PRODSAI_ITEM
, s.*
FROM OBRF_082 s
WHERE s.NUMERO_ORDEM = 589
ORDER BY
  s.SEQUENCIA
, s.PRODSAI_NIVEL99
, s.PRODSAI_GRUPO
, s.PRODSAI_SUBGRUPO
, s.PRODSAI_ITEM
;

SELECT
  s.PRODORD_NIVEL99
, s.PRODORD_GRUPO
, s.PRODORD_SUBGRUPO
, s.PRODORD_ITEM
, s.*
FROM OBRF_081 s
WHERE s.NUMERO_ORDEM = 589
ORDER BY
  s.PRODORD_NIVEL99
, s.PRODORD_GRUPO
, s.PRODORD_SUBGRUPO
, s.PRODORD_ITEM
;

SELECT DISTINCT
  s.PRODORD_SUBGRUPO
, tam.ORDEM_TAMANHO
FROM OBRF_081 s
LEFT JOIN BASI_220 tam
  ON tam.TAMANHO_REF = s.PRODORD_SUBGRUPO
WHERE s.NUMERO_ORDEM = 589
ORDER BY
  tam.ORDEM_TAMANHO
;

SELECT
  s.PRODORD_GRUPO || ' - ' || s.PRODORD_ITEM SORTIMENTO
, s.PRODORD_GRUPO || ' - ' || s.PRODORD_ITEM || ' - ' || max( p.DESCRICAO_15 ) DESCR
FROM OBRF_081 s
LEFT JOIN basi_010 p
  ON p.NIVEL_ESTRUTURA = 1
 AND p.GRUPO_ESTRUTURA = s.PRODORD_GRUPO
 AND p.ITEM_ESTRUTURA = s.PRODORD_ITEM
WHERE s.NUMERO_ORDEM = 589
GROUP BY
  s.PRODORD_GRUPO
, s.PRODORD_ITEM
ORDER BY
  2
;

SELECT
  s.PRODORD_GRUPO || ' - ' || s.PRODORD_ITEM SORTIMENTO
, s.PRODORD_SUBGRUPO TAMANHO
, s.QTDE_ARECEBER QUANTIDADE
FROM OBRF_081 s
WHERE s.NUMERO_ORDEM = 463
ORDER BY
  s.PRODORD_NIVEL99
, s.PRODORD_GRUPO
, s.PRODORD_SUBGRUPO
, s.PRODORD_ITEM
;

SELECT
  os.NUMERO_ORDEM OS
, count(DISTINCT os.ORDEM_PRODUCAO) OP
FROM PCPC_040 os
GROUP BY
  os.NUMERO_ORDEM
ORDER BY
  2 DESC
;

        SELECT DISTINCT
          os.NUMERO_ORDEM OS
        , os.CODIGO_SERVICO
        , os.CGCTERC_FORNE9 CNPJ9
        , os.CGCTERC_FORNE4 CNPJ4
        , os.CGCTERC_FORNE2 CNPJ2
        , CASE os.SITUACAO_ORDEM
          WHEN 1 THEN '1-Aberta'
          WHEN 2 THEN '2-Em Processo'
          WHEN 3 THEN '3-Baixa Parcial'
          WHEN 4 THEN '4-Baixa Total'
          ELSE '-'
          END SITUACAO
        , os.COD_CANC_ORDEM
        , os.data_emissao
        , os.
        FROM OBRF_080 os
        WHERE os.NUMERO_ORDEM = 589
;

SELECT
  x.CODIGO_ROLO
, x.ORDEM_PRODUCAO
, x.ROLO_ESTOQUE
, x.*
FROM PCPT_020 x -- cadastro de rolos
WHERE 1=1
  AND x.PANOACAB_GRUPO = 'MA004'
--  AND x.ORDEM_PRODUCAO <> 0
--  AND x.CODIGO_ROLO = 370
--WHERE x.NUMERO_ROLO = 8080
--   OR x.NUMERO_LOTE = 8080
--   OR x.NR_VOLUME = 8080
--   OR x.NR_SOLIC_VOLUME = 8080
--   OR x.NUMERO_PROGRAMA = 8080
--   OR x.NR_ROLO_ORIGEM = 8080
--   OR x.NUMERO_TUBETE = 8080
ORDER BY
  x.CODIGO_ROLO
;


SELECT
  x.*
FROM PCPT_021 x -- rolos - informações não utilizadas
WHERE 1=1
;

SELECT
  x.*
FROM PCPT_060 x -- faturamento de rolo - porém, quase nenhum dado
WHERE 1=1
;

SELECT
  x.*
FROM PCPT_025 x -- confirmação de rolo
--WHERE x.PANO_INI_GRUPO = 'MA004'
--  AND x.ORDEM_PRODUCAO <> 0
--  AND x.CODIGO_ROLO = 3648
--   OR x.NUMROLO_PER_TECE = 8080
--   OR x.NUMROLO_PER_TECE = 8080
--   OR x.NUMROLO_PER_TECE = 8080
--   OR x.NUMROLO_PER_TECE = 8080
;

SELECT
  x.GRUPO_PRODUTO
, x.ORDEM_PRODUCAO
, x.*
FROM TMRP_141 x -- reserva de rolo para OP
WHERE 1=1
  AND x.GRUPO_PRODUTO = 'MA005'
--  AND x.CODIGO_ROLO = 3648
--  AND x.ORDEM_PRODUCAO <> 0
;


SELECT
  x.*
FROM PCPT_020 x -- cadastro de rolos
WHERE x.PANOACAB_GRUPO = 'MA004'
  AND x.ROLO_ESTOQUE = 3
;

UPDATE PCPT_020 x -- cadastro de rolos
SET
x.ROLO_ESTOQUE = 1
WHERE x.PANOACAB_GRUPO = 'MA004'
  AND x.ROLO_ESTOQUE = 3
;

SELECT
  x.*
FROM TMRP_141 x -- reserva de rolo para OP
WHERE x.GRUPO_PRODUTO = 'MA004'
;

SELECT
  i.CODIGO_BARRAS
, i.*
FROM BASI_010 i
WHERE i.GRUPO_ESTRUTURA = '0679A'
  AND i.CODIGO_BARRAS IS NOT NULL
;

MERGE INTO BASI_010 dest
USING(
	SELECT
	  ori.*
	FROM BASI_010 ori
	WHERE ori.GRUPO_ESTRUTURA = '0679A'
	  AND ori.CODIGO_BARRAS IS NOT NULL
	) orig
ON (dest.NIVEL_ESTRUTURA = orig.NIVEL_ESTRUTURA
AND dest.GRUPO_ESTRUTURA = '0679O'
AND dest.SUBGRU_ESTRUTURA = orig.SUBGRU_ESTRUTURA
AND dest.ITEM_ESTRUTURA = orig.ITEM_ESTRUTURA
)
WHEN MATCHED THEN
    update set dest.CODIGO_BARRAS = orig.CODIGO_BARRAS
--WHEN NOT MATCHED THEN
--    insert (xyz) values (orig.xyz)
;

SELECT
  i.CODIGO_BARRAS
, i.*
FROM BASI_010 i
WHERE i.GRUPO_ESTRUTURA IN ( '0679A', '0679O')
  AND i.CODIGO_BARRAS IS NOT NULL
ORDER BY
  i.SUBGRU_ESTRUTURA
, i.ITEM_ESTRUTURA
, i.GRUPO_ESTRUTURA
;

SELECT
  count(*)
FROM HIST_010 h
;

SELECT
  h.*
FROM HIST_010 h
;


SELECT
  i.CODIGO_BARRAS
, i.*
FROM BASI_010 i
WHERE i.GRUPO_ESTRUTURA = 'M761R'
  AND i.CODIGO_BARRAS IS NOT NULL
;

MERGE INTO BASI_010 dest
USING(
	SELECT
	  ori.*
	FROM BASI_010 ori
	WHERE ori.GRUPO_ESTRUTURA = 'M761R'
	  AND ori.CODIGO_BARRAS IS NOT NULL
	) orig
ON (dest.NIVEL_ESTRUTURA = orig.NIVEL_ESTRUTURA
AND dest.GRUPO_ESTRUTURA = '7611U'
AND dest.SUBGRU_ESTRUTURA = orig.SUBGRU_ESTRUTURA
AND dest.ITEM_ESTRUTURA = orig.ITEM_ESTRUTURA
)
WHEN MATCHED THEN
    update set dest.CODIGO_BARRAS = orig.CODIGO_BARRAS
--WHEN NOT MATCHED THEN
--    insert (xyz) values (orig.xyz)
;

SELECT
  i.CODIGO_BARRAS
, i.*
FROM BASI_010 i
WHERE i.GRUPO_ESTRUTURA IN ( 'M761R', '7611U')
  AND i.CODIGO_BARRAS IS NOT NULL
ORDER BY
  i.SUBGRU_ESTRUTURA
, i.ITEM_ESTRUTURA
, i.GRUPO_ESTRUTURA
;

SELECT
  x.CODIGO_ROLO
, x.PANOACAB_NIVEL99
, x.PANOACAB_GRUPO
, x.PANOACAB_SUBGRUPO
, x.PANOACAB_ITEM
FROM PCPT_020 x -- cadastro de rolos
WHERE x.CODIGO_ROLO = 253
;

SELECT
  i.*
FROM basi_010 i
WHERE i.DESCRICAO_15 LIKE '%ROYAL%'
  AND i.ITEM_ESTRUTURA = '0000AZ'
ORDER BY
  i.NIVEL_ESTRUTURA
, i.DESCRICAO_15
;


SELECT
*
FROM dba_locks
;

SELECT
  o.*
FROM OBRF_080 o
WHERE o.NUMERO_ORDEM = 1391
;

DELETE
FROM OBRF_080 o
WHERE o.NUMERO_ORDEM = 1391
;

SELECT DISTINCT
  l.*
FROM pcpc_040 l -- lotes nos estágios
WHERE l.NUMERO_ORDEM = 1391
;

UPDATE pcpc_040 l -- lotes nos estágios
SET
  l.NUMERO_ORDEM = 0
WHERE l.NUMERO_ORDEM = 1391
;

SELECT DISTINCT
  l.*
FROM pcpc_040 l -- lotes nos estágios
WHERE l.ORDEM_PRODUCAO = 3596
;

SELECT
  i.CODIGO_BARRAS
, i.*
FROM BASI_010 i
WHERE i.GRUPO_ESTRUTURA = '05200'
  AND i.ITEM_ESTRUTURA = '0000ME'
--  AND i.CODIGO_BARRAS IS NOT NULL
;


SELECT
  op.DATA_ENTRADA_CORTE
, op.*
FROM PCPC_020 op -- OP capa
WHERE op.ORDEM_PRODUCAO = 2004
;

SELECT
  op.d
, COALESCE(
  ( SELECT
      MIN( le.CODIGO_ESTAGIO ) CODIGO_ESTAGIO
    FROM PCPC_040 le
    JOIN MQOP_005 ed
      ON ed.CODIGO_ESTAGIO = le.CODIGO_ESTAGIO
    WHERE le.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
      AND le.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
      AND le.QTDE_EM_PRODUCAO_PACOTE <> 0
  )
  , 9999
  ) EST_NUM
, l.ORDEM_PRODUCAO OP
, op.SITUACAO OP_SITUACAO
, CASE WHEN dos.NUMERO_ORDEM IS NULL
  THEN '0'
  ELSE l.NUMERO_ORDEM || ' (' || eos.DESCRICAO || ')'
  END OS
, l.PROCONF_GRUPO REF
, l.PROCONF_SUBGRUPO TAM
, l.PROCONF_ITEM COR
, COALESCE(
  ( SELECT
      LISTAGG(le.CODIGO_ESTAGIO || ' - ' || ed.DESCRICAO, ' & ')
      WITHIN GROUP (ORDER BY le.CODIGO_ESTAGIO)
    FROM PCPC_040 le
    JOIN MQOP_005 ed
      ON ed.CODIGO_ESTAGIO = le.CODIGO_ESTAGIO
    WHERE le.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
      AND le.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
      AND le.QTDE_EM_PRODUCAO_PACOTE <> 0
  )
  , 'FINALIZADO'
  ) EST
, l.PERIODO_PRODUCAO PERIODO
, l.ORDEM_CONFECCAO OC
, l.QTDE_PECAS_PROG QTD
, l.QTDE_PECAS_PROD PROD1Q
, l.QTDE_CONSERTO CONSERTO
, l.QTDE_PECAS_2A PROD2Q
, l.QTDE_PERDAS PERDA
, r.NARRATIVA
, CASE WHEN l.DIVISAO = 0 THEN dp.DIVISAO_PRODUCAO
  ELSE l.DIVISAO END DIVISAO
, CASE WHEN l.DIVISAO = 0 THEN dp.DESCRICAO
  ELSE di.DESCRICAO END DESCRICAO_DIVISAO
FROM (
  SELECT
    os.PERIODO_PRODUCAO
  , os.ORDEM_CONFECCAO
  , os.PROCONF_GRUPO
  , os.PROCONF_SUBGRUPO
  , os.PROCONF_ITEM
  , os.ORDEM_PRODUCAO
  , max( os.NUMERO_ORDEM ) NUMERO_ORDEM
  , max( os.QTDE_PECAS_PROG ) QTDE_PECAS_PROG
  , max( os.QTDE_PECAS_PROD ) QTDE_PECAS_PROD
  , max( os.QTDE_CONSERTO ) QTDE_CONSERTO
  , max( os.QTDE_PECAS_2A ) QTDE_PECAS_2A
  , max( os.QTDE_PERDAS ) QTDE_PERDAS
  , max( CASE WHEN os.CODIGO_FAMILIA < 1000
         THEN os.CODIGO_FAMILIA
         ELSE 0 END ) DIVISAO
  FROM PCPC_040 os
  WHERE 1=1
    AND (os.ORDEM_PRODUCAO = 2004)
--    AND (os.NUMERO_ORDEM = %s or %s IS NULL)
--    AND (os.ORDEM_CONFECCAO >= %s or %s IS NULL)
--    AND (os.ORDEM_CONFECCAO <= %s or %s IS NULL)
--    AND (os.PROCONF_SUBGRUPO = %s OR %s IS NULL)
--    AND (os.PROCONF_ITEM = %s OR %s IS NULL)
  GROUP BY
    os.PERIODO_PRODUCAO
  , os.ORDEM_CONFECCAO
  , os.PROCONF_GRUPO
  , os.PROCONF_SUBGRUPO
  , os.PROCONF_ITEM
  , os.ORDEM_PRODUCAO
) l
LEFT JOIN PCPC_040 dos
  ON l.NUMERO_ORDEM <> 0
 AND dos.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
 AND dos.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
 AND dos.NUMERO_ORDEM = l.NUMERO_ORDEM
LEFT JOIN MQOP_005 eos
  ON eos.CODIGO_ESTAGIO = dos.CODIGO_ESTAGIO
LEFT JOIN BASI_220 t
  ON t.TAMANHO_REF = l.PROCONF_SUBGRUPO
JOIN BASI_010 r
  ON r.NIVEL_ESTRUTURA = 1
 AND r.GRUPO_ESTRUTURA = l.PROCONF_GRUPO
 AND r.SUBGRU_ESTRUTURA = l.PROCONF_SUBGRUPO
 AND r.ITEM_ESTRUTURA = l.PROCONF_ITEM
LEFT JOIN BASI_180 di -- divisao de producao - unidade
  ON di.DIVISAO_PRODUCAO = l.DIVISAO
LEFT JOIN OBRF_080 osc -- OS capa
  ON l.NUMERO_ORDEM <> 0
 AND osc.NUMERO_ORDEM = l.NUMERO_ORDEM
LEFT JOIN BASI_180 dp -- divisao de producao - unidade
  ON dp.FACCIONISTA9 = osc.CGCTERC_FORNE9
 AND dp.FACCIONISTA4 = osc.CGCTERC_FORNE4
 AND dp.FACCIONISTA2 = osc.CGCTERC_FORNE2
JOIN PCPC_020 op -- OP capa
  ON op.ordem_producao = l.ORDEM_PRODUCAO
;

SELECT
  i.CODIGO_BARRAS
, i.*
FROM BASI_010 i
WHERE i.GRUPO_ESTRUTURA = '02577'
--  AND i.SUBGRU_ESTRUTURA = 'M'
  AND i.ITEM_ESTRUTURA = '0000PR'
--  AND i.CODIGO_BARRAS IS NOT NULL
;

SELECT
  CURRENT_DATE
, f.DATA_EMISSAO
, f.NUMERO_DANF_NFE
, f.*
FROM fatu_050 f
WHERE 1=1
--  AND f.NUM_NOTA_FISCAL IN (059341)
  AND f.COD_STATUS = 990
  AND f.DATA_EMISSAO < CURRENT_DATE - 7
ORDER BY
  f.DATA_EMISSAO DESC
;

UPDATE fatu_050 f
SET
  f.COD_STATUS = 101
, f.MSG_STATUS = 'Cancelamento de NF-e homologado'
WHERE f.COD_STATUS = 990
  AND f.DATA_EMISSAO < CURRENT_DATE - 3
;

SELECT
  o.DATA_ENTRADA_CORTE
, l.*
, o.*
FROM pcpc_040 l
JOIN PCPC_020 o
  ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
WHERE l.PROCONF_NIVEL99 = 1
  AND o.SITUACAO IN (2, 4)
  AND o.DATA_ENTRADA_CORTE >= '01/10/2017'
ORDER BY
  o.DATA_ENTRADA_CORTE
;

SELECT
  i.CODIGO_BARRAS
, i.*
FROM BASI_010 i
LEFT JOIN BASI_220 t -- tamanhos
  ON t.TAMANHO_REF = i.SUBGRU_ESTRUTURA
WHERE i.GRUPO_ESTRUTURA = '0687U'
  AND i.ITEM_ESTRUTURA = '0000BR'
--  AND i.CODIGO_BARRAS IS NOT NULL
ORDER BY
  t.ORDEM_TAMANHO
;

SELECT
  i.CODIGO_BARRAS
, i.*
FROM BASI_010 i
WHERE i.GRUPO_ESTRUTURA = '0695U'
  AND i.ITEM_ESTRUTURA in ('0000CB')
--  AND i.CODIGO_BARRAS IS NOT NULL
ORDER BY
  i.ITEM_ESTRUTURA
, i.SUBGRU_ESTRUTURA
;

SELECT
  e.CODIGO_ESTAGIO
, e.CODIGO_ESTAGIO || ' - ' || e.DESCRICAO ESTAGIO
, l.PERIODO_PRODUCAO PERIODO
, p.DATA_INI_PERIODO DATA_INI
, p.DATA_FIM_PERIODO DATA_FIM
, r.COLECAO || ' - ' || c.DESCR_COLECAO COLECAO
, l.PROCONF_GRUPO REF
, l.ORDEM_PRODUCAO OP
, l.SEQ_OPERACAO SEQ
, o.DATA_ENTRADA_CORTE DT_CORTE
, SUM( l.QTDE_PECAS_PROG - l.QTDE_PECAS_PROD) QTD
, COUNT(*) LOTES
FROM MQOP_005 e
JOIN PCPC_040 l
  ON l.CODIGO_ESTAGIO = e.CODIGO_ESTAGIO
JOIN BASI_030 r -- cadastro de produtos
  ON r.NIVEL_ESTRUTURA = l.PROCONF_NIVEL99
 AND r.REFERENCIA = l.PROCONF_GRUPO
JOIN BASI_140 c -- cadastro de coleções de produtos
  ON c.COLECAO = r.COLECAO
 AND ( %s is NULL or c.COLECAO = %s )
JOIN PCPC_020 o
  ON o.ORDEM_PRODUCAO = l.ORDEM_PRODUCAO
JOIN PCPC_010 p
  ON p.AREA_PERIODO = 1
 AND p.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
WHERE l.QTDE_EM_PRODUCAO_PACOTE <> 0
  AND o.SITUACAO = 4 -- Ordens em produção
--  AND ( %s is NULL or e.CODIGO_ESTAGIO = %s )
--  AND l.PERIODO_PRODUCAO >= %s
--  AND l.PERIODO_PRODUCAO <= %s
  AND ( o.DATA_ENTRADA_CORTE >= '01/05/2017' )
  AND ( o.DATA_ENTRADA_CORTE <= '01/06/2017' )
GROUP BY
  e.CODIGO_ESTAGIO
, e.DESCRICAO
, l.PERIODO_PRODUCAO
, p.DATA_INI_PERIODO
, p.DATA_FIM_PERIODO
, l.PROCONF_GRUPO
, r.COLECAO
, c.DESCR_COLECAO
, l.ORDEM_PRODUCAO
, l.SEQ_OPERACAO
, o.DATA_ENTRADA_CORTE
ORDER BY
  e.CODIGO_ESTAGIO
, l.PERIODO_PRODUCAO
, r.COLECAO
, l.PROCONF_GRUPO
, l.ORDEM_PRODUCAO
;

SELECT
  x.*
FROM PCPT_025 x -- confirmação de rolo
;

DELETE
FROM PCPT_025 x -- confirmação de rolo
;

SELECT
  x.*
FROM TMRP_141 x -- reserva de rolo para OP
;

DELETE
FROM TMRP_141 x -- reserva de rolo para OP
;

SELECT
  x.*
FROM PCPT_020 x -- cadastro de rolos
WHERE x.ROLO_ESTOQUE = 3
;

UPDATE PCPT_020 x -- cadastro de rolos
SET
  x.ROLO_ESTOQUE = 1
WHERE x.ROLO_ESTOQUE = 3
;

SELECT
  COALESCE(
  ( SELECT
      MIN( le.CODIGO_ESTAGIO ) CODIGO_ESTAGIO
    FROM PCPC_040 le
    JOIN MQOP_005 ed
      ON ed.CODIGO_ESTAGIO = le.CODIGO_ESTAGIO
    WHERE le.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
      AND le.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
      AND le.QTDE_EM_PRODUCAO_PACOTE <> 0
  )
  , 9999
  ) EST_NUM
, l.ORDEM_PRODUCAO OP
, op.SITUACAO OP_SITUACAO
, CASE WHEN dos.NUMERO_ORDEM IS NULL
  THEN '0'
  ELSE l.NUMERO_ORDEM || ' (' || eos.DESCRICAO || ')'
  END OS
, l.PROCONF_GRUPO REF
, l.PROCONF_SUBGRUPO TAM
, l.PROCONF_ITEM COR
, COALESCE(
  ( SELECT
      LISTAGG(le.CODIGO_ESTAGIO || ' - ' || ed.DESCRICAO, ' & ')
      WITHIN GROUP (ORDER BY le.CODIGO_ESTAGIO)
    FROM PCPC_040 le
    JOIN MQOP_005 ed
      ON ed.CODIGO_ESTAGIO = le.CODIGO_ESTAGIO
    WHERE le.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
      AND le.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
      AND le.QTDE_EM_PRODUCAO_PACOTE <> 0
  )
  , 'FINALIZADO'
  ) EST
, l.PERIODO_PRODUCAO PERIODO
, l.ORDEM_CONFECCAO OC
, l.QTDE_PECAS_PROG QTD
, r.NARRATIVA
, CASE WHEN l.DIVISAO = 0 THEN dp.DIVISAO_PRODUCAO
  ELSE l.DIVISAO END DIVISAO
, CASE WHEN l.DIVISAO = 0 THEN dp.DESCRICAO
  ELSE di.DESCRICAO END DESCRICAO_DIVISAO
FROM (
  SELECT
    os.PERIODO_PRODUCAO
  , os.ORDEM_CONFECCAO
  , os.PROCONF_GRUPO
  , os.PROCONF_SUBGRUPO
  , os.PROCONF_ITEM
  , os.ORDEM_PRODUCAO
  , max( os.NUMERO_ORDEM ) NUMERO_ORDEM
  , max( os.QTDE_PECAS_PROG ) QTDE_PECAS_PROG
  , max( CASE WHEN os.CODIGO_FAMILIA < 1000
         THEN os.CODIGO_FAMILIA
         ELSE 0 END ) DIVISAO
  FROM PCPC_040 os
  WHERE 1=1
    AND (os.ORDEM_PRODUCAO = 183)-- or %s IS NULL)
--    AND (os.NUMERO_ORDEM = %s or %s IS NULL)
--    AND (os.ORDEM_CONFECCAO >= %s or %s IS NULL)
--    AND (os.ORDEM_CONFECCAO <= %s or %s IS NULL)
--    AND (os.PROCONF_SUBGRUPO = %s OR %s IS NULL)
--    AND (os.PROCONF_ITEM = %s OR %s IS NULL)
  GROUP BY
    os.PERIODO_PRODUCAO
  , os.ORDEM_CONFECCAO
  , os.PROCONF_GRUPO
  , os.PROCONF_SUBGRUPO
  , os.PROCONF_ITEM
  , os.ORDEM_PRODUCAO
) l
LEFT JOIN PCPC_040 dos
  ON l.NUMERO_ORDEM <> 0
 AND dos.PERIODO_PRODUCAO = l.PERIODO_PRODUCAO
 AND dos.ORDEM_CONFECCAO = l.ORDEM_CONFECCAO
 AND dos.NUMERO_ORDEM = l.NUMERO_ORDEM
LEFT JOIN MQOP_005 eos
  ON eos.CODIGO_ESTAGIO = dos.CODIGO_ESTAGIO
LEFT JOIN BASI_220 t
  ON t.TAMANHO_REF = l.PROCONF_SUBGRUPO
JOIN BASI_010 r
  ON r.NIVEL_ESTRUTURA = 1
 AND r.GRUPO_ESTRUTURA = l.PROCONF_GRUPO
 AND r.SUBGRU_ESTRUTURA = l.PROCONF_SUBGRUPO
 AND r.ITEM_ESTRUTURA = l.PROCONF_ITEM
LEFT JOIN BASI_180 di -- divisao de producao - unidade
  ON di.DIVISAO_PRODUCAO = l.DIVISAO
LEFT JOIN OBRF_080 osc -- OS capa
  ON l.NUMERO_ORDEM <> 0
 AND osc.NUMERO_ORDEM = l.NUMERO_ORDEM
LEFT JOIN BASI_180 dp -- divisao de producao - unidade
  ON dp.FACCIONISTA9 = osc.CGCTERC_FORNE9
 AND dp.FACCIONISTA4 = osc.CGCTERC_FORNE4
 AND dp.FACCIONISTA2 = osc.CGCTERC_FORNE2
JOIN PCPC_020 op -- OP capa
  ON op.ordem_producao = l.ORDEM_PRODUCAO
ORDER BY
  l.ORDEM_CONFECCAO
;

SELECT
  i.CODIGO_BARRAS
, i.*
FROM BASI_010 i
WHERE i.GRUPO_ESTRUTURA = '0620S'
  AND i.SUBGRU_ESTRUTURA = 'G'
  AND i.ITEM_ESTRUTURA = '0000BC'
--  AND i.CODIGO_BARRAS IS NOT NULL
;

SELECT DISTINCT
  l.ORDEM_PRODUCAO
, l.NUMERO_ORDEM
, l.SEQ_ORDEM_SERV
, l.PERIODO_PRODUCAO
, l.ORDEM_CONFECCAO
, l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
, l.*
FROM pcpc_040 l
WHERE 1=1
  --AND l.ORDEM_PRODUCAO = 297
  AND l.NUMERO_ORDEM = 1399
--  AND l.CODIGO_ESTAGIO = 39
--  AND l.PERIODO_PRODUCAO = 1721
--  AND l.ORDEM_CONFECCAO IN (
--    3679
--  , 3708
--  )
--  AND l.NUMERO_ORDEM <> 0
--  AND l.SEQ_ORDEM_SERV <> 0
;

SELECT
  DISTINCT
  s.PRODORD_NIVEL99
, s.PRODORD_GRUPO
, s.PRODORD_SUBGRUPO
, s.PRODORD_ITEM
, s.SEQUENCIA
, s.SEQ_NOTA_SAIDA
, s.SEQUENCIA_ORIGEM
--, s.*
FROM OBRF_081 s
WHERE s.NUMERO_ORDEM = 1399
ORDER BY
  s.PRODORD_NIVEL99
, s.PRODORD_GRUPO
, s.PRODORD_SUBGRUPO
, s.PRODORD_ITEM
;

SELECT
  o.*
FROM OBRF_081_LOG o
WHERE o.NUMERO_ORDEM = 1388
;

DELETE
FROM OBRF_081_LOG o
WHERE o.NUMERO_ORDEM = 1388
;

SELECT
  s.*
FROM OBRF_082 s
WHERE s.NUMERO_ORDEM = 1388
;

DELETE
FROM OBRF_082 s
WHERE s.NUMERO_ORDEM = 1388
;

SELECT
  s.*
FROM OBRF_081 s
WHERE s.NUMERO_ORDEM = 1388
;

SELECT
  s.*
FROM OBRF_080 s
WHERE s.NUMERO_ORDEM = 1388
;

DELETE
FROM OBRF_080 s
WHERE s.NUMERO_ORDEM = 1388
;

SELECT DISTINCT
  l.NUMERO_ORDEM
, l.*
FROM pcpc_040 l -- lotes nos estágios
WHERE 1=1
--  AND l.NUMERO_ORDEM = 1391
  AND l.PERIODO_PRODUCAO = 1747
  AND l.ORDEM_CONFECCAO = 3107
;

SELECT
  o.*
FROM OBRF_081_LOG o
WHERE o.NUMERO_ORDEM = 1393
;

DELETE
FROM OBRF_081_LOG o
WHERE o.NUMERO_ORDEM = 1393
;

SELECT
  s.*
FROM OBRF_082 s
WHERE s.NUMERO_ORDEM = 1393
;

DELETE
FROM OBRF_082 s
WHERE s.NUMERO_ORDEM = 1393
;

SELECT
  s.*
FROM OBRF_081 s
WHERE s.NUMERO_ORDEM = 1393
;

-- está vazia

SELECT
  s.*
FROM OBRF_080 s
WHERE s.NUMERO_ORDEM = 1393
;

DELETE
FROM OBRF_080 s
WHERE s.NUMERO_ORDEM = 1393
;

SELECT
  l.*
FROM pcpc_040 l -- lotes nos estágios
WHERE l.NUMERO_ORDEM = 1393
;

SELECT
  r.SEQ_OPERACAO SEQ
, r.CODIGO_OPERACAO || ' - ' || o.NOME_OPERACAO OPERACAO
, r.CODIGO_ESTAGIO || ' - ' || e.DESCRICAO ESTAGIO
, CASE WHEN r.IND_ESTAGIO_GARGALO = 1
  THEN 'Gargalo'
  ELSE ' '
  END GARGALO
, r.*
FROM MQOP_050 r -- roteiro
JOIN MQOP_005 e -- estagio
  ON e.CODIGO_ESTAGIO = r.CODIGO_ESTAGIO
JOIN MQOP_040 o -- operacao
  ON o.CODIGO_OPERACAO = r.CODIGO_OPERACAO
WHERE r.NIVEL_ESTRUTURA = 1
  AND r.GRUPO_ESTRUTURA = 'M725S'
--  AND r.NUMERO_ALTERNATI = %s
--  AND r.NUMERO_ROTEIRO = %s
ORDER BY
  r.SEQ_OPERACAO
;

SELECT
  s.*
FROM OBRF_082 s
WHERE s.NUMERO_ORDEM = 1476
;

SELECT
  p.PEDIDO_VENDA PEDIDO
, c.NOME_CLIENTE
  || ' (' || lpad(c.CGC_9, 8, '0')
  || '/' || lpad(c.CGC_4, 4, '0')
  || '-' || lpad(c.CGC_2, 2, '0')
  || ')' CLIENTE
, i.CD_IT_PE_NIVEL99 NIVEL
, i.CD_IT_PE_GRUPO REF
, i.CD_IT_PE_ITEM COR
, i.CD_IT_PE_SUBGRUPO TAM
, i.QTDE_PEDIDA QTD
, coalesce( ip.REF_CLIENTE, '-') INFADPROD
, coalesce( rtc.CODIGO_BARRAS, ' ') EAN
, rtc.NARRATIVA
FROM PEDI_100 p -- pedido de venda
LEFT JOIN PEDI_010 c
  ON c.CGC_9 = p.CLI_PED_CGC_CLI9
 AND c.CGC_4 = p.CLI_PED_CGC_CLI4
JOIN PEDI_110 i -- item de pedido de venda
  ON i.PEDIDO_VENDA = p.PEDIDO_VENDA
JOIN BASI_010 rtc -- item (ref+tam+cor)
  on rtc.NIVEL_ESTRUTURA = i.CD_IT_PE_NIVEL99
 AND rtc.GRUPO_ESTRUTURA = i.CD_IT_PE_GRUPO
 AND rtc.SUBGRU_ESTRUTURA = i.CD_IT_PE_SUBGRUPO
 AND rtc.ITEM_ESTRUTURA = i.CD_IT_PE_ITEM
LEFT JOIN ESTQ_400 ip -- item - informações por cliente
  ON ip.CLIENTE9 = CLI_PED_CGC_CLI9
 AND ip.CLIENTE4 = CLI_PED_CGC_CLI4
 AND ip.NIVEL_ESTRUTURA = i.CD_IT_PE_NIVEL99
 AND ip.GRUPO_ESTRUTURA = i.CD_IT_PE_GRUPO
 AND ip.SUBGRUPO_ESTRUTURA = i.CD_IT_PE_SUBGRUPO
 AND ip.ITEM_ESTRUTURA = i.CD_IT_PE_ITEM
LEFT JOIN BASI_220 t -- tamanhos
  ON t.TAMANHO_REF = i.CD_IT_PE_SUBGRUPO
WHERE p.PEDIDO_VENDA = 1000
ORDER BY
  p.PEDIDO_VENDA
, p.CLI_PED_CGC_CLI9
, p.CLI_PED_CGC_CLI4
, i.CD_IT_PE_NIVEL99
, i.CD_IT_PE_GRUPO
, i.CD_IT_PE_ITEM
, t.ORDEM_TAMANHO
, i.CD_IT_PE_SUBGRUPO
;

SELECT DISTINCT
  i.CD_IT_PE_SUBGRUPO TAM
, t.ORDEM_TAMANHO
FROM PEDI_110 i -- item de pedido de venda
LEFT JOIN BASI_220 t -- tamanhos
  ON t.TAMANHO_REF = i.CD_IT_PE_SUBGRUPO
WHERE i.PEDIDO_VENDA = 1000
ORDER BY
  t.ORDEM_TAMANHO
;

SELECT
  i.CD_IT_PE_GRUPO || ' - ' || i.CD_IT_PE_ITEM SORTIMENTO
, i.CD_IT_PE_GRUPO || ' - ' || i.CD_IT_PE_ITEM || ' - ' ||
  max( rtc.DESCRICAO_15 ) DESCR
FROM PEDI_110 i -- item de pedido de venda
JOIN BASI_010 rtc -- item (ref+tam+cor)
  on rtc.NIVEL_ESTRUTURA = i.CD_IT_PE_NIVEL99
 AND rtc.GRUPO_ESTRUTURA = i.CD_IT_PE_GRUPO
 AND rtc.SUBGRU_ESTRUTURA = i.CD_IT_PE_SUBGRUPO
 AND rtc.ITEM_ESTRUTURA = i.CD_IT_PE_ITEM
WHERE i.PEDIDO_VENDA = 1000
GROUP BY
  i.CD_IT_PE_GRUPO
, i.CD_IT_PE_ITEM
ORDER BY
  2
;

SELECT
  i.CD_IT_PE_GRUPO || ' - ' || i.CD_IT_PE_ITEM SORTIMENTO
, i.CD_IT_PE_SUBGRUPO TAMANHO
, i.QTDE_PEDIDA QUANTIDADE
FROM PEDI_110 i -- item de pedido de venda
WHERE i.PEDIDO_VENDA = 1000
;

SELECT
  c.*
FROM BASI_040 c -- combinações de cor e tamanho de componentes de alternativa de estrutura
JOIN
(
SELECT DISTINCT
  e.NIVEL_ITEM
, e.GRUPO_ITEM
, e.ALTERNATIVA_ITEM
FROM BASI_050 e -- componentes de alternativas de estrutura
WHERE e.NIVEL_ITEM = 1
--  AND e.GRUPO_ITEM = '110VO'
--  AND e.ALTERNATIVA_ITEM = 6
  AND e.ESTAGIO = 40
) alt
  ON c.NIVEL_ITEM = alt.NIVEL_ITEM
 AND c.GRUPO_ITEM = alt.GRUPO_ITEM
 AND c.ALTERNATIVA_ITEM = alt.ALTERNATIVA_ITEM
--WHERE c.ESTAGIO <> 40
ORDER BY
  c.NIVEL_ITEM
, c.GRUPO_ITEM
, c.ALTERNATIVA_ITEM
;

DELETE FROM BASI_040 cd
WHERE cd.ROWID IN (
  SELECT
    c.ROWID
  FROM BASI_040 c -- combinações de cor e tamanho de componentes de alternativa de estrutura
  JOIN
  (
    SELECT DISTINCT
      e.NIVEL_ITEM
    , e.GRUPO_ITEM
    , e.ALTERNATIVA_ITEM
    FROM BASI_050 e -- componentes de alternativas de estrutura
    WHERE e.NIVEL_ITEM = 1
--      AND e.GRUPO_ITEM = '110VO'
    --  AND e.ALTERNATIVA_ITEM = 6
      AND e.ESTAGIO = 40
  ) alt
    ON c.NIVEL_ITEM = alt.NIVEL_ITEM
   AND c.GRUPO_ITEM = alt.GRUPO_ITEM
   AND c.ALTERNATIVA_ITEM = alt.ALTERNATIVA_ITEM
  --WHERE c.ESTAGIO <> 40
)
;


DELETE FROM BASI_050 cd
WHERE cd.ROWID IN (
  SELECT
    c.ROWID
--    c.*
  FROM
  (
    SELECT DISTINCT
      e.NIVEL_ITEM
    , e.GRUPO_ITEM
    , e.ALTERNATIVA_ITEM
    FROM BASI_050 e -- componentes de alternativas de estrutura
    WHERE e.NIVEL_ITEM = 1
--      AND e.GRUPO_ITEM = '110VO'
    --  AND e.ALTERNATIVA_ITEM = 6
      AND e.ESTAGIO = 40
  ) alt
  JOIN BASI_050 c -- componentes de alternativa de estrutura
    ON c.NIVEL_ITEM = alt.NIVEL_ITEM
   AND c.GRUPO_ITEM = alt.GRUPO_ITEM
   AND c.ALTERNATIVA_ITEM = alt.ALTERNATIVA_ITEM
)
;

SELECT
  a.NIVEL
, a.GRUPO
, a.ALTERNATIVA
, count(*)
FROM BASI_070 a -- alternativas de estrutura
JOIN BASI_050 c -- componentes de alternativa de estrutura
  ON c.NIVEL_ITEM = a.NIVEL
 AND c.GRUPO_ITEM = a.GRUPO
 AND c.ALTERNATIVA_ITEM = a.ALTERNATIVA
WHERE a.NIVEL = 1
GROUP BY
  a.NIVEL
, a.GRUPO
, a.ALTERNATIVA
HAVING
  count(*) = 0
;


SELECT
  r.NIVEL_ESTRUTURA
, r.GRUPO_ESTRUTURA
, r.NUMERO_ALTERNATI
, a.GRUPO tab_alt
, c.GRUPO_ITEM tab_compo
FROM MQOP_050 r -- operaçẽs das alternativas de roteiro
LEFT JOIN BASI_070 a -- alternativas de estrutura
  ON a.NIVEL = r.NIVEL_ESTRUTURA
 AND a.GRUPO = r.GRUPO_ESTRUTURA
 AND a.ALTERNATIVA = r.NUMERO_ALTERNATI
LEFT JOIN BASI_050 c -- componentes de alternativa de estrutura
  ON c.NIVEL_ITEM = r.NIVEL_ESTRUTURA
 AND c.GRUPO_ITEM = r.GRUPO_ESTRUTURA
 AND c.ALTERNATIVA_ITEM = r.NUMERO_ALTERNATI
WHERE r.NIVEL_ESTRUTURA = 1
  AND (
    a.ALTERNATIVA IS NULL
    OR c.ALTERNATIVA_ITEM IS NULL
  )

--  AND r.GRUPO_ESTRUTURA LIKE 'F%'
--  AND (  r.NUMERO_ROTEIRO = 6
--      OR r.NUMERO_ALTERNATI = 6 )
;

SELECT
  ro.*
--  ro.ROWID
--, rr.NIVEL_ESTRUTURA
--, rr.GRUPO_ESTRUTURA
--, rr.NUMERO_ALTERNATI
--, ro.SEQ_OPERACAO
FROM MQOP_050 ro -- operaçẽs das alternativas de roteiro
JOIN (
SELECT DISTINCT
  r.NIVEL_ESTRUTURA
, r.GRUPO_ESTRUTURA
, r.NUMERO_ALTERNATI
FROM MQOP_050 r -- operaçẽs das alternativas de roteiro
LEFT JOIN BASI_050 c -- componentes de alternativa de estrutura
  ON c.NIVEL_ITEM = r.NIVEL_ESTRUTURA
 AND c.GRUPO_ITEM = r.GRUPO_ESTRUTURA
 AND c.ALTERNATIVA_ITEM = r.NUMERO_ALTERNATI
WHERE r.NIVEL_ESTRUTURA = 1
  AND c.ALTERNATIVA_ITEM IS NULL
) rr
  ON rr.NIVEL_ESTRUTURA = ro.NIVEL_ESTRUTURA
 AND rr.GRUPO_ESTRUTURA = ro.GRUPO_ESTRUTURA
 AND rr.NUMERO_ALTERNATI = ro.NUMERO_ALTERNATI
ORDER BY
  rr.NIVEL_ESTRUTURA
, rr.GRUPO_ESTRUTURA
, rr.NUMERO_ALTERNATI
, ro.SEQ_OPERACAO
;

DELETE FROM MQOP_050 rod
WHERE rod.ROWID IN (
  SELECT
    ro.ROWID
  FROM MQOP_050 ro -- operaçẽs das alternativas de roteiro
  JOIN (
    SELECT DISTINCT
      r.NIVEL_ESTRUTURA
    , r.GRUPO_ESTRUTURA
    , r.NUMERO_ALTERNATI
    FROM MQOP_050 r -- operaçẽs das alternativas de roteiro
    LEFT JOIN BASI_050 c -- componentes de alternativa de estrutura
      ON c.NIVEL_ITEM = r.NIVEL_ESTRUTURA
     AND c.GRUPO_ITEM = r.GRUPO_ESTRUTURA
     AND c.ALTERNATIVA_ITEM = r.NUMERO_ALTERNATI
    WHERE r.NIVEL_ESTRUTURA = 1
      AND c.ALTERNATIVA_ITEM IS NULL
  ) rr
    ON rr.NIVEL_ESTRUTURA = ro.NIVEL_ESTRUTURA
   AND rr.GRUPO_ESTRUTURA = ro.GRUPO_ESTRUTURA
   AND rr.NUMERO_ALTERNATI = ro.NUMERO_ALTERNATI
)
;

-- referência sem operações de roteiro
SELECT
  r.NIVEL_ESTRUTURA
, r.REFERENCIA
, ro.GRUPO_ESTRUTURA
FROM BASI_030 r -- referencia (produto)
LEFT JOIN MQOP_050 ro -- operaçẽs das alternativas de roteiro
  ON ro.NIVEL_ESTRUTURA = r.NIVEL_ESTRUTURA
 AND ro.GRUPO_ESTRUTURA = r.REFERENCIA
WHERE ro.GRUPO_ESTRUTURA IS NULL
;

SELECT
--  r.RESPONSAVEL
--,
  count( DISTINCT i.GRUPO_ESTRUTURA )
FROM BASI_010 i -- item
JOIN BASI_030 r -- referencia (produto)
  ON r.NIVEL_ESTRUTURA = i.NIVEL_ESTRUTURA
 AND r.REFERENCIA = i.GRUPO_ESTRUTURA
WHERE i.NIVEL_ESTRUTURA = 1
  AND i.DATA_CADASTRO <= '01.06.2017'
  AND r.RESPONSAVEL IS NULL
;

SELECT
  i.*
FROM BASI_030 i -- referencia (produto)
WHERE i.NIVEL_ESTRUTURA = 1
--  AND i.dt >= '11.12.2017'
;

-- itens de referência sem operações de roteiro e sem componentes de alternativa
SELECT
  i.NIVEL_ESTRUTURA
, i.GRUPO_ESTRUTURA
, i.SUBGRU_ESTRUTURA
, i.ITEM_ESTRUTURA
, ro.GRUPO_ESTRUTURA
, e.GRUPO_ITEM
FROM BASI_010 i -- referencia (produto)
LEFT JOIN MQOP_050 ro -- operaçẽs das alternativas de roteiro
  ON ro.NIVEL_ESTRUTURA = i.NIVEL_ESTRUTURA
 AND ro.GRUPO_ESTRUTURA = i.GRUPO_ESTRUTURA
LEFT JOIN BASI_050 e -- componentes de alternativas de estrutura
  ON e.NIVEL_ITEM = i.NIVEL_ESTRUTURA
 AND e.GRUPO_ITEM = i.GRUPO_ESTRUTURA
WHERE 1=1
--  AND ro.GRUPO_ESTRUTURA <> e.GRUPO_ITEM
  AND (
    ro.GRUPO_ESTRUTURA IS NULL
    OR e.GRUPO_ITEM IS NULL
  )
;


SELECT
  TRUNC( ( lnumber + 2 )/ 3 ) steplnumber
, lote.PROCONF_ITEM
, lote.PROCONF_SUBGRUPO
, MIN( lote.PERIODO_PRODUCAO ) PERIODO_PRODUCAO
, COUNT( lote.ORDEM_CONFECCAO ) OCN
, MIN( lote.ORDEM_CONFECCAO ) OCI
, MAX( lote.ORDEM_CONFECCAO ) OCF
FROM (
SELECT
  row_number() over(
    partition BY
      l.PROCONF_ITEM
    , l.ORDEM_TAMANHO
    order BY
      l.ORDEM_CONFECCAO
  ) lnumber
, l.*
FROM (
SELECT DISTINCT
    os.PERIODO_PRODUCAO
  , os.PROCONF_ITEM
  , t.ORDEM_TAMANHO
  , os.PROCONF_SUBGRUPO
  , os.ORDEM_CONFECCAO
  FROM PCPC_040 os
  LEFT JOIN BASI_220 t -- tamanhos
    ON t.TAMANHO_REF = os.PROCONF_SUBGRUPO
  WHERE os.ORDEM_PRODUCAO = 4000
    AND os.PROCONF_ITEM = '0000PE'
  GROUP BY
    os.PERIODO_PRODUCAO
  , os.PROCONF_ITEM
  , t.ORDEM_TAMANHO
  , os.PROCONF_SUBGRUPO
  , os.ORDEM_CONFECCAO
) l
) lote
GROUP BY
  lote.PROCONF_ITEM
, lote.ORDEM_TAMANHO
, lote.PROCONF_SUBGRUPO
, TRUNC( ( lnumber + 2 )/ 3 )
ORDER BY
  lote.PROCONF_ITEM
, lote.ORDEM_TAMANHO
, 1
;


SELECT
  ll.lnumber
, ll.PERIODO_PRODUCAO
, ll.PROCONF_ITEM
, ll.PROCONF_SUBGRUPO
, MIN(ll.ORDEM_CONFECCAO) OC1
, CASE COUNT(ll.ORDEM_CONFECCAO)
  WHEN 1 THEN NULL
  WHEN 2 THEN MAX(ll.ORDEM_CONFECCAO)
  WHEN 3 THEN AVG(ll.ORDEM_CONFECCAO)
  END OC2
, CASE WHEN COUNT(ll.ORDEM_CONFECCAO) = 3
  THEN MAX(ll.ORDEM_CONFECCAO)
  ELSE NULL
  END OC3
FROM (
SELECT DISTINCT
  TRUNC( (
    row_number()
      over(
      partition BY
        os.PROCONF_ITEM
      , t.ORDEM_TAMANHO
      order BY
        os.ORDEM_CONFECCAO
      )
    + 2 )/ 3 ) lnumber
  , os.PERIODO_PRODUCAO
  , os.PROCONF_ITEM
  , t.ORDEM_TAMANHO
  , os.PROCONF_SUBGRUPO
  , os.ORDEM_CONFECCAO
  FROM PCPC_040 os
  LEFT JOIN BASI_220 t -- tamanhos
    ON t.TAMANHO_REF = os.PROCONF_SUBGRUPO
  WHERE os.ORDEM_PRODUCAO = 4000
    AND os.PROCONF_ITEM = '0000PE'
  GROUP BY
    os.PERIODO_PRODUCAO
  , os.PROCONF_ITEM
  , t.ORDEM_TAMANHO
  , os.PROCONF_SUBGRUPO
  , os.ORDEM_CONFECCAO
) ll
GROUP BY
  ll.PERIODO_PRODUCAO
, ll.PROCONF_ITEM
, ll.ORDEM_TAMANHO
, ll.PROCONF_SUBGRUPO
, ll.lnumber
ORDER BY
  ll.PERIODO_PRODUCAO
, ll.PROCONF_ITEM
, ll.ORDEM_TAMANHO
, ll.PROCONF_SUBGRUPO
, ll.lnumber
;


WITH lotes AS (
SELECT DISTINCT
  TRUNC( (
    row_number()
      over(
      partition BY
        os.PROCONF_ITEM
      , t.ORDEM_TAMANHO
      order BY
        os.ORDEM_CONFECCAO
      )
    + 2 )/ 3 ) PACOTE
, os.ORDEM_PRODUCAO OP
, op.SITUACAO
, os.PERIODO_PRODUCAO PERIODO
, os.PROCONF_GRUPO REF
, os.PROCONF_ITEM COR
, t.ORDEM_TAMANHO TAMORD
, os.PROCONF_SUBGRUPO TAM
, os.ORDEM_CONFECCAO OC
, r.NARRATIVA
FROM PCPC_040 os
LEFT JOIN BASI_220 t -- tamanhos
  ON t.TAMANHO_REF = os.PROCONF_SUBGRUPO
JOIN PCPC_020 op -- OP capa
  ON op.ordem_producao = os.ORDEM_PRODUCAO
JOIN BASI_010 r
  ON r.NIVEL_ESTRUTURA = 1
 AND r.GRUPO_ESTRUTURA = os.PROCONF_GRUPO
 AND r.SUBGRU_ESTRUTURA = os.PROCONF_SUBGRUPO
 AND r.ITEM_ESTRUTURA = os.PROCONF_ITEM
WHERE 1=1
--  AND (os.ORDEM_PRODUCAO = %s or %s IS NULL)
--  AND (os.PROCONF_SUBGRUPO = %s OR %s IS NULL)
--  AND (os.PROCONF_ITEM = %s OR %s IS NULL)
  AND os.ORDEM_PRODUCAO = 4000
  AND os.PROCONF_ITEM = '0000PE'
GROUP BY
  os.ORDEM_PRODUCAO
, op.SITUACAO
, os.PERIODO_PRODUCAO
, os.PROCONF_GRUPO
, os.PROCONF_ITEM
, t.ORDEM_TAMANHO
, os.PROCONF_SUBGRUPO
, os.ORDEM_CONFECCAO
, r.NARRATIVA
)
SELECT
  ll.OP
, ll.SITUACAO
, ll.PERIODO
, ll.REF
, ll.COR
, ll.TAM
, ll.NARRATIVA
, ll.pacote
, MIN(ll.OC) OC1
, CASE COUNT(ll.OC)
  WHEN 1 THEN NULL
  WHEN 2 THEN MAX(ll.OC)
  WHEN 3 THEN AVG(ll.OC)
  END OC2
, CASE WHEN COUNT(ll.OC) = 3
  THEN MAX(ll.OC)
  ELSE NULL
  END OC3
FROM lotes ll
GROUP BY
  ll.OP
, ll.SITUACAO
, ll.PERIODO
, ll.REF
, ll.COR
, ll.TAMORD
, ll.TAM
, ll.NARRATIVA
, ll.pacote
ORDER BY
  ll.OP
, ll.SITUACAO
, ll.PERIODO
, ll.REF
, ll.COR
, ll.TAMORD
, ll.NARRATIVA
, ll.pacote
;


SELECT
  ll.OP
, ll.SITUACAO
, ll.PERIODO
, ll.REF
, ll.COR
, ll.TAM
, ll.NARRATIVA
, ll.pacote
, MIN(ll.OC) OC1
, CASE COUNT(ll.OC)
  WHEN 1 THEN NULL
  WHEN 2 THEN MAX(ll.OC)
  WHEN 3 THEN AVG(ll.OC)
  END OC2
, CASE WHEN COUNT(ll.OC) = 3
  THEN MAX(ll.OC)
  ELSE NULL
  END OC3
FROM (
SELECT DISTINCT
  TRUNC( (
    row_number()
      over(
      partition BY
        os.PROCONF_ITEM
      , t.ORDEM_TAMANHO
      order BY
        os.ORDEM_CONFECCAO
      )
    + 2 )/ 3 ) PACOTE
, os.ORDEM_PRODUCAO OP
, op.SITUACAO
, os.PERIODO_PRODUCAO PERIODO
, os.PROCONF_GRUPO REF
, os.PROCONF_ITEM COR
, t.ORDEM_TAMANHO TAMORD
, os.PROCONF_SUBGRUPO TAM
, os.ORDEM_CONFECCAO OC
, r.NARRATIVA
FROM PCPC_040 os
LEFT JOIN BASI_220 t -- tamanhos
  ON t.TAMANHO_REF = os.PROCONF_SUBGRUPO
JOIN PCPC_020 op -- OP capa
  ON op.ordem_producao = os.ORDEM_PRODUCAO
JOIN BASI_010 r
  ON r.NIVEL_ESTRUTURA = 1
 AND r.GRUPO_ESTRUTURA = os.PROCONF_GRUPO
 AND r.SUBGRU_ESTRUTURA = os.PROCONF_SUBGRUPO
 AND r.ITEM_ESTRUTURA = os.PROCONF_ITEM
WHERE 1=1
--  AND (os.ORDEM_PRODUCAO = %s or %s IS NULL)
--  AND (os.PROCONF_SUBGRUPO = %s OR %s IS NULL)
--  AND (os.PROCONF_ITEM = %s OR %s IS NULL)
  AND os.ORDEM_PRODUCAO = 4000
  AND os.PROCONF_ITEM = '0000PE'
GROUP BY
  os.ORDEM_PRODUCAO
, op.SITUACAO
, os.PERIODO_PRODUCAO
, os.PROCONF_GRUPO
, os.PROCONF_ITEM
, t.ORDEM_TAMANHO
, os.PROCONF_SUBGRUPO
, os.ORDEM_CONFECCAO
, r.NARRATIVA
) ll
GROUP BY
  ll.OP
, ll.SITUACAO
, ll.PERIODO
, ll.REF
, ll.COR
, ll.TAMORD
, ll.TAM
, ll.NARRATIVA
, ll.pacote
ORDER BY
  ll.OP
, ll.SITUACAO
, ll.PERIODO
, ll.REF
, ll.COR
, ll.TAMORD
, ll.NARRATIVA
, ll.pacote
;


WITH Table_qtd_lotes AS (
SELECT
  ll.OP
, ll.SITUACAO
, ll.PERIODO
, ll.REF
, ll.COR
, ll.TAM
, ll.NARRATIVA
, ll.pacote
, MIN(ll.OC) OC1
, CASE COUNT(ll.OC)
  WHEN 1 THEN NULL
  WHEN 2 THEN MAX(ll.OC)
  WHEN 3 THEN AVG(ll.OC)
  END OC2
, CASE WHEN COUNT(ll.OC) = 3
  THEN MAX(ll.OC)
  ELSE NULL
  END OC3
FROM (
SELECT DISTINCT
  TRUNC( (
    row_number()
      over(
      partition BY
        os.PROCONF_ITEM
      , t.ORDEM_TAMANHO
      order BY
        os.ORDEM_CONFECCAO
      )
    + 2 )/ 3 ) PACOTE
, os.ORDEM_PRODUCAO OP
, op.SITUACAO
, os.PERIODO_PRODUCAO PERIODO
, os.PROCONF_GRUPO REF
, os.PROCONF_ITEM COR
, t.ORDEM_TAMANHO TAMORD
, os.PROCONF_SUBGRUPO TAM
, os.ORDEM_CONFECCAO OC
, r.NARRATIVA
FROM PCPC_040 os
LEFT JOIN BASI_220 t -- tamanhos
  ON t.TAMANHO_REF = os.PROCONF_SUBGRUPO
JOIN PCPC_020 op -- OP capa
  ON op.ordem_producao = os.ORDEM_PRODUCAO
JOIN BASI_010 r
  ON r.NIVEL_ESTRUTURA = 1
 AND r.GRUPO_ESTRUTURA = os.PROCONF_GRUPO
 AND r.SUBGRU_ESTRUTURA = os.PROCONF_SUBGRUPO
 AND r.ITEM_ESTRUTURA = os.PROCONF_ITEM
WHERE 1=1
--  AND (os.ORDEM_PRODUCAO = %s or %s IS NULL)
--  AND (os.PROCONF_SUBGRUPO = %s OR %s IS NULL)
--  AND (os.PROCONF_ITEM = %s OR %s IS NULL)
  AND os.ORDEM_PRODUCAO = 4000
  AND os.PROCONF_ITEM = '0000PE'
GROUP BY
  os.ORDEM_PRODUCAO
, op.SITUACAO
, os.PERIODO_PRODUCAO
, os.PROCONF_GRUPO
, os.PROCONF_ITEM
, t.ORDEM_TAMANHO
, os.PROCONF_SUBGRUPO
, os.ORDEM_CONFECCAO
, r.NARRATIVA
) ll
GROUP BY
  ll.OP
, ll.SITUACAO
, ll.PERIODO
, ll.REF
, ll.COR
, ll.TAMORD
, ll.TAM
, ll.NARRATIVA
, ll.pacote
ORDER BY
  ll.OP
, ll.SITUACAO
, ll.PERIODO
, ll.REF
, ll.COR
, ll.TAMORD
, ll.NARRATIVA
, ll.pacote
)
select * from Table_qtd_lotes where rownum <= 4
;


                SELECT
                  f.NUM_NOTA_FISCAL NF
                , f.BASE_ICMS VALOR
                , f.QTDE_EMBALAGENS VOLUMES
                , f.DATA_AUTORIZACAO_NFE FATURAMENTO
                , CAST( COALESCE( '0' || f.COD_STATUS, '0' ) AS INT )
                  COD_STATUS
                , COALESCE( f.MSG_STATUS, ' ' ) MSG_STATUS
                , f.SITUACAO_NFISC SITUACAO
                , f.NATOP_NF_NAT_OPER NAT
                , f.NATOP_NF_EST_OPER UF
                , n.DESCR_NAT_OPER NATUREZA
                , f.CGC_9 CNPJ9
                , f.CGC_4 CNPJ4
                , f.CGC_2 CNPJ2
                , c.NOME_CLIENTE CLIENTE
                , COALESCE(
                    CASE WHEN f.TRANSPOR_FORNE9
                            + f.TRANSPOR_FORNE4
                            + f.TRANSPOR_FORNE2 = 0
                    THEN 'O PROPRIO'
                    ELSE COALESCE( t.NOME_FANTASIA
                                 , '(' || f.TRANSPOR_FORNE9 || '/' ||
                                   f.TRANSPOR_FORNE4 || '-' ||
                                   f.TRANSPOR_FORNE2 || ')' )
                    END
                  , '-') TRANSP
                , f.PEDIDO_VENDA PEDIDO
                , coalesce(p.COD_PED_CLIENTE, '') PED_CLIENTE
                FROM FATU_050 f
                LEFT JOIN PEDI_100 p
                  ON p.PEDIDO_VENDA = f.PEDIDO_VENDA
                JOIN PEDI_010 c
                  ON c.CGC_9 = f.CGC_9
                 AND c.CGC_4 = f.CGC_4
                 AND c.CGC_2 = f.CGC_2
                JOIN PEDI_080 n
                  ON n.NATUR_OPERACAO = f.NATOP_NF_NAT_OPER
                 AND n.ESTADO_NATOPER = f.NATOP_NF_EST_OPER
                LEFT JOIN SUPR_010 t
                  ON t.TIPO_FORNECEDOR = 31 -- transportadora
                 AND t.FORNECEDOR9 = f.TRANSPOR_FORNE9
                 AND t.FORNECEDOR4 = f.TRANSPOR_FORNE4
                 AND t.FORNECEDOR2 = f.TRANSPOR_FORNE2
                --WHERE rownum = 1
                ORDER BY
                  f.NUM_NOTA_FISCAL DESC
;


SELECT
  h.USUARIO_SISTEMA
, h.MAQUINA_REDE
FROM HIST_010 h
GROUP BY
  h.USUARIO_SISTEMA
, h.MAQUINA_REDE
ORDER BY
  h.USUARIO_SISTEMA
, h.MAQUINA_REDE
;

SELECT
  min(h.DATA_OCORR)
, max(h.DATA_OCORR)
FROM HIST_010 h
;

SELECT DISTINCT
  h.USUARIO_SISTEMA
FROM HIST_010 h
WHERE h.APLICACAO <> 'python@INTRANET'
;

SELECT
  u.ATIVO_INATIVO
, u.*
FROM HDOC_030 u
WHERE u.USUARIO NOT IN
(
SELECT DISTINCT
  h.USUARIO_SISTEMA
FROM HIST_010 h
WHERE h.APLICACAO <> 'python@INTRANET'
)
;

SELECT DISTINCT
  h.USUARIO_SISTEMA
, h.NOME_PROGRAMA
FROM HIST_010 h
ORDER BY
  h.USUARIO_SISTEMA
, h.NOME_PROGRAMA
;

SELECT DISTINCT
  h.*
FROM HIST_010 h
WHERE h.NOME_PROGRAMA = 'SQL'
;

SELECT DISTINCT
  h.APLICACAO
, h.NOME_PROGRAMA
, h.MAQUINA_REDE
FROM HIST_010 h
;

SELECT DISTINCT
  h.USUARIO_SISTEMA
, h.MAQUINA_REDE
FROM HIST_010 h
WHERE h.NOME_PROGRAMA <> 'SQL'
ORDER BY
  h.USUARIO_SISTEMA
, h.MAQUINA_REDE
;

SELECT
  ll.PCPC040_PERCONF
, ll.PCPC040_ORDCONF
, ll.PCPC040_ESTCONF
, count(*)
--, ll.*
FROM PCPC_045 ll
--WHERE ll.PCPC040_PERCONF = 1750
--  AND ll.PCPC040_ORDCONF = 216
GROUP BY
  ll.PCPC040_PERCONF
, ll.PCPC040_ORDCONF
, ll.PCPC040_ESTCONF
ORDER BY
  4 DESC
;

SELECT
  ll.PCPC040_PERCONF
, ll.PCPC040_ORDCONF
, ll.PCPC040_ESTCONF
, ll.DATA_INSERCAO
, max(ll.DATA_INSERCAO)
    over(
      partition BY
	    ll.PCPC040_PERCONF
	  , ll.PCPC040_ORDCONF
      )
FROM PCPC_045 ll
WHERE ll.PCPC040_PERCONF = 1750
  AND ll.PCPC040_ORDCONF = 216
;

SELECT
  ll.PCPC040_PERCONF
, ll.PCPC040_ORDCONF
, ll.DATA_INSERCAO
, count(*)
FROM PCPC_045 ll
GROUP BY
  ll.PCPC040_PERCONF
, ll.PCPC040_ORDCONF
, ll.DATA_INSERCAO
ORDER BY
  4 DESC
;


SELECT
  CURRENT_DATE
--, CURRENT_TIME
, CURRENT_TIMESTAMP
, ll.*
FROM PCPC_045 ll
;

SELECT
  t.*
FROM (
SELECT
  ll.PCPC040_PERCONF
, ll.PCPC040_ORDCONF
, ll.PCPC040_ESTCONF
--, l.SEQ_OPERACAO
--, ll.DATA_PRODUCAO
--, ll.HORA_PRODUCAO
--, ll.*
FROM PCPC_045 ll
JOIN pcpc_040 l
  ON l.PERIODO_PRODUCAO = ll.PCPC040_PERCONF
 AND l.ORDEM_CONFECCAO = ll.PCPC040_ORDCONF
 AND l.CODIGO_ESTAGIO = ll.PCPC040_ESTCONF
WHERE ll.PCPC040_PERCONF = 1720
  AND ll.PCPC040_ORDCONF = 1041
ORDER BY
  ll.DATA_INSERCAO DESC
, l.SEQ_OPERACAO DESC
) t
WHERE rownum = 1
;


SELECT
  0
, PERIODO_PRODUCAO, ORDEM_CONFECCAO, CODIGO_ESTAGIO, PROCONF_NIVEL99, PROCONF_GRUPO, PROCONF_SUBGRUPO, PROCONF_ITEM, QTDE_PECAS_PROG
, QTDE_PECAS_PROD ---------
, QTDE_CONSERTO, QTDE_PECAS_2A, ESTAGIO_ANTERIOR, SITUACAO_ORDEM, NUMERO_ORDEM, SEQ_ORDEM_SERV, DIV_PROD_INT, ORDEM_PRODUCAO, QTDE_PERDAS, QTDE_PROGRAMADA, SEQUENCIA_ESTAGIO
, ESTAGIO_DEPENDE, USUARIO, CODIGO_FAMILIA, POSICAO_FILA, POSICAO_FILA_MANUAL, SEQ_OPERACAO, DATA_PREV_INICIO, QTDE_PESSOAS_PREV, CODIGO_BALANCEIO, NUM_PACOTE_I
, NUM_PACOTE_F, NUMERO_ID_TMRP_650, EXPORTADO_PMS, EXECUTA_TRIGGER, SEQUENCIA_ENFESTO, EXCLUI_PACOTE, SEQ_QUEBRA, DATA_ALTERACAO
, QTDE_EM_PRODUCAO_PACOTE ---------
, QTDE_A_PRODUZIR_PACOTE ---------
, QTDE_DISPONIVEL_BAIXA ---------
, SITUACAO_EM_PROD_A_PROD, QTDE_PECAS_PROD_RECALC, QTDE_CONSERTO_RECALC, QTDE_PECAS_2A_RECALC, QTDE_PERDAS_RECALC, NOME_PROGRAMA_CRIACAO
, NOME_PROGRAMA ---------
, CODIGO_EMPRESA
FROM SYSTEXTIL.PCPC_040
WHERE PERIODO_PRODUCAO=1743 AND ORDEM_CONFECCAO=10128 AND CODIGO_ESTAGIO=51
UNION
SELECT
  1
, PERIODO_PRODUCAO, ORDEM_CONFECCAO, CODIGO_ESTAGIO, PROCONF_NIVEL99, PROCONF_GRUPO, PROCONF_SUBGRUPO, PROCONF_ITEM, QTDE_PECAS_PROG
, 0 QTDE_PECAS_PROD ---------
, QTDE_CONSERTO, QTDE_PECAS_2A, ESTAGIO_ANTERIOR, SITUACAO_ORDEM, NUMERO_ORDEM, SEQ_ORDEM_SERV, DIV_PROD_INT, ORDEM_PRODUCAO, QTDE_PERDAS, QTDE_PROGRAMADA, SEQUENCIA_ESTAGIO
, ESTAGIO_DEPENDE, USUARIO, CODIGO_FAMILIA, POSICAO_FILA, POSICAO_FILA_MANUAL, SEQ_OPERACAO, DATA_PREV_INICIO, QTDE_PESSOAS_PREV, CODIGO_BALANCEIO, NUM_PACOTE_I
, NUM_PACOTE_F, NUMERO_ID_TMRP_650, EXPORTADO_PMS, EXECUTA_TRIGGER, SEQUENCIA_ENFESTO, EXCLUI_PACOTE, SEQ_QUEBRA, DATA_ALTERACAO
, QTDE_PECAS_PROD QTDE_EM_PRODUCAO_PACOTE ---------
, QTDE_PECAS_PROD QTDE_A_PRODUZIR_PACOTE ---------
, QTDE_PECAS_PROD QTDE_DISPONIVEL_BAIXA ---------
, SITUACAO_EM_PROD_A_PROD, QTDE_PECAS_PROD_RECALC, QTDE_CONSERTO_RECALC, QTDE_PECAS_2A_RECALC, QTDE_PERDAS_RECALC, NOME_PROGRAMA_CRIACAO
, 'pcpc_f046' NOME_PROGRAMA ---------
, CODIGO_EMPRESA
FROM SYSTEXTIL.PCPC_040
WHERE PERIODO_PRODUCAO=1743 AND ORDEM_CONFECCAO=10128 AND CODIGO_ESTAGIO=51
;


SELECT
  le.*
FROM pcpc_040 le
WHERE le.PERIODO_PRODUCAO = 1743
  AND le.ORDEM_CONFECCAO IN (10127, 10128)
  AND le.CODIGO_ESTAGIO in (48, 51)
;


SELECT
  l2.*
FROM pcpc_045 l2
WHERE l2.PCPC040_PERCONF = 1743
  AND l2.PCPC040_ORDCONF IN (10127, 10128)
  AND l2.PCPC040_ESTCONF in (51)
;


SELECT
  l2.*
FROM pcpc_045 l2
JOIN pcpc_040 l
  ON l.PERIODO_PRODUCAO = l2.PCPC040_PERCONF
 AND l.ORDEM_CONFECCAO = l2.PCPC040_ORDCONF
 AND l.CODIGO_ESTAGIO = l2.PCPC040_ESTCONF
WHERE l.ORDEM_PRODUCAO = 3160
--  AND l.QTDE_PECAS_PROD <> 0
--  AND l2.PCPC040_ORDCONF NOT IN (10127, 10128)
  AND l2.PCPC040_ESTCONF = 51
ORDER BY
  l2.PCPC040_ORDCONF
, l2.SEQUENCIA
;


UPDATE SYSTEXTIL.PCPC_045
SET
  PROCESSO_SYSTEXTIL='pcpc_f046'
, USUARIO_SYSTEXTIL='ROSANGELA_PCP'
WHERE PCPC040_PERCONF=1743
  AND PCPC040_ORDCONF=10128
  AND PCPC040_ESTCONF=51
  AND SEQUENCIA=2
;

SELECT
  p.*
FROM HDOC_036 p
WHERE p.DESCRICAO like '%Estorn%'
;

UPDATE SYSTEXTIL.PCPC_040
SET
  PROCONF_NIVEL99 = PROCONF_NIVEL99
, PROCONF_GRUPO = PROCONF_GRUPO
, PROCONF_SUBGRUPO = PROCONF_SUBGRUPO
, PROCONF_ITEM = PROCONF_ITEM
, QTDE_PECAS_PROG = QTDE_PECAS_PROG
, QTDE_PECAS_PROD = 40 ----------------
, QTDE_CONSERTO = QTDE_CONSERTO
, QTDE_PECAS_2A = QTDE_PECAS_2A
, ESTAGIO_ANTERIOR = ESTAGIO_ANTERIOR
, SITUACAO_ORDEM = SITUACAO_ORDEM
, NUMERO_ORDEM = NUMERO_ORDEM
, SEQ_ORDEM_SERV = SEQ_ORDEM_SERV
, DIV_PROD_INT = DIV_PROD_INT
, ORDEM_PRODUCAO = ORDEM_PRODUCAO
, QTDE_PERDAS = QTDE_PERDAS
, QTDE_PROGRAMADA = QTDE_PROGRAMADA
, SEQUENCIA_ESTAGIO = SEQUENCIA_ESTAGIO
, ESTAGIO_DEPENDE = ESTAGIO_DEPENDE
, USUARIO = USUARIO
, CODIGO_FAMILIA = CODIGO_FAMILIA
, POSICAO_FILA = POSICAO_FILA
, POSICAO_FILA_MANUAL = POSICAO_FILA_MANUAL
, SEQ_OPERACAO = SEQ_OPERACAO
, DATA_PREV_INICIO = DATA_PREV_INICIO
, QTDE_PESSOAS_PREV = QTDE_PESSOAS_PREV
, CODIGO_BALANCEIO = CODIGO_BALANCEIO
, NUM_PACOTE_I = NUM_PACOTE_I
, NUM_PACOTE_F = NUM_PACOTE_F
, NUMERO_ID_TMRP_650 = NUMERO_ID_TMRP_650
, EXPORTADO_PMS = EXPORTADO_PMS
, EXECUTA_TRIGGER = EXECUTA_TRIGGER
, SEQUENCIA_ENFESTO = SEQUENCIA_ENFESTO
, EXCLUI_PACOTE = EXCLUI_PACOTE
, SEQ_QUEBRA = SEQ_QUEBRA
, DATA_ALTERACAO = DATA_ALTERACAO
, QTDE_EM_PRODUCAO_PACOTE = 0 ----------------
, QTDE_A_PRODUZIR_PACOTE = 0 ----------------
, QTDE_DISPONIVEL_BAIXA = 0 ----------------
, SITUACAO_EM_PROD_A_PROD = SITUACAO_EM_PROD_A_PROD
, QTDE_PECAS_PROD_RECALC = QTDE_PECAS_PROD_RECALC
, QTDE_CONSERTO_RECALC = QTDE_CONSERTO_RECALC
, QTDE_PECAS_2A_RECALC = QTDE_PECAS_2A_RECALC
, QTDE_PERDAS_RECALC = QTDE_PERDAS_RECALC
, NOME_PROGRAMA_CRIACAO = NOME_PROGRAMA_CRIACAO
, NOME_PROGRAMA = 'pcpc_f230' ----------------
, CODIGO_EMPRESA = CODIGO_EMPRESA
WHERE PERIODO_PRODUCAO = 1743
  AND ORDEM_CONFECCAO = 10128
  AND CODIGO_ESTAGIO = 51
;

INSERT INTO SYSTEXTIL.PCPC_045
(PCPC040_PERCONF, PCPC040_ORDCONF, PCPC040_ESTCONF, SEQUENCIA, DATA_PRODUCAO, HORA_PRODUCAO, QTDE_PRODUZIDA, QTDE_PECAS_2A, QTDE_CONSERTO, TURNO_PRODUCAO, TIPO_ENTRADA_ORD, NOTA_ENTR_ORDEM, SERIE_NF_ENT_ORD, SEQ_NF_ENTR_ORD, ORDEM_PRODUCAO, CODIGO_USUARIO, QTDE_PERDAS, NUMERO_DOCUMENTO, CODIGO_DEPOSITO, CODIGO_FAMILIA, CODIGO_INTERVALO, EXECUTA_TRIGGER, DATA_INSERCAO, PROCESSO_SYSTEXTIL, NUMERO_VOLUME, NR_OPERADORES, ATZ_PODE_PRODUZIR, ATZ_EM_PROD, ATZ_A_PROD, EFICIENCIA_INFORMADA, USUARIO_SYSTEXTIL, CODIGO_OCORRENCIA, COD_OCORRENCIA_ESTORNO, SOLICITACAO_CONSERTO, NUMERO_SOLICITACAO, NUMERO_ORDEM)
SELECT
  PCPC040_PERCONF
, PCPC040_ORDCONF
, PCPC040_ESTCONF
, SEQUENCIA+1 -- SEQUENCIA
, CURRENT_DATE -- DATA_PRODUCAO
, CURRENT_DATE -- HORA_PRODUCAO
, -QTDE_PRODUZIDA -- QTDE_PRODUZIDA
, QTDE_PECAS_2A
, QTDE_CONSERTO
, TURNO_PRODUCAO
, TIPO_ENTRADA_ORD
, NOTA_ENTR_ORDEM
, SERIE_NF_ENT_ORD
, SEQ_NF_ENTR_ORD
, ORDEM_PRODUCAO
, CODIGO_USUARIO
, QTDE_PERDAS
, NUMERO_DOCUMENTO
, CODIGO_DEPOSITO
, CODIGO_FAMILIA
, CODIGO_INTERVALO
, EXECUTA_TRIGGER
, CURRENT_DATE -- DATA_INSERCAO
, 'pcpc_f046' -- PROCESSO_SYSTEXTIL
, NUMERO_VOLUME
, NR_OPERADORES
, ATZ_PODE_PRODUZIR
, ATZ_EM_PROD
, ATZ_A_PROD
, EFICIENCIA_INFORMADA
, USUARIO_SYSTEXTIL
, CODIGO_OCORRENCIA
, COD_OCORRENCIA_ESTORNO
, SOLICITACAO_CONSERTO
, NUMERO_SOLICITACAO
, NUMERO_ORDEM
FROM SYSTEXTIL.PCPC_045
WHERE PCPC040_PERCONF=1743
  AND PCPC040_ORDCONF=10128
  AND PCPC040_ESTCONF=51
  AND SEQUENCIA=1
;


INSERT INTO SYSTEXTIL.PCPC_045
(PCPC040_PERCONF, PCPC040_ORDCONF, PCPC040_ESTCONF, SEQUENCIA, DATA_PRODUCAO, HORA_PRODUCAO, QTDE_PRODUZIDA, QTDE_PECAS_2A, QTDE_CONSERTO, TURNO_PRODUCAO, TIPO_ENTRADA_ORD, NOTA_ENTR_ORDEM, SERIE_NF_ENT_ORD, SEQ_NF_ENTR_ORD, ORDEM_PRODUCAO, CODIGO_USUARIO, QTDE_PERDAS, NUMERO_DOCUMENTO, CODIGO_DEPOSITO, CODIGO_FAMILIA, CODIGO_INTERVALO, EXECUTA_TRIGGER, DATA_INSERCAO, PROCESSO_SYSTEXTIL, NUMERO_VOLUME, NR_OPERADORES, ATZ_PODE_PRODUZIR, ATZ_EM_PROD, ATZ_A_PROD, EFICIENCIA_INFORMADA, USUARIO_SYSTEXTIL, CODIGO_OCORRENCIA, COD_OCORRENCIA_ESTORNO, SOLICITACAO_CONSERTO, NUMERO_SOLICITACAO, NUMERO_ORDEM)
SELECT
  l2.PCPC040_PERCONF
, l2.PCPC040_ORDCONF
, l2.PCPC040_ESTCONF
, l2.SEQUENCIA+1 -- SEQUENCIA
, CURRENT_DATE -- DATA_PRODUCAO
, CURRENT_DATE -- HORA_PRODUCAO
, -l2.QTDE_PRODUZIDA -- QTDE_PRODUZIDA
, l2.QTDE_PECAS_2A
, l2.QTDE_CONSERTO
, l2.TURNO_PRODUCAO
, l2.TIPO_ENTRADA_ORD
, l2.NOTA_ENTR_ORDEM
, l2.SERIE_NF_ENT_ORD
, l2.SEQ_NF_ENTR_ORD
, l2.ORDEM_PRODUCAO
, l2.CODIGO_USUARIO
, l2.QTDE_PERDAS
, l2.NUMERO_DOCUMENTO
, l2.CODIGO_DEPOSITO
, l2.CODIGO_FAMILIA
, l2.CODIGO_INTERVALO
, l2.EXECUTA_TRIGGER
, CURRENT_DATE -- DATA_INSERCAO
, 'pcpc_f046' -- PROCESSO_SYSTEXTIL
, l2.NUMERO_VOLUME
, l2.NR_OPERADORES
, l2.ATZ_PODE_PRODUZIR
, l2.ATZ_EM_PROD
, l2.ATZ_A_PROD
, l2.EFICIENCIA_INFORMADA
, l2.USUARIO_SYSTEXTIL
, l2.CODIGO_OCORRENCIA
, l2.COD_OCORRENCIA_ESTORNO
, l2.SOLICITACAO_CONSERTO
, l2.NUMERO_SOLICITACAO
, l2.NUMERO_ORDEM
FROM pcpc_045 l2
JOIN pcpc_040 l
  ON l.PERIODO_PRODUCAO = l2.PCPC040_PERCONF
 AND l.ORDEM_CONFECCAO = l2.PCPC040_ORDCONF
 AND l.CODIGO_ESTAGIO = l2.PCPC040_ESTCONF
WHERE l.ORDEM_PRODUCAO = 3160
  AND l.QTDE_PECAS_PROD <> 0
  AND l2.PCPC040_ORDCONF NOT IN (10127, 10128)
  AND l2.PCPC040_ESTCONF = 51
;

UPDATE SYSTEXTIL.PCPC_045 l2
SET
  l2.CODIGO_USUARIO = 99001
, l2.PROCESSO_SYSTEXTIL='pcpc_f046'
, l2.USUARIO_SYSTEXTIL='ANSELMO_SIS'
WHERE l2.PCPC040_PERCONF=1743
  AND l2.PCPC040_ORDCONF in
  (
  SELECT
    l.ORDEM_CONFECCAO
  FROM pcpc_040 l
  WHERE l.ORDEM_PRODUCAO = 3160
  )
  AND l2.PCPC040_ESTCONF=51
  AND l2.SEQUENCIA=2
;

SELECT
  o.*
FROM OBRF_082 o
WHERE o.NUMERO_ORDEM = 1486
;

SELECT DISTINCT
  l.SITUACAO_EM_PROD_A_PROD
, count(*)
FROM PCPC_040 l
--WHERE l.ORDEM_PRODUCAO = 4053
GROUP BY
  l.SITUACAO_EM_PROD_A_PROD
;

SELECT DISTINCT
  l.QTDE_PROGRAMADA
, l.QTDE_PECAS_PROG
, l.*
FROM PCPC_040 l
WHERE l.ORDEM_PRODUCAO >= 3981
  AND l.QTDE_PROGRAMADA <> l.QTDE_PECAS_PROG
;

SELECT DISTINCT
  l.CODIGO_FAMILIA
, l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
, l.ORDEM_CONFECCAO
, l.QTDE_PROGRAMADA
, l.QTDE_PECAS_PROG
, l.CODIGO_ESTAGIO
, l.*
FROM PCPC_040 l
WHERE 1=1
  AND l.ORDEM_PRODUCAO = 3981
--  AND l.QTDE_PROGRAMADA <> l.QTDE_PECAS_PROG
  AND l.CODIGO_ESTAGIO = 27
ORDER BY
  l.PROCONF_GRUPO
, l.PROCONF_SUBGRUPO
, l.PROCONF_ITEM
, l.ORDEM_CONFECCAO
, l.CODIGO_ESTAGIO
;

SELECT
  l21.CODIGO_FAMILIA
, l21.PERIODO_PRODUCAO
, l21.ORDEM_CONFECCAO
, l33.*
FROM PCPC_040 l21
JOIN pcpc_040 l33
  ON l33.PERIODO_PRODUCAO = l21.PERIODO_PRODUCAO
 AND l33.ORDEM_CONFECCAO = l21.ORDEM_CONFECCAO
JOIN pcpc_020 o
  ON o.ORDEM_PRODUCAO = l21.ORDEM_PRODUCAO
WHERE o.ALTERNATIVA_PECA = 1
  AND l21.CODIGO_ESTAGIO = 21
  AND l21.CODIGO_FAMILIA <> 0
  AND l33.CODIGO_ESTAGIO = 33
  AND l33.CODIGO_FAMILIA = 0
  AND (  l33.QTDE_PECAS_PROD <> 0
      OR l33.QTDE_CONSERTO <> 0
      OR l33.QTDE_PECAS_2A <> 0
      OR l33.QTDE_PERDAS <> 0
      )
--ORDER BY l21.ORDEM_PRODUCAO DESC
;

UPDATE PCPC_040 l
SET
  l.CODIGO_FAMILIA = 1400
WHERE l.PERIODO_PRODUCAO = 1720
  AND l.ORDEM_CONFECCAO = 2507
  AND l.CODIGO_ESTAGIO = 33
;

SELECT
  *
FROM BASI_140
;

SELECT
  i.CODIGO_BARRAS
, i.*
FROM basi_010 i
WHERE i.NIVEL_ESTRUTURA = 1
  AND i.GRUPO_ESTRUTURA = '0620S'
  AND i.ITEM_ESTRUTURA IN ('0000MA')
;


SELECT
  x.GRUPO_PRODUTO
, x.ORDEM_PRODUCAO
, x.*
FROM TMRP_141 x -- reserva de rolo para OP
WHERE 1=1
--  AND x.GRUPO_PRODUTO = '0620S'
--  AND x.CODIGO_ROLO = 3648
  AND x.ORDEM_PRODUCAO = 3886
;

SELECT
  x.CODIGO_ROLO
, x.ORDEM_PRODUCAO
, x.ROLO_ESTOQUE
, x.*
FROM PCPT_020 x -- cadastro de rolos
WHERE 1=1
  AND x.PANOACAB_GRUPO = 'MA002'
--  AND x.ORDEM_PRODUCAO <> 0
--  AND x.CODIGO_ROLO = 370
--WHERE x.NUMERO_ROLO = 8080
--   OR x.NUMERO_LOTE = 8080
--   OR x.NR_VOLUME = 8080
--   OR x.NR_SOLIC_VOLUME = 8080
--   OR x.NUMERO_PROGRAMA = 8080
--   OR x.NR_ROLO_ORIGEM = 8080
--   OR x.NUMERO_TUBETE = 8080
  AND x.ROLO_ESTOQUE = 3
ORDER BY
  x.CODIGO_ROLO
;

SELECT
  i.CODIGO_BARRAS
, i.*
FROM basi_010 i
WHERE i.NIVEL_ESTRUTURA = 1
  AND i.GRUPO_ESTRUTURA = '00251'
  AND i.ITEM_ESTRUTURA IN ('0000AZ')
--  AND i.SUBGRU_ESTRUTURA IN ('GG')
ORDER BY
  i.ITEM_ESTRUTURA
, i.SUBGRU_ESTRUTURA
;

SELECT
  f.NUM_NOTA_FISCAL NF
, f.BASE_ICMS VALOR
, f.QTDE_EMBALAGENS VOLUMES
, f.DATA_AUTORIZACAO_NFE FATURAMENTO
, CAST( COALESCE( '0' || f.COD_STATUS, '0' ) AS INT )
  COD_STATUS
, COALESCE( f.MSG_STATUS, ' ' ) MSG_STATUS
, f.SITUACAO_NFISC SITUACAO
, f.NATOP_NF_NAT_OPER NAT
, f.NATOP_NF_EST_OPER UF
, n.DESCR_NAT_OPER NATUREZA
, f.CGC_9 CNPJ9
, f.CGC_4 CNPJ4
, f.CGC_2 CNPJ2
, c.NOME_CLIENTE CLIENTE
, COALESCE(
    CASE WHEN f.TRANSPOR_FORNE9
            + f.TRANSPOR_FORNE4
            + f.TRANSPOR_FORNE2 = 0
    THEN 'O PROPRIO'
    ELSE COALESCE( t.NOME_FANTASIA
                 , '(' || f.TRANSPOR_FORNE9 || '/' || f.TRANSPOR_FORNE4 || '-' || f.TRANSPOR_FORNE2 || ')' )
    END
  , '-' ) TRANSP
, f.TRANSPOR_FORNE9
, f.TRANSPOR_FORNE4
, f.TRANSPOR_FORNE2
FROM FATU_050 f
JOIN PEDI_010 c
  ON c.CGC_9 = f.CGC_9
 AND c.CGC_4 = f.CGC_4
 AND c.CGC_2 = f.CGC_2
JOIN PEDI_080 n
  ON n.NATUR_OPERACAO = f.NATOP_NF_NAT_OPER
 AND n.ESTADO_NATOPER = f.NATOP_NF_EST_OPER
LEFT JOIN SUPR_010 t
  ON t.TIPO_FORNECEDOR = 31 -- transportadora
 AND t.FORNECEDOR9 = f.TRANSPOR_FORNE9
 AND t.FORNECEDOR4 = f.TRANSPOR_FORNE4
 AND t.FORNECEDOR2 = f.TRANSPOR_FORNE2
--WHERE rownum = 1
WHERE
  f.NUM_NOTA_FISCAL = 61284
ORDER BY
  f.NUM_NOTA_FISCAL DESC
;


SELECT
  x.GRUPO_PRODUTO
, x.ORDEM_PRODUCAO
, x.*
FROM TMRP_141 x -- reserva de rolo para OP
WHERE 1=1
--  AND x.GRUPO_PRODUTO = 'MA005'
  AND x.CODIGO_ROLO = 9584
--  AND x.ORDEM_PRODUCAO <> 0
;


SELECT
  x.CODIGO_ROLO
, x.ORDEM_PRODUCAO
, x.ROLO_ESTOQUE
, x.*
FROM PCPT_020 x -- cadastro de rolos
WHERE 1=1
--  AND x.PANOACAB_GRUPO = 'MA004'
--  AND x.ORDEM_PRODUCAO <> 0
  AND x.CODIGO_ROLO = 9584
--WHERE x.NUMERO_ROLO = 8080
--   OR x.NUMERO_LOTE = 8080
--   OR x.NR_VOLUME = 8080
--   OR x.NR_SOLIC_VOLUME = 8080
--   OR x.NUMERO_PROGRAMA = 8080
--   OR x.NR_ROLO_ORIGEM = 8080
--   OR x.NUMERO_TUBETE = 8080
ORDER BY
  x.CODIGO_ROLO
;

UPDATE PCPT_020 x
SET
  x.ROLO_ESTOQUE = 1
WHERE x.CODIGO_ROLO = 9584
;

SELECT
  x.*
FROM PCPT_025 x -- confirmação de rolo
WHERE x.CODIGO_ROLO = 9584
;


SELECT
  x.*
FROM TMRP_141 x -- reserva de rolo para OP
WHERE x.CODIGO_ROLO = 9584
;


SELECT
  x.CODIGO_ROLO
, x.ORDEM_PRODUCAO
, x.ROLO_ESTOQUE
, x.*
FROM PCPT_020 x -- cadastro de rolos
WHERE x.CODIGO_ROLO = 9584
;


                SELECT
                  f.NUM_NOTA_FISCAL NF
                , f.BASE_ICMS VALOR
                , f.QTDE_EMBALAGENS VOLUMES
                , f.DATA_AUTORIZACAO_NFE FATURAMENTO
                , CAST( COALESCE( '0' || f.COD_STATUS, '0' ) AS INT )
                  COD_STATUS
                , COALESCE( f.MSG_STATUS, ' ' ) MSG_STATUS
                , f.SITUACAO_NFISC SITUACAO
                , f.NATOP_NF_NAT_OPER NAT
                , f.NATOP_NF_EST_OPER UF
                , n.DESCR_NAT_OPER NATUREZA
                , f.CGC_9 CNPJ9
                , f.CGC_4 CNPJ4
                , f.CGC_2 CNPJ2
                , c.NOME_CLIENTE CLIENTE
                , COALESCE(
                    CASE WHEN f.TRANSPOR_FORNE9
                            + f.TRANSPOR_FORNE4
                            + f.TRANSPOR_FORNE2 = 0
                    THEN 'O PROPRIO'
                    ELSE COALESCE( t.NOME_FANTASIA
                                 , '(' || f.TRANSPOR_FORNE9 || '/' ||
                                   f.TRANSPOR_FORNE4 || '-' ||
                                   f.TRANSPOR_FORNE2 || ')' )
                    END
                  , '-') TRANSP
                , f.PEDIDO_VENDA PEDIDO
                , p.COD_PED_CLIENTE PED_CLIENTE
                FROM FATU_050 f
                JOIN PEDI_100 p
                  ON p.PEDIDO_VENDA = f.PEDIDO_VENDA
                JOIN PEDI_010 c
                  ON c.CGC_9 = f.CGC_9
                 AND c.CGC_4 = f.CGC_4
                 AND c.CGC_2 = f.CGC_2
                JOIN PEDI_080 n
                  ON n.NATUR_OPERACAO = f.NATOP_NF_NAT_OPER
                 AND n.ESTADO_NATOPER = f.NATOP_NF_EST_OPER
                LEFT JOIN SUPR_010 t
                  ON t.TIPO_FORNECEDOR = 31 -- transportadora
                 AND t.FORNECEDOR9 = f.TRANSPOR_FORNE9
                 AND t.FORNECEDOR4 = f.TRANSPOR_FORNE4
                 AND t.FORNECEDOR2 = f.TRANSPOR_FORNE2
                --WHERE rownum = 1
                ORDER BY
                  f.NUM_NOTA_FISCAL DESC
;

        WITH Table_qtd_lotes AS (
        SELECT
          ll.OP
        , ll.COR
        , ll.TAM
        , ll.pacote
        , MIN(ll.OC) OC1
        , CASE COUNT(ll.OC)
          WHEN 1 THEN NULL
          WHEN 2 THEN MAX(ll.OC)
          WHEN 3 THEN AVG(ll.OC)
          END OC2
        , CASE WHEN COUNT(ll.OC) = 3
          THEN MAX(ll.OC)
          ELSE NULL
          END OC3
        FROM (
        SELECT DISTINCT
          TRUNC( (
            row_number()
              over(
              partition BY
                os.PROCONF_ITEM
              , os.PROCONF_SUBGRUPO
              order BY
                os.ORDEM_CONFECCAO
              )
            + 2 )/ 3 ) PACOTE
        , os.ORDEM_PRODUCAO OP
        , os.PROCONF_ITEM COR
        , os.PROCONF_SUBGRUPO TAM
        , os.ORDEM_CONFECCAO OC
        FROM PCPC_040 os
        WHERE os.ORDEM_PRODUCAO = 4000
        GROUP BY
          os.ORDEM_PRODUCAO
        , os.PROCONF_ITEM
        , os.PROCONF_SUBGRUPO
        , os.ORDEM_CONFECCAO
        ) ll
        GROUP BY
          ll.OP
        , ll.COR
        , ll.TAM
        , ll.pacote
        )
        select
          tb.*
        , ( SELECT
			  max( os.QTDE_PECAS_PROG )
			FROM PCPC_040 os
			WHERE os.PERIODO_PRODUCAO = o.PERIODO_PRODUCAO
			  AND os.ORDEM_CONFECCAO = tb.OC1
		  )	QTD1
        , ( SELECT
			  max( os.QTDE_PECAS_PROG )
			FROM PCPC_040 os
			WHERE os.PERIODO_PRODUCAO = o.PERIODO_PRODUCAO
			  AND os.ORDEM_CONFECCAO = tb.OC2
		  )	QTD2
        , ( SELECT
			  max( os.QTDE_PECAS_PROG )
			FROM PCPC_040 os
			WHERE os.PERIODO_PRODUCAO = o.PERIODO_PRODUCAO
			  AND os.ORDEM_CONFECCAO = tb.OC3
		  )	QTD3
        , o.SITUACAO
        , o.PERIODO_PRODUCAO PERIODO
        , o.REFERENCIA_PECA REF
        , t.ORDEM_TAMANHO TAMORD
        , r.NARRATIVA
        from Table_qtd_lotes tb
        JOIN PCPC_020 o -- OP capa
          ON o.ORDEM_PRODUCAO = tb.OP
        JOIN BASI_220 t -- tamanhos
          ON t.TAMANHO_REF = tb.TAM
        JOIN BASI_010 r
          ON r.NIVEL_ESTRUTURA = 1
         AND r.GRUPO_ESTRUTURA = o.REFERENCIA_PECA
         AND r.SUBGRU_ESTRUTURA = tb.TAM
         AND r.ITEM_ESTRUTURA = tb.COR
        ORDER BY
          tb.COR
        , t.ORDEM_TAMANHO
        , tb.pacote
;


  SELECT
    max( os.QTDE_PECAS_PROG ) QTD1
  FROM PCPC_040 os
  WHERE os.PERIODO_PRODUCAO = 1750
    AND os.ORDEM_CONFECCAO = 6709
;

insert into hdoc_035
(codigo_programa, descricao, programa_menu, item_menu_def)
values
('spdf_f001', 'Produtos em Processos', 0, 1)
;

insert into hdoc_033
(usu_prg_cdusu, usu_prg_empr_usu, programa, nome_menu, item_menu, ordem_menu, incluir, modificar, excluir, procurar)
values
('INTERSYS', 1, 'spdf_f001', 'obrf_menu', 1 , 2, 'S', 'S', 'S', 'S')
;

insert into hdoc_033
(usu_prg_cdusu, usu_prg_empr_usu, programa, nome_menu, item_menu, ordem_menu, incluir, modificar, excluir, procurar)
values
('TREINAMENTO', 1, 'spdf_f001', 'obrf_menu', 1 , 2, 'S', 'S', 'S', 'S')
;

SELECT
  x.ROLO_ESTOQUE
, x.TRANSACAO_CARDEX
, x.DATA_CARDEX
, x.*
FROM PCPT_020 x -- cadastro de rolos
WHERE 1=1
--  AND x.ROLO_ESTOQUE = 3
--  AND x.CODIGO_ROLO = 1009 -- 11443
  AND x.CODIGO_ROLO = 11443
ORDER BY
  x.CODIGO_ROLO DESC
;

SELECT
  x.*
FROM PCPT_025 x -- confirmação de rolo
WHERE x.CODIGO_ROLO = 11843
;
